### ISSUE TITLE
Compile error on Ubuntu 20.04

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#1]
I have a clean install Ubuntu 20.04 instance
When I run `npm run package` I get the following error
```
/home/adamfowler/Developer/tools/vscode-swift/node_modules/vsce/out/package.js:136
    return (translations ?? [])
```

**Comment by svanimpe** [comment]
Seems like the version of Node.js that ships with Ubuntu (even in 21.10) is severely outdated. I was able to fix this issue by first completely removing Node.js and its dependencies, and then reinstalling a newer version (16 or 17) from [NodeSource](https://github.com/nodesource/distributions/)

Fortunately, this is only required for building from source.

**Comment by adam-fowler** [comment]
Cheers that resolved it
