### ISSUE TITLE
Merge sourcekit-lsp vscode extension into this extension

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#10]
It might be worthwhile talking to guys from sourcekit-lsp project before doing this.

**Comment by 0xTim** [comment]
I think they're unable to publish it so we'd never be able to add it as a dependency so our only solution is to lift and shift

**Comment by adam-fowler** [comment]
Yeah I have an implementation of a lift and shift, was really simple. If we go for it, it would be good if the source kit-lsp guys ended up pointing to this extension instead of having their own implementation.

**Comment by 0xTim** [comment]
I'm pretty sure a PR to the repo pointing to this extension would be accepted
