### ISSUE TITLE
Re-instate resolve button on package dependency view

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#100]
Sometimes when jumping between branches the package resolve doesn't work. Ideally this wouldn't happen, but it does (Xcode doesn't get this right all the time either). What are your thoughts on adding the resolve button back on package dependency view

@0xTim @svanimpe

**Comment by 0xTim** [comment]
Fine by me - I also think we should add it as an option to the command palette

**Comment by adam-fowler** [comment]
I have a branch with it available as a command. It is dependent on what is the current active folder.

**Comment by adam-fowler** [comment]
Branch is now PR #103

**Comment by adam-fowler** [comment]
#111 fixed this
