### ISSUE TITLE
Support Windows WSL?

### ISSUE THREAD

**Issue by Zingam** [swift-server/vscode-swift#121]
So I consider starting a new Vapor project just on Linux as SwiftNIO is not supported on Windows. Will this extension work with WSL on Windows? Running VSCode on Windows but building and running the Vapor application on WSL/Ubuntu?

**Comment by adam-fowler** [comment]
Can I ask what didn't work on your Mac? It should work. 

You can use VSCode remote container support to build on Linux as long as you have Docker installed. See https://github.com/swift-server/vscode-swift/blob/main/docs/remote-dev.md

I don't know about whether it'll work for WSL.

**Comment by Zingam** [comment]
> Can I ask what didn't work on your Mac? It should work.

After some tinkering I solved the issue.  Sorry about that. 

Docker is an interesting option to check definitely.

**Comment by adam-fowler** [comment]
Keeping this Issue to verify if Windows WSL is supported or even if it is a viable solution compared to Docker.

**Comment by adam-fowler** [comment]
Windows WSL2 should be supported.
