### ISSUE TITLE
not work on my mac

### ISSUE THREAD

**Issue by faimin** [swift-server/vscode-swift#127]
This plugin is not work on my mac, e.g: `Code completion`, but the `Swift Development Environment` can work normally. I'm confused, why is this happening...

**Comment by adam-fowler** [comment]
Hi @faimin 

By not work, what do you mean exactly? 

Also can you give us some platform details, macOS, swift version. Are you able to run swift from the command line ok?

Thanks

**Comment by faimin** [comment]
https://user-images.githubusercontent.com/8207436/151511235-3fbe68f2-daf0-4d53-819d-530b0239ced2.mp4

I recorded a video, `vscode -swift` has no code hint

**Comment by adam-fowler** [comment]
On the command line type `swift --version` to get the swift version. 

In your demonstration do you have a Package.swift or is this a standalone swift file? Currently we don't support standalone swift files. This is a limitation we inherit from sourcekit-lsp. I would hope we can resolve that though. 

Which LSP server are you using while using the Swift Development Environment?

**Comment by faimin** [comment]
This is a standalone swift file in my demonstration.
My Swift Development Environment 's LSP server is `sourcekit-lsp`.

**Comment by adam-fowler** [comment]
I have an idea what this might be. I'll need to check.

**Comment by adam-fowler** [comment]
Ok I just tried to replicate your issue and cannot replicate it. Can you post what `swift --version` outputs.

**Comment by faimin** [comment]
```shell
10:16:18: Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
Target: x86_64-apple-macosx12.0
```

**Comment by adam-fowler** [comment]
If you open a swift file does anything get added to the log?

**Comment by faimin** [comment]
> If you open a swift file does anything get added to the log?

yes, I open a swift file does nothing, then go to the output panel and transform to swift type, get the log

**Comment by adam-fowler** [comment]
And what is in the log? Is it just the swift version?

Have you tried running with a swift package to see if that works?

**Comment by adam-fowler** [comment]
I think I might have found the issue. Currently the extension expects you to have a workspace folder. It currently doesn't work for a single swift file

**Comment by faimin** [comment]
> I think I might have found the issue. Currently the extension expects you to have a workspace folder. It currently doesn't work for a single swift file

Nice. Thank you very much for your contribution, hope this extension gets better and better.
