### ISSUE TITLE
Can't start client SourceKit Language Sever when opening xcode project folder

### ISSUE THREAD

**Issue by StefKors** [swift-server/vscode-swift#128]
<img width="1760" alt="Screenshot 2022-01-28 at 11 14 30" src="https://user-images.githubusercontent.com/11800807/151519765-450cc3f4-efe8-4328-af16-2e7da8acedad.png">

## VS code version
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0

-----------

Any logs I can grab somewhere that might help in debugging the problem?

**Comment by adam-fowler** [comment]
If you go to the output panel and select Swift from the drop down box and post the contents.

**Comment by adam-fowler** [comment]
Xcodeproj is an Xcode file format. I cannot imagine the LSP server sourcekit-lsp supports loading these. 

We should be clearer in the readme that the extension is primarily there to support Swift Packages.
