### ISSUE TITLE
Extension doesn't automatically create launch.json or task.json upon opening SPM Package.

### ISSUE THREAD

**Issue by kneekey23** [swift-server/vscode-swift#140]
I opened this package: https://github.com/awslabs/aws-sdk-swift/tree/main/TestLambdaSdk in VS Code and it did not automatically create the json files for me to launch a debugging session. I had to manually create them in order to debug this package. I did try restarting VS Code as well as disabling the extension and re-enabling it, however I did not try reloading window using the command palette. The package I opened loads a locally generated dependency.

**Comment by adam-fowler** [comment]
I can't replicate this because it is looking for a local package `~/Projects/Amplify/SwiftSDK/aws-sdk-swift/codegen/sdk-codegen/build/smithyprojections/sdk-codegen/s3.2006-03-01/swift-codegen` which I don't have

If you view the Terminal you should see the results of a `swift package resolve`. Does that return any errors?

**Comment by kneekey23** [comment]
No errors from running that command. 

In order to locally generate that package, you can add a `local.properties` file to the root of the repo with the following:
```
onlyIncludeModels=s3.2006-03-01
```
and then run `./gradlew build -p codegen/sdk-codegen` if you have gradle installed.

**Comment by kneekey23** [comment]
yes will try to see if can resolve the dependency from a tag and experience the same issue. @adam-fowler

**Comment by kneekey23** [comment]
changing the Pacakge.swift to use a tagged version of the sdk didn't fix the issue for me either.
```
import PackageDescription

let package = Package(
    name: "TestSdk",
    platforms: [.macOS(.v10_15)],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        //FIXME change this path to be non-localized
//        .package(name: "AWSS3", path: "~/Projects/Amplify/SwiftSDK/aws-sdk-swift/codegen/sdk-codegen/build/smithyprojections/sdk-codegen/s3.2006-03-01/swift-codegen"),
        .package(name: "AWSSwiftSDK", url: "https://github.com/awslabs/aws-sdk-swift", from: "0.2.0")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .executableTarget(
            name: "TestSdk",
            dependencies: [
                .product(name: "AWSS3", package: "AWSSwiftSDK")
            ],
            path: "Sources/TestSdk",
            resources: [.copy("Resources")]),
        .testTarget(
            name: "TestSdkTests",
            dependencies: ["TestSdk"]),
    ]
)
```

**Comment by adam-fowler** [comment]
Hey @kneekey23 I can't replicate this. I get launch configs generated. What version of swift are you using? Also which version of the extension do you have?

**Comment by kneekey23** [comment]
```
 $ swift --version
swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
Target: x86_64-apple-macosx11.0
```
and version 0.2.0 of the extension. hm I wonder where I am going wrong. I do have other swift extensions installed, could they be conflicting? Should I try un-installing extensions to see if I can get it to work?

**Comment by adam-fowler** [comment]
@kneekey23 are you still having issues with this Package? If so, I've a couple of questions
- when you load it, does the package dependencies view appear?
- if you run `swift package describe --type json` is the first line of the text a warning?

**Comment by kneekey23** [comment]
yes I am. I tried removing all my other extensions and reloading it and it still didnt create the Tasks for me so I put them back.

- when you load it, does the package dependencies view appear? No

- if you run swift package describe --type json is the first line of the text a warning?  No
```
 $ swift package describe --type json
{
  "dependencies" : [
    {
      "identity" : "swift-codegen",
      "name" : "AWSLambda",
      "url" : "/Users/nickik/Projects/Amplify/SwiftSDK/aws-sdk-swift/codegen/sdk-codegen/build/smithyprojections/sdk-codegen/lambda.2015-03-31/swift-codegen"
    }
  ],
  "name" : "TestSdk",
  "path" : "/Users/nickik/Projects/Amplify/SwiftSDK/aws-sdk-swift/TestLambdaSdk",
  "platforms" : [
    {
      "name" : "macos",
      "version" : "10.15"
    }
  ],
  "products" : [
    {
      "name" : "TestSdk",
      "targets" : [
        "TestSdk"
      ],
      "type" : {
        "executable" : null
      }
    }
  ],
  "targets" : [
    {
      "c99name" : "TestSdkTests",
      "module_type" : "SwiftTarget",
      "name" : "TestSdkTests",
      "path" : "Tests/TestSdkTests",
      "sources" : [
        "TestSdkTests.swift",
        "XCTestManifests.swift"
      ],
      "target_dependencies" : [
        "TestSdk"
      ],
      "type" : "test"
    },
    {
      "c99name" : "TestSdk",
      "module_type" : "SwiftTarget",
      "name" : "TestSdk",
      "path" : "Sources/TestSdk",
      "product_memberships" : [
        "TestSdk"
      ],
      "resources" : [
        {
          "path" : "/Users/nickik/Projects/Amplify/SwiftSDK/aws-sdk-swift/TestLambdaSdk/Sources/TestSdk/Resources",
          "rule" : "copy"
        }
      ],
      "sources" : [
        "TestSdk.swift",
        "tmp.swift"
      ],
      "target_dependencies" : [

      ],
      "type" : "executable"
    }
  ],
  "tools_version" : "5.5"
}
```

**Comment by adam-fowler** [comment]
So your `swift package describe` output loads fine.
- Can you reply with the contents of the "Swift" output window. (Output tab, select "Swift" from drop down menu)
- You could try running `swift package reset` on your folder and see if that fixes it.

**Comment by kneekey23** [comment]
<img width="1789" alt="Screen Shot 2022-03-01 at 11 09 17 AM" src="https://user-images.githubusercontent.com/8533749/156232958-37ac6441-0d89-42ff-bcd7-14528e01454f.png">
don't even see that?
ran the command

**Comment by kneekey23** [comment]
<img width="1284" alt="Screen Shot 2022-03-01 at 11 10 12 AM" src="https://user-images.githubusercontent.com/8533749/156233054-b963175a-411b-452e-a142-469c6ebf9796.png">
Extension is installed

**Comment by adam-fowler** [comment]
@kneekey23 don't know if you have anytime to look at this, or if you have access to the project but I've added some extra error messaging to v0.5.0 when projects fail to load, which might give us an idea what is happening here

**Comment by Jeffrey-de-Bruijn** [comment]
I am experiencing the same problem.

**Comment by 0xTim** [comment]
@Jeffrey-de-Bruijn is it a SwiftPM package? What version of Swift, VSCode, the extension, OS etc are you seeing it in?

**Comment by adam-fowler** [comment]
> @Jeffrey-de-Bruijn is it a SwiftPM package? What version of Swift, VSCode, the extension, OS etc are you seeing it in? And can you provide the outlet from the extension as described [#140 (comment)](https://github.com/swift-server/vscode-swift/issues/140#issuecomment-1054404467)

Also does it have an executable. launch.json configs are only generated for executables? The extension does not create a tasks.json file

**Comment by Jeffrey-de-Bruijn** [comment]
I retract my comment, the problem turned out to be different.

**Comment by adam-fowler** [comment]
Closing this as it has never been reported since.
