### ISSUE TITLE
Windows: Verify multi-folder workspaces work correctly

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#157]
- [ ] Check build tasks are created for all folders in a workspace. Press Ctrl+Shift+B. There should be build targets for tests and executables. Check each build task works.
- [ ] Check launch.json configuration files are created for all folders in a workspace. There should be launch configurations generated for each executable (currently if also generates a test launch configuration, but this will be removed once the test explorer is fully operational)
- [ ] Check LSP server works for each folder. Easiest way to do this is to check symbol name completion.
- [ ] Check Package dependency view updates based on what file you have open. Should display package dependencies for the package the file belongs to.

**Comment by stevapple** [comment]
> Check build tasks are created for all folders in a workspace. Press Ctrl+Shift+B. There should be build targets for tests and executables. Check each build task works.

Failed. Is it required that every folder is a SwiftPM project?

![A616B4DD-A223-4819-97F4-D017CBF4F24C](https://user-images.githubusercontent.com/26525394/156165185-735853dd-6fc1-422c-8b3e-01dbe238b828.png)

**Comment by stevapple** [comment]
> I think the max number it will show at any one point is 9

I believe that’s the point. VS Code limitation?

**Comment by adam-fowler** [comment]
You should be able to scroll that list though

**Comment by adam-fowler** [comment]
Doesn't make it very helpful, but a scroll bar will appear when the mouse moves over it

**Comment by stevapple** [comment]
> You should be able to scroll that list though

I’ve scrolled it to bottom already😢 Then it seems more likely a bug of the plugin.

**Comment by adam-fowler** [comment]
@stevapple If you replicate this again, can you go to the output pane, and select swift from the drop down and paste the contents here cheers

**Comment by stevapple** [comment]
@adam-fowler I think I've located the problem. It turns out that the plugin isn't activated before we access any Swift source file; and even we already opened a Swift file, it will only detect, resolve and generate tasks for the package the file is in.

Is this misbehavior or not?

**Comment by adam-fowler** [comment]
> @adam-fowler I think I've located the problem. It turns out that the plugin isn't activated before we access any Swift source file; and even we already opened a Swift file, it will only detect, resolve and generate tasks for the package the file is in.
> 
> Is this misbehavior or not?

This is the case for packages in subfolders, but not for packages at the root of a workspace folder. Well at least that should be the case.

**Comment by stevapple** [comment]
I noticed frequent `focus: undefined` and `unfocus: undefined` in Swift plugin output.

**Comment by adam-fowler** [comment]
You've enter a folder outside of an SPM project

**Comment by stevapple** [comment]
Nice to hear that’s expected behavior.

**Comment by stevapple** [comment]
@adam-fowler I may need more details on how this feature is triggered.  I tried on macOS and also failed to retrieve Swift build tasks (nor did Code activated Swift plugin).

**Comment by adam-fowler** [comment]
How are you building your workspace? Are you using `Add Folder To Workspace...`?

**Comment by stevapple** [comment]
I may be misunderstanding this feature. Retrying found all features okay.

**Comment by stevapple** [comment]
Just met SourceKit-LSP crash once (cannot reproduce). Does it need an issue?
```
2022-03-03 19:29:27.555 sourcekit-lsp.exe[3696:33b4] Failed to dynamically register for workspace/executeCommand: ResponseError(code: LanguageServerProtocol.ErrorCode(rawValue: -32603), message: "Request client/registerCapability failed with message: command \'semantic.refactor.command\' already exists")
```

**Comment by adam-fowler** [comment]
> Just met SourceKit-LSP crash once (cannot reproduce). Does it need an issue?
> 
> ```
> 2022-03-03 19:29:27.555 sourcekit-lsp.exe[3696:33b4] Failed to dynamically register for workspace/executeCommand: ResponseError(code: LanguageServerProtocol.ErrorCode(rawValue: -32603), message: "Request client/registerCapability failed with message: command \'semantic.refactor.command\' already exists")
> ```

Ah bugger I thought I had fixed all of those. It is me trying to run two LSP servers at the same time. Do you have the swift output channel still from when that happened. Yes a separate bug would be good

**Comment by adam-fowler** [comment]
I have re-worked the lsp server restart in #178 hopefully this will fix the issue you mention above. 
Otherwise I think everything else here is resolved so I'm closing
