### ISSUE TITLE
Empty `.lock` files created at root

### ISSUE THREAD

**Issue by stevapple** [swift-server/vscode-swift#161]
- Windows 10
- swift-DEVELOPMENT-SNAPSHOT-2022-02-03-a
- Visual Studio Code 1.64.2 (system)
- sswg.swift-lang 0.3.0

![8D43C973-741A-48C7-8822-E30264BAC414](https://user-images.githubusercontent.com/26525394/156181535-fc5559e9-1631-490a-91df-e051dc73e691.png)

**Comment by adam-fowler** [comment]
I'm guessing those are created by SPM. I haven't seen them on either macOS or Linux though.

@compnerd @tomerd any idea why we might be seeing lock files like this?

**Comment by compnerd** [comment]
They are indeed created by SPM.  The files are meant to be empty, they are used for locking.  There were some synchronization improvements that @tomerd had implemented which moved the lock files around.

**Comment by adam-fowler** [comment]
Would it not be better to stick these in the `.build` folder

**Comment by tomerd** [comment]
These go in the user's temp directory. not sure how they ended up at the "tests" directory in this case. could be a Windows bug in how the temp directory is calculated.

**Comment by adam-fowler** [comment]
@tomerd It's not the tests folder they are in. It is at the same level as the Package.swift

**Comment by adam-fowler** [comment]
@stevapple Do you want to add a bug to bugs.swift.org. This isn't something I can track. Once it is in, can you close this.

**Comment by tomerd** [comment]
@stevapple can you test the behavior of temp dir computation on Windows? that seems to be isolated enough

**Comment by compnerd** [comment]
FWIW, I have a bunch of them in my temporary directory:

```
C__Users_compnerd_.swiftpm.lock
C__Users_compnerd_.swiftpm_security_fingerprints.lock
C__Users_compnerd_AppData_Local_Temp_org.swift.swiftpm_manifests_manifest.db.lock
C__Users_compnerd_AppData_Local_Temp_org.swift.swiftpm_repositories.lock
C__Users_compnerd_AppData_Local_Temp_org.swift.swiftpm_repositories_swift-argument-parser-139e172a.lock
C__Users_compnerd_AppData_Local_Temp_org.swift.swiftpm_repositories_swift-argument-parser-59ba1edd.lock
C__Users_compnerd_AppData_Local_Temp_org.swift.swiftpm_repositories_swift-collections-51f90653.lock
C__Users_compnerd_AppData_Local_Temp_org.swift.swiftpm_repositories_swift-crypto-02716821.lock
C__Users_compnerd_AppData_Local_Temp_org.swift.swiftpm_repositories_swift-driver-0ca7b7a4.lock
C__Users_compnerd_AppData_Local_Temp_org.swift.swiftpm_repositories_swift-llbuild-0f2964f9.lock
C__Users_compnerd_AppData_Local_Temp_org.swift.swiftpm_repositories_swift-system-b9feb0b6.lock
C__Users_compnerd_AppData_Local_Temp_org.swift.swiftpm_repositories_swift-tools-support-core-1e273aae.lock
C__Users_compnerd_AppData_Local_Temp_org.swift.swiftpm_repositories_Yams-00fc82b0.lock
```

I've seen other failures such as Foundation and dispatch being built with an older compiler (because incrementals), but I've never seen this behaviour in the repositories that I regularly build (swift-driver, sourcekit-lsp, swift-package-manager, swift-format, swift-win32, ...).

**Comment by adam-fowler** [comment]
Closing this as this appears to be an issue with SPM and not the VSCode extension.
