### ISSUE TITLE
Append `--enable-test-discovery` only when Swift < 5.4

### ISSUE THREAD

**Issue by stevapple** [swift-server/vscode-swift#166]

**Comment by adam-fowler** [comment]
I've seen issues with not appending this when a `LinuxMain.swift` exists in the project

**Comment by stevapple** [comment]
> I've seen issues with not appending this when a `LinuxMain.swift` exists in the project

How about not appending on Swift >=5.4 and no `LinuxMain.swift`? This would suppress the deprecation warning.
