### ISSUE TITLE
Split Build all task (with/without tests)

### ISSUE THREAD

**Issue by stevapple** [swift-server/vscode-swift#167]

**Comment by adam-fowler** [comment]
Not sure about this one. Don't really want to clutter the build list too much
If you are building an executable it will not build the tests 
If building a library, Xcode builds the tests always

**Comment by stevapple** [comment]
I knew little about Xcode's behavior, and was proposing this based on the CLI interface of SwiftPM.

On Windows, some packages may build, but there tests are not ready yet.  In order to verify whether a package can be built, it's necessary to not build the tests, which are already known to be broken.

**Comment by adam-fowler** [comment]
I'm going to close this. If you really want to build without tests you can always create a tasks.json entry
