### ISSUE TITLE
Package dependencies view assumes we only have one project

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#17]
If I have two projects in my workspace the package dependencies doesn't update based on which project I am editing.

**Comment by svanimpe** [comment]
Yeah this will require support for multi-root workspaces.

**Comment by adam-fowler** [comment]
Just realised the workspace root ends up being the original folder, so you end up adding file watchers for the original folder again. So you have two watchers for `Package.swift`. So if we go for multi root workspaces or not it is a bug to be fixed.

**Comment by svanimpe** [comment]
What exactly is the situation here? Do you have a single-root workspace (single folder open) that contains multiple Swift projects? And there's file watchers for all **Package.swift** files?

**Comment by adam-fowler** [comment]
It seems a little random, sometimes when you add another folder to the workspace it calls `activate` another time. Because you are only ever using the first workspace folder it adds additional file watchers to the original Package.swift.

I think for the moment while we consider the project to be single-root you should jump out of activate if the number of workspaceFolders is greater than 1. Although I'm not sure what would happen if you loaded a workspace with multiple folders if it would activate with two folders straight off

**Comment by adam-fowler** [comment]
Ignore this I've worked out what is going on. When you add a folder to a single folder workspace it creates a new workspace which calls the `activate` function again. I thought it was calling activate for every new folder being added to the workspace. I am going to add an issue for support multiple folder workspaces. I have a cool idea

**Comment by adam-fowler** [comment]
Actually going to reopen as this is still a valid issue if we do move to multi folder workspaces

**Comment by adam-fowler** [comment]
This is now fixed
