### ISSUE TITLE
Add location information to TestItems to enable jump to code

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#192]
It would be good to jump to the source code for a test when you double click on the test in the test explorer (In a similar manner to Xcode).
This requires we get more information about tests. Currently we are getting test list via `swift test --list-tests` which only gives you the list of tests and no more information. There is a possibility we could get test information from sourcekit-lsp along with extra information like the file they are in and where in that file they are.

**Comment by adam-fowler** [comment]
We have this enabled once a file has been opened, unfortunately cannot get it working for all files at startup

**Comment by adam-fowler** [comment]
Would be good if SwiftPM was able to provide the location data in `swift test --list-tests`.

**Comment by adam-fowler** [comment]
Looks like we are going to look at a SourceKit-LSP solution for this.

**Comment by Zingam** [comment]
Shall we wait for https://github.com/apple/swift-package-manager/issues/5601 to be implemented?

**Comment by adam-fowler** [comment]
Actually, this is most likely going to done via a custom LSP request. I just haven't got around to chasing it up.

**Comment by adam-fowler** [comment]
SourceKit-LSP issue added https://github.com/apple/sourcekit-lsp/issues/611

**Comment by adam-fowler** [comment]
SourceKit-LSP request `workspace/tests` is available in Swift 6
Code using it in VSCode can be found in #701
