### ISSUE TITLE
Extension only partly works on Windows

### ISSUE THREAD

**Issue by stefanspringer1** [swift-server/vscode-swift#195]
Building a project works, but e.g. code completion and jumping to a definition do not work.

The documentation says "You'll be prompted to install and configure the CodeLLDB extension, which you should do so", but that did not happen, could this be a reason?

Environment: Swift Language Support for Visual Studio Code 0.3.0, VS Code 1.65.2, Swift 5.5.3, Windows 11.

It also seems that the path to Swift and the path to the toolchains have to be provided in the settings, although it should not be necessary when swift.exe in PATH? I am not sure about that, since it is difficult to find the build the comamnd to build release or debug in the command list, sometimes it seems to be there, and sometimes not.

**Comment by adam-fowler** [comment]
@stevapple Are you able to help here?

**Comment by stevapple** [comment]
> @stevapple Are you able to help here?

I'll try when I have time. Up till now I was testing all these features with the `main` snapshots.

Hope that's not Windows 11 issue:) I have no Windows 11 compatible device yet.

**Comment by stefanspringer1** [comment]
> > @stevapple Are you able to help here?
> 
> I'll try when I have time

Thanks. Please tell me when I should try out something or give you more information.

**Comment by adam-fowler** [comment]
The CodeLLDB prompt not appearing has been reported earlier on Windows. It isn't a huge issue. You should install the extension manually.

Q: What happens if you don't provide a path for swift? Does it not find the swift executable?

One thing to check when you startup is whether there is a "Swift" output pane. Go to the Output view and select "Swift" in the drop down (if it doesn't exist the extension failed to start, most likely because it didn't find the swift executable). The output pane should have your version of Swift, which folder SourceKit LSP is working from and events on folders like "add", "focus" and when swift resolve/update tasks start and complete.

About the build tasks not appearing, the extension needs to load your Package.swift before it can create build tasks, so they won't be available straight off. There is an indicator in the information bar at the bottom indicating whether packages are being loaded.

**Comment by stefanspringer1** [comment]
The "CodeLLDB" extension was already installed.

**Comment by jonha892** [comment]
Similar issue here on WSL2 (ubuntu 20.04), swift 5.6 and vscode-swif x0.4.1.

I wasn't prompted to install CodeLLDB. When I wanted to manually install it it was already installd.
However, the code-competion, jump to definition etc. doesn't work.

I noticed that the "Runtime Status" of the extention has an uncaught error "missing expected parameter: params". Does that help?

![grafik](https://user-images.githubusercontent.com/4357767/161448514-a9b14835-e93a-461d-9ea6-5598da118130.png)

I can see that the extention is working to some extend.
After building my project, the extention finds and can build + excecute tests them.
Although during debugging it doesn't show the state of variables. It only lists the register contents.
Maybe that functionality doesn't exist yet but I'd expect the variable `t` and `s`to be listed under local variables (and hovering on them should probably show their value).

![grafik](https://user-images.githubusercontent.com/4357767/161448227-fa2b4953-d203-4b2e-85b7-be5242655979.png)

**Comment by adam-fowler** [comment]
@jonha892 Can you create a separate bug for WSL.  There is a chance the issues are different from the standard Windows version. Also when adding the bug can you go to the Output view and select Swift from the drop down list. And include the contents of that in the bug. It'll possibly include some useful information.

**Comment by ARKAD97** [comment]
> I noticed that the "Runtime Status" of the extention has an uncaught error "missing expected parameter: params". Does that help?,


Same here on regular Ubnutu 20.04 machine, swift-5.5.2-RELEASE, vscode extension v0.4.1

**Comment by adam-fowler** [comment]
@stefanspringer1 Does v0.4.3 resolve any of the issues you were seeing? As long as your workspace only has one Package.swift in it code completion should be working fine.

**Comment by stefanspringer1** [comment]
@[adam-fowler](https://github.com/adam-fowler) I did not see a version number, but it was updated on April 5th which then should be v0.4.3, and :-) code completion works. When choosing "Go to definition" from the context menu, a kind of progress animation runs on top of the editor pane, but nothing else happens.

**Comment by adam-fowler** [comment]
Hi @stefanspringer1 

I believe "Go to definition" requires the project to be fully indexed. You should build the project and see if it works after that. Full indexing requires a built project. Indexing for a large project will take time. 

Do you get a API documentation window when hovering above a symbol?

**Comment by stefanspringer1** [comment]
@adam-fowler OK, after a successful build, "go to definition" does work. The API documentation when hovering then also works (do not know if the API doc worked before).

Maybe this should be documented that a successful build is needed for some features to work?

Anyway, great work, thanks! (From my perspective, you could close the issue.)
