### ISSUE TITLE
Tasks not showing up

### ISSUE THREAD

**Issue by marius-se** [swift-server/vscode-swift#2]
I just build and installed the extension, but for some reason the tasks are not showing up. I'm pretty new to VSCode and only have one other extension installed (sourcekit-lsp).

Details:
Ubuntu 21.10
Node v17.2.0
NPM 8.1.4

What else do we need to solve this? Any logs?

By the way: I'd be happy to contribute once I got used to Linux and VSCode!

**Comment by svanimpe** [comment]
Hi Marius,

Did you relaunch VS Code after installing the extension?
Did you open a folder (not a single file) that contains a Package.swift file?

**Comment by marius-se** [comment]
2x Yes. I also disabled the sourcekit-lsp extension and restartet my machine.

**Comment by svanimpe** [comment]
I don't have logs yet, but you can try the following:

> Alternatively, if you just want to try this extension without installing it, open this project in Visual Studio Code and press F5 to launch an instance of Visual Studio Code with the extension enabled.

In the terminal of your host instance, there should be a message that says the extension is activating. Then, you can check if this method:

https://github.com/swift-server/vscode-swift/blob/b5aa5129be0eef9df4dd484d3d20431fa6565554/src/SwiftTaskProvider.ts#L97

gets called when you go to **Terminal ▸ Run Task...** and select the **swift** folder.

You can also set breakpoints in the host instance if you want to debug the extension.

**Comment by marius-se** [comment]
Alright, I'll give that a try tomorrow.

**Comment by marius-se** [comment]
I think I found the problem: 

![image](https://user-images.githubusercontent.com/44228394/144775843-2d447df4-6f3d-4060-acee-47ba65315bb7.png)

I do have Swift in my $PATH. 'swift --version' works.

**Comment by marius-se** [comment]
I looked up how the exec function works: It spawns a sh child process. So I opened a sh session to see if I can access `swift` there: No, `swift` (the path/ link) does not exist in there. Is that an issue on my end or can we change something here (i.e. providing an option to set the swift toolchain path)?

**Comment by adam-fowler** [comment]
You could also have it recognise which SHELL vscode was run in and use that SHELL for running swift

**Comment by svanimpe** [comment]
I'm trying to understand what exactly is the problem here.

@marius-se

- How did you install Swift? I'm thinking maybe I don't have this problem because I use the native packages from [swiftlang.xyz](https://www.swiftlang.xyz), which put `swift` in `/usr/bin`.
- Can you run `/bin/sh -c 'swift --version'`? Does that work?
- Can you try adding `options.shell = process.env.SHELL;` as the first line in the **utilities.ts** `exec` function?. Does that fix it for you?

@adam-fowler

W.r.t. that configuration option: I assume that would also be required when a user wants to experiment with a different release or build of Swift? If so, maybe we can add it as an advanced option, because it really shouldn't be required for normal usage.

**Comment by marius-se** [comment]
I followed the guide on swift.org (1. install dependencies 2. download swift and store it "somewhere" 3. include that location in $PATH in my `.bashrc`.)

> Can you run /bin/sh -c 'swift --version'? Does that work?
No that does not work.

> Can you try adding options.shell = process.env.SHELL; as the first line in the utilities.ts exec function?. Does that fix it for you?
Yes! That fixes it for me!


I agree, it would be cool if users don't have to configure anything by default, tho an option to specify which swift toolchain to use is not a bad idea.

**Comment by svanimpe** [comment]
Thanks. So the error is that `exec` uses the Dash shell in this case, which doesn't have its PATH set up to include Swift.

Adding `options.shell = process.env.SHELL` may be the best solution here, as it will cause the least surprises. Whatever shell the user is using to launch VS Code is most likely also the shell they'd use to launch Swift?

I'll try that out later this week, to see if it doesn't cause any issues on Mac or Windows.

**Comment by 0xTim** [comment]
> Whatever shell the user is using to launch VS Code is most likely also the shell they'd use to launch Swift?

This certainly seems like a sensible default

**Comment by marius-se** [comment]
Interesting! Many thanks for debugging! 🙌🏼

**Comment by svanimpe** [comment]
I've tried this out on all platforms. Turns out this doesn't actually use the shell that was used to launch VS Code. It simply uses whatever shell the user has in $SHELL, but that should be fine too.

On Windows, the value of $SHELL was undefined for me, so `exec` used the default shell.
