### ISSUE TITLE
Configuration setting to disable auto-editing of launch.json

### ISSUE THREAD

**Issue by jtbandes** [swift-server/vscode-swift#201]
In some projects `.vscode/launch.json` is checked in to source control. However, any time I open a folder, the extension adds missing Swift package items to launch.json if I previously removed them. This is kind of annoying since I either have to check them in or keep ignoring/reverting the changed files. It would be great if there were an extension setting to prevent auto-updating launch.json — or better, don't auto-update by default (just ask the user).

Similar prior art I'm aware of is the C/C++ extension which automatically edits settings.json to add file associations for C++ STL headers; there is an option `"C_Cpp.autoAddFileAssociations": false` to disable this behavior.

Thanks for considering! 🙏

**Comment by adam-fowler** [comment]
Closing in favour of #168
