### ISSUE TITLE
Error: "Cannot read property 'pins' of undefined" with Swift 5.6

### ISSUE THREAD

**Issue by tonyarnold** [swift-server/vscode-swift#202]
**Describe the bug**
When updating my tools version to Swift 5.6, the extension no longer presents any package dependencies, just an ellipse ("…"). The error shown in the title of the issue is presented: 

```
Cannot read property 'pins' of undefined
```

**To Reproduce**
1. Ensure that you have Xcode 13.3 installed and set as your default CLI tools.
1. Set your Package description's tools version to `// swift-tools-version:5.6`.
2. If it's not already open, open the project using VSCode.
3. Wait until the Package Dependencies pane opens.

**Expected behavior**
A list of my project's packages are shown as with previous releases.

**Environment**
 - OS: macOS 12.3
 - Swift version: `swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)`
 - Visual Studio Code version: 1.65.2
 - vscode-swift version: 0.3.0

I'm happy to provide any additional info that might be helpful.

**Comment by adam-fowler** [comment]
Hi @tonyarnold 

I'm going to need your Package.swift and Package.resolved to work out what is going on here. Is that ok to supply them?

cheers

**Comment by tonyarnold** [comment]
Sure thing - here they are: https://gist.github.com/tonyarnold/2c28b8f10cd934c9930acfc712ce1cad

**Comment by adam-fowler** [comment]
I can see what the issue is now. Hopefully be able to get a solution out soon

**Comment by tonyarnold** [comment]
Thanks, @adam-fowler! Much appreciated. Do you have an ETA on when this might appear in an update to the extension?

**Comment by adam-fowler** [comment]
Included in v0.4.0

**Comment by adam-fowler** [comment]
> Aargh looks like I messed up the release and that change didn't make it. I'll do a 0.4.1

Ignore that it did make it in
