### ISSUE TITLE
Linux Aarch64: Activating extension 'sswg.swift-lang' failed: Cannot find swift executable..

### ISSUE THREAD

**Issue by cntrump** [swift-server/vscode-swift#218]
[vscode-swift](https://marketplace.visualstudio.com/items?itemName=sswg.swift-lang) not works, but another [SourceKit-LSP](https://marketplace.visualstudio.com/items?itemName=pvasek.sourcekit-lsp--dev-unofficial) is fine.

**To Reproduce**
1. `Ctrl` + `Shift` + `X`, install `vscode-swift` extension 
2. Sourcekit-lsp:Toolchain Path -> `/opt/swift-toolchain/usr`
3. Open a SPM workspace contains `Package.swift`
4. Runtime Status of Swift extension: `Not yet activated`
5. `Ctrl` + `Shift` + `I`, Open `Toggle Developer Tools`, see error:
    ```
    Activating extension 'sswg.swift-lang' failed: Cannot find swift executable..
    ```

**Expected behavior**
vscode-swift activated automatically when I open Swift workspace.

**Environment**
 - OS: `Ubuntu Desktop 20.04 arm64`
 - Swift version: 
    ```
    Swift version 5.6 (swift-5.6-RELEASE)
    Target: aarch64-unknown-linux-gnu
    ```
 - Visual Studio Code version: `1.65.2`
 - vscode-swift version: `v0.4.1 Preview`

**Additional context**

Download `code_1.65.2-1646922911_arm64.deb` from https://code.visualstudio.com/download

Install via `sudo apt-get --fix-broken install ./code_1.65.2-1646922911_arm64.deb`

Install Swift toolchain from https://swift-toolchain.com

**Comment by adam-fowler** [comment]
Is the swift executable in your PATH? If not you need to set the path in the `swift.path` config value. You shouldn't need to set the LSP toolchain path after that.

**Comment by cntrump** [comment]
> Is the swift executable in your PATH? If not you need to set the path in the `swift.path` config value. You shouldn't need to set the LSP toolchain path after that.

yes, `swift` is in $PATH.

I have set:

swift.path: `/opt/swift-toolchain/usr/bin/swift`

sourcekit-lsp.serverPath: `/opt/swift-toolchain/usr/bin/sourcekit-lsp`

sourcekit-lsp.toolchainPath: `/opt/swift-toolchain/usr`

**Comment by adam-fowler** [comment]
swift-path should be `/opt/swift-toolchain/usr/bin/`. See it's description "The path of the folder containing the Swift executables"
Once you get the swift-path correct you shouldn't need to set the LSP paths

**Comment by adam-fowler** [comment]
As an aside can you verify that swift is in your $PATH. It should work straight off if it is in your $PATH. Open a terminal in VSCode and type `swift --version` and see what it returns.

**Comment by cntrump** [comment]
> swift-path should be `/opt/swift-toolchain/usr/bin/`. See it's description "The path of the folder containing the Swift executables"
> Once you get the swift-path correct you shouldn't need to set the LSP paths

works! thanks for help me 😀
