### ISSUE TITLE
The extension isn't showing the error

### ISSUE THREAD

**Issue by r4rmas** [swift-server/vscode-swift#221]
The error should be highlighted

<img width="1512" alt="Captura de Pantalla 2022-04-02 a la(s) 17 03 44" src="https://user-images.githubusercontent.com/57473003/161402838-1f3d2215-87aa-4f2a-90f4-da8df0befe84.png">

**Comment by adam-fowler** [comment]
Can you please give me some details about your environment?

What platform you are running on, what version of swift you are running, also vscode version and the swift extension version. 

Thank you

**Comment by r4rmas** [comment]
I'm using a MacBook Pro with M1 Pro chip and running it on MacOS Monterey 12.3.1, Swift 5.6, Visual Studio Code 1.66.0 and the Swift extension is v0.4.1.

The content of the output:
<img width="1512" alt="Captura de Pantalla 2022-04-03 a la(s) 22 54 44" src="https://user-images.githubusercontent.com/57473003/161471250-b37d4494-6302-4290-b900-e4b64e101a6a.png">

**Comment by adam-fowler** [comment]
Hmmm, I don't have an M1 yet but maybe soon. I haven't seen any reports of issues from other M1 users. I can't replicate your issue on my intel mac. It looks like the LSP server just hasn't started up. Have you changed any of the config settings? I just noticed it doesn't output an error if the LSP server fails to start. I'm probably doing another release in the next day or so. I'll make sure it outputs an error in this situation in that release

**Comment by adam-fowler** [comment]
Actually I take that back it does output an error so I'm more confused

**Comment by adam-fowler** [comment]
@0xTim you have an M1 Mac don't you. Any ideas?

**Comment by adam-fowler** [comment]
@r4rmas The other thing you could do is set the config setting `Sourcekit-lsp.trace.server` to `verbose`, restart vscode, open your `HelloWorld.swift` file and then copy and paste the contents of the "Sourcekit Language Server" output pane into a comment here.

**Comment by r4rmas** [comment]
I don't know how to set `Sourcekit-lsp.trace.server` to `verbose`, is it a terminal command?

**Comment by adam-fowler** [comment]
> I don't know how to set `Sourcekit-lsp.trace.server` to `verbose`, is it a terminal command?

Go to menu Preferences -> Settings. It will bring up a dialog with all the settings. Expand Extensions and select Swift from the list. This should display all the settings for the swift extension including the one mentioned above.

By the way there has been a couple of patch updates since you posted this. We are now on v0.4.3 which fixes a similar issue to what you are seeing but for Linux.

**Comment by r4rmas** [comment]
It also works on MacOS.

v0.4.3:
<img width="1512" alt="Captura de Pantalla 2022-04-05 a la(s) 22 46 15" src="https://user-images.githubusercontent.com/57473003/161891859-31cc8e76-3dd4-40f8-8117-411900fcdad4.png">

Thanks!

**Comment by vidhanio** [comment]
I am having the exact same error. Syntax errors show, but not type mismatches.
