### ISSUE TITLE
Windows: Running tests keep rebuilding tests

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#249]
When running tests it does a full rebuild of the project before each time a test is run, even when they are already built.

Running `swift build` in shell doesn't require a rebuild, but running tests does for some reason.

@compnerd

**Comment by compnerd** [comment]
Minor update to this - this requires custom arguments to be supplied.  If you are building without any custom arguments, it seems to behave correctly.

**Comment by adam-fowler** [comment]
What arguments were you adding to cause this?

**Comment by compnerd** [comment]
`-Xcc -I -Xcc "%SystemDrive%\Library\sqlite-3.38.0\usr\include" -Xlinker -L -Xlinker "%SystemDrive%\Library\sqlite-3.38.0\usr\lib" -Xlinker "%SDKROOT%\usr\lib\swift\windows\x86_64\swiftCore.lib"`

**Comment by stevapple** [comment]
I guess that’s because we’re using different config for SourceKit-LSP and SwiftPM.

What if you add these to `sourcekit-lsp.serverArguments`.

**Comment by adam-fowler** [comment]
@compnerd can you try `main` and see if this is fixed?

**Comment by compnerd** [comment]
I think that it may not be fixed, but I wouldn't rule out PEBKAC.  It seems that the test explorer isn't updating the view, but the one test that is there does seem to trigger a (partial) rebuild.  This would be better than the previous state in that it was a full rebuild, but still is problematic.
