### ISSUE TITLE
Windows: LLDB library is not being setup correctly

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#250]
When the extension starts up it should setup the LLDB library for CodeLLDB. This appears to not be working on Windows

@compnerd

**Comment by adam-fowler** [comment]
Haha found this 
https://github.com/swift-server/vscode-swift/blob/a86cdacfb92ce4a899c7a9c979bb3ca499e55249/src/WorkspaceContext.ts#L244-L247

**Comment by adam-fowler** [comment]
Apparently using the swift version of LLDB on Windows causes issues (see https://github.com/vadimcn/vscode-lldb/issues/566).

@compnerd you could try removing the above lines and see if this is still the case

**Comment by compnerd** [comment]
That definitely helps!  It now fails with "unknown error" ... I guess that is a step in the right direction?
