### ISSUE TITLE
Add LLDB init commands for running on Windows

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#260]
It looks like Swift LLDB on Windows requires the swiftCore.dll to be loaded before running the debugger. The following lldb command does this
```
process load <path to swiftCore.dll>
```
This can be added in the `initCommands` section to the launch configs built in `createExecutableConfigurations` and `createTestConfiguration` or by setting the `initCommands` field in the LLDB configuration settings.

**Comment by compnerd** [comment]
Correction to this - it was the missing SDK settings.  So this should be `settings set target.sdk <SDKROOT>`.

**Comment by adam-fowler** [comment]
Resolved in #275
