### ISSUE TITLE
swift package sdk command line is `-sdk` not `--sdk`

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#277]

**Comment by stevapple** [comment]
> `swift --help` says the command line param is `-sdk` while extension is asking for `--sdk`.
> 
> @stevapple can you look into this please

I don’t think there’s anything wrong. `-sdk` is for Swift Driver and `--sdk` is for SwiftPM. We’re only using the driver directly with "Run Swift Script" (and indirectly though SourceKit-LSP).

**Comment by stevapple** [comment]
Check out `swift build --help` and it should give `--sdk`.

**Comment by adam-fowler** [comment]
`swift -help` says the opposite, at least on macOS.

**Comment by stevapple** [comment]
> `swift -help` says the opposite, at least on macOS.

Would you mind pasting the output of `swift -help` and `swift build --help`?

**Comment by adam-fowler** [comment]
On both macOS and linux: `swift --help` outputs
```
 -sdk <sdk>              Compile against <sdk>
```
`swift build --help` doesn't output anything for `-sdk` or `--sdk`.

What does Windows output?

**Comment by stevapple** [comment]
> `swift build --help` doesn't output anything for `-sdk` or `--sdk`.

This is a known bug, which has been fixed in `main`. See https://forums.swift.org/t/when-did-swift-build-help-stop-being-useful/56651 and apple/swift-package-manager#4190

**Comment by stevapple** [comment]
SwiftPM always takes `--sdk` as the SDK option flag.
