### ISSUE TITLE
Tests on Windows stopped working on latest (main)

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#280]
Tests on Windows are broken on `main`. It seems related to a `Path` issue as I understand it. 

Unfortunately merging #262 without #275 has broken them in another way.
If this could be looked from the previous commit that would be great https://github.com/swift-server/vscode-swift/commit/ebba42b01b651cf6b0f3f2d83089325061e2404c

**Comment by adam-fowler** [comment]
@stevapple this is the area you were working on (environment vars sent saved in launch config) could you look into this

**Comment by stevapple** [comment]
I’m sorry about having to be absent until this Saturday noon (UTC+8) to prepare for a test) Will look into the issue this weekend, is that acceptable?
