### ISSUE TITLE
Add support for multi-workspace version of sourcekit-lsp

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#281]
See https://github.com/apple/sourcekit-lsp/pull/473
Will require swift 5.7

**Comment by Zingam** [comment]
I don't know if my request is related but here it is. I'd like to use VSCode's [multi-root workspace files `.code-workspace`](https://code.visualstudio.com/docs/editor/multi-root-workspaces) even for a single folder for some reason. The workspace file could look like:

```json5
{
	"folders": [
		{
			"path": "MySwiftProject"
		}
	],
	"settings": {
		"files.autoSave": "afterDelay",
	}
}
```
The extension should handle this case correctly. For example I might want to have separate `settings.json`, `launch.json` per folder. I assume that `.code-workspace` can be commited to a version control system, so it shouldn't contain non-portable settings, preferably.
For example the `lldb` setting gets added to the workspace file. There should be an option to add it to the folder:
```json5
{
    "lldb.library": "/home/hristo/SDKs/Swift/swift-5.6.1-RELEASE-ubuntu20.04/usr/lib/liblldb.so"
}
```
So I had to move this setting manually.

**Comment by adam-fowler** [comment]
@Zingam This is completely different issue can you add a new issue instead.

**Comment by adam-fowler** [comment]
This is merged and ready for release once there is an Xcode beta that includes the sourcekit-lsp changes.
