### ISSUE TITLE
Automatically created tasks don't respect `swift` path specified for the extension

### ISSUE THREAD

**Issue by MaxDesiatov** [swift-server/vscode-swift#287]
**Describe the bug**
When custom path to the Swift toolchain is specified for the extension, automatically created tasks don't use this path.

**To Reproduce**
1. Go to extension settings and specify a custom toolchain path, for example `~/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2022-04-20-a.xctoolchain/usr/bin/`
2. Run a task automatically created by this extension, e.g. `swift: Build All`
3. You can see that the extension still refers to `swift` without the fully specified path. In my case, as I'm trying to use features only available in this custom toolchain, the build fails.

**Expected behavior**
The extension should use the Swift toolchain from the path specified in extension settings.

**Environment**
 - OS: macOS 12.3.1, Xcode 13.3.1
 - Swift version (output of `swift --version`):
```
swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
```
The version of the custom toolchain is 
```
Apple Swift version 5.7-dev (LLVM 0f7d6007e7787bb, Swift 270d100b43f5e33)
```
 - Visual Studio Code version: VS Code 1.66.2
 - vscode-swift version: v0.4.3

**Comment by adam-fowler** [comment]
Did you create a custom version of this task in tasks.json as I can see a bug in the code when resolving those tasks

**Comment by MaxDesiatov** [comment]
No custom version of the task, I stumbled upon this in a freshly created project.

**Comment by adam-fowler** [comment]
Without a `tasks.json` I can't see how that is possible. To test

- I create a new project `swift package init`
- opened the project in vscode
- edited the settings to use another version of swift (downloaded from swift.org)
- Pressed Ctrl+Cmd+B to bring up build tasks and then return to pick the first build task in the list

In this situation it used the correct version of swift. I could tell because it came up with a load of errors I wasn't seeing before
```
objc[95302]: Class _TtCs27_KeyedEncodingContainerBase is implemented in both /usr/lib/swift/libswiftCore.dylib (0x7ff84d19d518) and /Library/Developer/Toolchains/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-04-25-a.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib (0x110a2fa68). One of the two will be used. Which one is undefined.
objc[95302]: Class _TtCs27_KeyedDecodingContainerBase is implemented in both /usr/lib/swift/libswiftCore.dylib (0x7ff84d19d6d0) and /Library/Developer/Toolchains/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-04-25-a.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib (0x110a2fc20). One of the two will be used. Which one is undefined.
...
```

**Comment by MaxDesiatov** [comment]
Looks like the problem isn't with `tasks.json`, but `launch.json`, which I assume the extension creates automatically? After deleting that file I also had to restart VS Code for it to pick the correct path.

**Comment by MaxDesiatov** [comment]
BTW, is the extension supposed to make `swift run` tasks available as well? I'm not seeing any of those in the list of Swift tasks.

**Comment by adam-fowler** [comment]
If your package has executables it will add configurations to `launch.json` for debug and release, so F5 will build (using the generated build tasks) and then run your exe through lldb. 

It doesn't add any `swift run` tasks, it assumes you'll be running the exe's thru LLDB.

**Comment by MaxDesiatov** [comment]
Great, thanks!
