### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ConsoleTVs** [swift-server/vscode-swift#290]
When this extension is enabled there's a high CPU usage, to the point where my macbook pro 16 2019 has to increase the fan speed to a considerable frequency.

I confirm that when the extension is disabled, the activity monitor shows a much smaller CPU usage by vscode.

**Comment by adam-fowler** [comment]
It is most likely sourcekit-lsp. When you are getting higher CPU usage, can you run activity monitor and search for sourcekit, check the amount CPU usage of both `sourcekit-lsp` and `SourceKitService`.

**Comment by ConsoleTVs** [comment]
Will try again but it was named electron the process, also i am using sourcekit using another extension and works fine, let me report back later

**Comment by adam-fowler** [comment]
> Will try again but it was named electron the process, also i am using sourcekit using another extension and works fine, let me report back later

I also just released 0.5.0, can you check using that version

**Comment by ConsoleTVs** [comment]
Since `0.5.0` this issue seems to be fixed. Thanks!
