### ISSUE TITLE
SwiftPM plugin support

### ISSUE THREAD

**Issue by stevapple** [swift-server/vscode-swift#292]
SwiftPM 5.6+ supports custom plugins, and would be useful for specific tasks (like building documents).

**Comment by adam-fowler** [comment]
Yeah I had a quick look at this in relation to the docc plugin. Haven't really worked out how we would deal with the arguments you would pass to plugin.

**Comment by adam-fowler** [comment]
#335 Adds tasks for each swift plugin in a package. You can find them prefixed with swift-plugin. Copies of these can be created in tasks.json and arguments added, also there is a disable-sandbox boolean. This is a start. I'm think of adding a command to display a task list which filters to just swift-plugin tasks.

**Comment by adam-fowler** [comment]
#457 Adds a command to run a command plugin. This brings up a menu of all the command plugins, plus edited ones and you can either select to run a command or edit its configuration.

With this and #335 I think I can close this Issue
