### ISSUE TITLE
PackageDependenciesProvider.getLocalDependencies should use `SwiftPackage`

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#30]
No need to run another swift process to get local packages

**Comment by svanimpe** [comment]
Are you referring to `dump-package`? 

I went for that one because `package describe` doesn't mark local packages as local. The output for local packages also uses the `url` field, so we'd need to do some extra work to figure out if the URL is a path, or actually a URL.

**Comment by adam-fowler** [comment]
Could you not recognise the url field as a folder ie it starts with a "/". Also a local package doesn't have a requirement

**Comment by svanimpe** [comment]
I just wasn't sure if those things always hold true. But if it does, then yes, we can just use the `SwiftPackage` here also.
