### ISSUE TITLE
Failed to setup CodeLLDB message in Codespaces

### ISSUE THREAD

**Issue by damuellen** [swift-server/vscode-swift#302]
**Describe the bug**
Unexpected error message.
Failed to setup CodeLLDB for debugging of Swift code. Debugging may produce unexpected results. Error: error: python failed attempting to evaluate 'print('<!' + lldb.SBHostOS.GetLLDBPath(lldb.ePathTypeLLDBShlibDir).fullpath + '!>')'

**To Reproduce**
Connect to the remote workspace

**Expected behavior**
No message because 'lldb.library' is already set to "/usr/lib/liblldb.so" in remote settings.

**Environment**
 - OS: Ubuntu 18.04.6 LTS
 - Swift version 5.6.1 (swift-5.6.1-RELEASE)
 - vscode-swift version: 1.67.0

**Additional context**
Running in Github codespaces

**Comment by adam-fowler** [comment]
v0.5.2 has been released with a fix for this

**Comment by damuellen** [comment]
Thanks, and great job the extension works great.
