### ISSUE TITLE
Support multi-root workspaces

### ISSUE THREAD

**Issue by Zingam** [swift-server/vscode-swift#322]
I'd like to use VSCode's [multi-root workspace files `.code-workspace`](https://code.visualstudio.com/docs/editor/multi-root-workspaces) even for a single folder for some reason. The workspace file could look like:

```json5
{
	"folders": [
		{
			"path": "MySwiftProject"
		}
	],
	"settings": {
		"files.autoSave": "afterDelay",
	}
}
```
The extension should handle this case correctly. For example I might want to have separate `settings.json`, `launch.json` per folder. I assume that `.code-workspace` can be commited to a version control system, so it shouldn't contain non-portable settings, preferably.
For example the `lldb` setting gets added to the workspace file. There should be an option to add it to the folder:
```json5
{
    "lldb.library": "/home/hristo/SDKs/Swift/swift-5.6.1-RELEASE-ubuntu20.04/usr/lib/liblldb.so"
}
```
So I had to move this setting manually.

A sample setup:

![image](https://user-images.githubusercontent.com/3337419/171274502-4e7f41aa-f3a2-4341-84df-f86720afd9ca.png)

**Comment by Zingam** [comment]
Various setups

```json
{
	"folders": [
		{
			"path": "MySwiftProject"
		}
	],
	"settings": {
		"files.autoSave": "afterDelay",
	}
}
```

```json
{
	"folders": [
		{
			"path": "MySwiftProject"
		},
                {
                        "path": "MySwiftLibrary"
                }
	],
	"settings": {
		"files.autoSave": "afterDelay",
	}
}
```

```json
{
	"folders": [
                {
                        "path": "."
                },
		{
			"path": "MySwiftProject"
		}
	],
	"settings": {
		"files.autoSave": "afterDelay",
	}
}
```

```json
{
	"folders": [
                {
                        "path": "."
                },
		{
			"path": "MySwiftProject"
		},
                {
                        "path": "MySwiftLibrary"
                }
	],
	"settings": {
		"files.autoSave": "afterDelay",
	}
}
```

**Comment by adam-fowler** [comment]
I'm not totally sure what you want here. Is it to add an option to set the LLDB option on just one folder of a workspace?

When manually editing settings VSCode allow you to set them at the user, workspace or folder level.

**Comment by Zingam** [comment]
Maybe the best way would be to create a sample project to illustrate what I imagine the behaviour should be. I'll do it later.

Basically I want to have the Swift project in a subdirectory of a root directory. I figured out that for the extension to reliably work I need to use a workspace file. It appears to work well enough. Yet some setting that are machine specific are set not quite where I'd like them to be. I can move them around but sometimes the extension (I think so) tries to put back the modifications in the wrong places on update.

**Comment by adam-fowler** [comment]
Apart from the LLDB lib setting I setup at start up. VSCode does all the settings saving and the swift extension has no control over where they go. If you have multiple folders in your workspace though, the settings does have an option to set the setting for a folder. Haven't looked into it in great detail though

**Comment by Zingam** [comment]
I want to have a project structure such as:

```
~/MyProjectRoot/
  |
  +--- .vscode/
  |      |
  |      +--- settings.json  - shared settings?  <---- "lldb.library": "/home/xxx/SDKs/Swift/swift-5.6.1-RELEASE-ubuntu20.04/usr/lib/liblldb.so"
  |
  +--- MySwiftProject1
  |      |
  |      +--- .vscode/
  |             |
  |             +--- launch.json
  |             |
  |             \---- Package.swift
  |
  +--- MySwiftProject2
  |      |
  |      +--- .vscode/
  |             |
  |             +--- launch.json
  |             |
  |             \---- Package.swift
  |
  +--- README.md
```

If I use `Open Folder` on the root the extension doesn't detect the `Package.swift` project. If I use a `.code-workspace` the extension works as I expect it to do. I need to do some manual adjustment to the settings/launch.json but it works.

To me it makes sense to put `lldb` setting in the root but then everytime the extension ask me to create it on opening the project.

```
{
    "lldb.library": "/home/hristo/SDKs/Swift/swift-5.6.1-RELEASE-ubuntu20.04/usr/lib/liblldb.so"
}
```

Can we have another option to put the setting in the root folder if there are multiple project in a folder? Does this make sense?

Maybe the extension could look for projects in the subfolders but I guess that would be another feature.

**Comment by adam-fowler** [comment]
Closing this as the issue seems to be with VS Code more than the Swift extension
