### ISSUE TITLE
Inlay hints preferences aren't taken into account with Swift 5.7

### ISSUE THREAD

**Issue by PopFlamingo** [swift-server/vscode-swift#344]
**Describe the bug**
When using Swift 5.7, disabling inlay hints doesn't seem to work (tested in a Linux container), so they are always displayed.

**Environment**
 - VS Code devcontainer with swiftlang/swift:nightly-5.7-focal image
 - Swift version (output of `swift --version`): `Swift version 5.7-dev (LLVM eecf02df5133efe, Swift ad06e7d7251311a)`
 - Visual Studio Code version: `Version: 1.68.1 (Universal)`
 - vscode-swift version: `v0.6.0 preview`

**Additional context**
In my quick tests it seemed to work fine  with older Swift versions

**Comment by adam-fowler** [comment]
Inlay hints and Swift 5.7 are in a state of flux at the moment as we are in the process of moving across to the official LSP spec version of Inlay hints which is now used in VSCode. SourceKit-LSP 5.7 is now generating the official spec Inlay Hints which VSCode picks up automatically. But we still have the old system running as well. We need to release a new version of the extension which disables the old Inlay Hints for Swift 5.7 and above.

The official Inlay Hints display is controlled by VSCode setting `Editor › Inlay Hints`. It has some nice options where you can display the Inlay hints temporarily when a key is pressed.

**Comment by PopFlamingo** [comment]
@adam-fowler Thank you! I didn't know VS Code had something specific its its extension API to make these settings more global.

**Comment by adam-fowler** [comment]
Closing as v0.7.0 adds comment pointing to correct option.
