### ISSUE TITLE
Activating extension 'sswg.swift-lang' failed: Cannot read properties of undefined (reading 'match').

### ISSUE THREAD

**Issue by RickyLiu0w0** [swift-server/vscode-swift#347]
**Describe the bug**
In my swift workspace, the [scode-swift](https://marketplace.visualstudio.com/items?itemName=sswg.swift-lang) not works. 

**To Reproduce**
1. Install vscode-swift extension
2. Create a workspace by command: `swift package init --type executable`
3. Type `xcrun --find sourcekit-lsp` in `Terminal` and the output is
```
Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp
```
4. set `Sourcekit-lsp: Server Path` and `Swift: Path` -> `Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/`
5. Open the workspace contains Package.swift.
6. We can see some error message in ` Toggle Developer Tools`: 
```
Activating extension 'sswg.swift-lang' failed: Cannot read properties of undefined (reading 'match').
``` 
<img width="625" alt="image" src="https://user-images.githubusercontent.com/50950678/178095536-f71ed6bc-5917-4204-b6c8-e0eac8655a39.png">

**Expected behavior**
vscode-swift activated automatically when I open Swift workspace.

**Environment**
 - OS: MacOS 10.15.7
 - Swift version: Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28), Target: x86_64-apple-darwin19.6.0
 - Visual Studio Code version: 1.69.0
 - vscode-swift version: v0.6.0

**Comment by adam-fowler** [comment]
You don't need to set the source kit-lsp path. Although that shouldn't be causing this crash

**Comment by stevapple** [comment]
Looks like the plugin fails to parse Swift version from target info.

What’s the output of `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -print-target-info`?

P.S. Did you intentionally omit the leading slash (in the path), or it just got lost somewhere eg. during copy & paste?

**Comment by RickyLiu0w0** [comment]
> Looks like the plugin fails to parse Swift version from target info.
> 
> What’s the output of `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -print-target-info`?
> 
> P.S. Did you intentionally omit the leading slash (in the path), or it just got lost somewhere eg. during copy & paste?

Oh, I find that I did accidentally omit the leading slash

Here is the screenshot:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/50950678/178097031-e65e3c69-904c-46e2-a94a-129df8c2887a.png">

```json
{
  "target": {
    "triple": "x86_64-apple-macosx10.15",
    "unversionedTriple": "x86_64-apple-macosx",
    "moduleTriple": "x86_64-apple-macos",
    "swiftRuntimeCompatibilityVersion": "5.1",
    "librariesRequireRPath": false
  },
  "paths": {
    "runtimeLibraryPaths": [
      "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx",
      "/usr/lib/swift"
    ],
    "runtimeLibraryImportPaths": [
      "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx"
    ],
    "runtimeResourcePath": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift"
  }
}
```

**Comment by stevapple** [comment]
Looks like Swift 5.3.2 doesn't have `compilerVersion` field in its target info. We should check and fall back to `swift --version` when it doesn’t exist.

**Comment by RickyLiu0w0** [comment]
Thank you, I really appreciate it.

**Comment by adam-fowler** [comment]
We don't really support swift 5.3 as it missing some things that mean that some features of the extension don't work. But we should really produce better error messaging than what you received.

**Comment by stevapple** [comment]
Note that the `compilerVersion` field is introduced in Swift 5.4 by apple/swift#32758. Since this provides the foundation and is not actually some missing feature, maybe a workaround is still preferable.

Better clarify toolchain & feature support state with a table in `README`.

**Comment by adam-fowler** [comment]
Yeah as I said we need better messaging. So we need to recognise older versions of Swift. There are elements of the extension that still work with older version of swift but not all. We should detail what they are either in error messaging or the readme.
