### ISSUE TITLE
Extension seems to be barely functional

### ISSUE THREAD

**Issue by stefanspringer1** [swift-server/vscode-swift#348]
**Describe the bug**
I have no code completion and building seems not to be possible. I could not find the tasks that should exist under "Terminal > Task > ...". I find no good documentation about where those commands should be and how to work with it.

**Environment**
 - masOS resp. Windows
 - 5.6 resp. 5.5
 - Visual Studio Code 1.69.0
 - vscode-swift version: 0.6.0

**Comment by adam-fowler** [comment]
In the output pane there is a dropdown can you select Swift from that dropdown and paste the contents of the window here. It sounds like something didn't initialise properly.

**Comment by stefanspringer1** [comment]
On Windows, newly opening a fresh checked-out project:

12:49:27: [compnerd.org](http://compnerd.org/) Swift version 5.5.3 (swift-5.5.3-RELEASE)
12:49:30: XSwift: add: c:\tmp\XSwift
12:49:30: XSwift: Resolving Dependencies ... 12:49:47: XSwift: resolvedUpdated: c:\tmp\XSwift
done.
12:49:49: XSwift: Resolving Dependencies ... 12:49:49: SourceKit-LSP setup for XSwift
12:49:49: XSwift: focus: c:\tmp\XSwift
done.
12:49:52: XSwift: Test Discovery Failed: error: The operation could not be completed. The file doesn’t exist.

**Comment by stefanspringer1** [comment]
On macOS:

13:04:34: Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
13:04:38: XSwift: add: /Users/stefan/tmp/XSwift
13:04:38: XSwift: Resolving Dependencies ... 13:04:43: XSwift: resolvedUpdated: /Users/stefan/tmp/XSwift
done.
13:04:44: XSwift: Resolving Dependencies ... 13:04:44: SourceKit-LSP setup for XSwift
13:04:44: XSwift: focus: /Users/stefan/tmp/XSwift
done.
13:04:45: XSwift: Test Discovery Failed: error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec/swift/pm/swiftpm-xctest-helper /Users/stefan/tmp/XSwift/.build/arm64-apple-macosx/debug/XSwiftPackageTests.xctest /var/folders/6d/xg7m2lks06lb_glqkmvd00700000gn/T/TemporaryFile.GwmQci output:
    error: unableToLoadBundle("/Users/stefan/tmp/XSwift/.build/arm64-apple-macosx/debug/XSwiftPackageTests.xctest")

**Comment by adam-fowler** [comment]
I'd recommend upgrading to 5.6 on Windows. I think the extension is reliant on features that were not available in the Windows version of Swift 5.5

Build tasks are available from `Terminal -> Run Build Task...` or Ctrl+Shift+B.
There is currently an issue with swift packages in sub-folders. I am currently fixing. How are you loading your projects into your workspace?

**Comment by stefanspringer1** [comment]
I am dragging the folder into VS Code.

Please note that I have **the same problem under macOS with Swift 5.6.1** (see my second comment).

(The project can be opened without a problem in Xcode and CLion – although the CLion plugin for Swift seems not to be very good or updated, probably not using SourceKit...)

**Comment by adam-fowler** [comment]
Can you try opening it either via running `code .` in a terminal (think you have to install the terminal commands to do that) or opening via the menu option `File -> Open ...`

I think by dragging a folder into vscode you add the folder to the current workspace, which means your package.swift is not at the root of the workspace. This currently has issues I am just fixing

**Comment by stefanspringer1** [comment]
I tried to open the project via `code .` or `File -> Open ...`, but no change.

**Comment by adam-fowler** [comment]
In Windows with Swift 5.5?

**Comment by stefanspringer1** [comment]
Tried on macOS. (Also tried on Windows, also did not work, but still using Swift 5.5 on Windows for a reason.)

**Comment by stefanspringer1** [comment]
Might `Test Discovery Failed` be an issue?

**Comment by adam-fowler** [comment]
Test discovery failed is not an issue. It basically means you haven't built the project. I would like to be sure you have it running on macOS first. As that is the platform most used. If you can't get it working there you have no chance with Window 5.5. Can you provide the output you get when you open on macOS using the menu `Open...`. Also does `Cmd+Shift+B` bring up the build tasks menu?

**Comment by stefanspringer1** [comment]
The output is not different from the one that I posted above.

I noted that code completion does work for things defined in the same package, but it does not find things defined in an included package, see screen shots:

Xcode:

<img width="210" alt="Bildschirmfoto 2022-07-11 um 14 00 17" src="https://user-images.githubusercontent.com/5261689/178261496-76e2e4b0-2ced-441c-9aa7-00e74fd66ddd.png">

VS Code:

<img width="241" alt="Bildschirmfoto 2022-07-11 um 13 59 56" src="https://user-images.githubusercontent.com/5261689/178261516-a9f8ea87-a033-481d-9bee-f4248a32f6d6.png">

Bit once you use things from the other package, it knows its members.

In another project, VS Code thinks that a particular included Swift package is an Objective-C package:

```text
could not build Objective-C module 'XSwift' sourcekitd
```

`Cmd+Shift+B` does bring up the build tasks menu.

**Comment by garrettm** [comment]
I am having similar issues, my Swift output looks like:
```
19:46:40: Apple Swift version 5.7 (swiftlang-5.7.0.113.202 clang-1400.0.16.2)
19:46:40: SourceKit-LSP setup
19:46:40: focus: undefined
```

On MacOS, opened with `code .` and also `File -> Open`

**Comment by stefanspringer1** [comment]
What I found (see above) is that in some contexts it does not work or only part of it. That is why I first thought it does not work at all. @adam-fowler: This extension for VS Code is a wonderful thing and I am sure the problems can be resolved. Thank you for your good work!

**Comment by adam-fowler** [comment]
You do need to build your project for some of the code completion, go to symbol features to work fully. This is a limitation of Sourcekit-LSP.

**Comment by adam-fowler** [comment]
@stefanspringer1 do you get the package dependencies view?

**Comment by garrettm** [comment]
@adam-fowler my project does not have a Package.swift file — I don't see build commands. Will it just not work for this use case?

**Comment by adam-fowler** [comment]
> @adam-fowler my project does not have a Package.swift file — I don't see build commands. Will it just not work for this use case?
> 
Yes a Package.swift is required? Is your project an Xcode project?

**Comment by garrettm** [comment]
Yes, it is an Xcode project

**Comment by stefanspringer1** [comment]
@adam-fowler Yes, I see the package dependencies view, and after the project has been built, code completion works. I think it would be an important thing to document this limitation, or even better also have an according warning issued by the extension. So Q: If new stuff gets added, is another build process necessary before the new stuff is known for code completion? And it this a limitation of Sourcekit-LSP that could go away?

**Comment by stefanspringer1** [comment]
...Already testet it on Windows and it works when first built.

>If new stuff gets added, is another build process necessary before the new stuff is known for code completion?

I guess if new packages or versions are included, a new build is necessary for code completion to get new stuff from the included packages.

Another thing I noticed: It seems that even after a build, you have to open the file again (or at least switch back to it).

**Comment by 0xTim** [comment]
> Yes, it is an Xcode project

@garrettm The extension does not support Xcode projects. The primary goal is Swift packages and standalone Swift scripts work mostly as well

**Comment by garrettm** [comment]
Ah okay, bummer. Is Xcode support on the roadmap? Or could it be hacked in easily?

**Comment by stefanspringer1** [comment]
>Ah okay, bummer. Is Xcode support on the roadmap? Or could it be hacked in easily?

I thinks the direction is and should more in the opposite direction, newer Xcode versions added some better support for SPM projects (creating one was not possible with some previous versions if I remember it correctly).

I think VS Code – or, if you are willing to pay a license, also CLion (but only the upcoming version 2022.2) – are very good solutions if you are not working on macOS so cannot use Xcode(*), so they are a good choice for projects that do not target Apple systems exclusively. So I think supporting Xcode projects does not make that much sense for this extension.

---

(*): Yes, some may choose another IDE even on macOS.

**Comment by stefanspringer1** [comment]
>I think by dragging a folder into vscode you add the folder to the current workspace, which means your package.swift is not at the root of the workspace. This currently has issues I am just fixing

Looked OK when I tried again (on macOS).

**Comment by 0xTim** [comment]
> Ah okay, bummer. Is Xcode support on the roadmap? Or could it be hacked in easily?

@stefanspringer1 the extension is a cross-platform effort, supporting Xcode doesn't make sense. The ecosystem also seems to be slowly moving away from Xcode projects (like the new Swift Playgrounds app)

**Comment by stefanspringer1** [comment]
@[0xTim](https://github.com/0xTim) That remark did not come from me. See my answer to this remark. I agree with you.

**Comment by 0xTim** [comment]
@stefanspringer1 apologies, missed out part of the message! Fixed

**Comment by stefanspringer1** [comment]
...So I think, if the issue with having to first build the project if packages are included is documented (or even better also a message is displayed in VS Code), from my point of view, the issue is fixed. (Or building automatically in this case?)

Again, thank you for your good work!

**Comment by adam-fowler** [comment]
@stefanspringer1  Do you think we can close this once #362 is added to README?

**Comment by stefanspringer1** [comment]
Yes, I think so. Thanks.

**Comment by adam-fowler** [comment]
I edited the README and this has been merged. It will come out with the next release
