### ISSUE TITLE
local spm is not shown in the dependency list 

### ISSUE THREAD

**Issue by aelam** [swift-server/vscode-swift#357]
**Describe the bug**

In the developing Package.swift
add the dependency of a local lib (same repo)
```swift
    dependencies: [
        .package(name: "LocalLib", path: "Path/To/LocalLib"),
    ]
```

The localLib can show well in Xcode

**To Reproduce**

**Expected behavior**

shown in the Package dependencies panel

**Environment**
 - OS: [e.g. Ubuntu 20.04]
 - Swift version (output of `swift --version`)
 - Visual Studio Code version:
 - vscode-swift version: v0.6.0

**Additional context**

**Comment by adam-fowler** [comment]
Yep I'm seeing this.

**Comment by adam-fowler** [comment]
#361 should fix this
