### ISSUE TITLE
error: cannot find 'XCTAssertEqual' in scope with iOS swift.buildArguments

### ISSUE THREAD

**Issue by aelam** [swift-server/vscode-swift#358]
**Describe the bug**

* the test target can't be built. 
`/xxx/MyLibraryTests/MyLibraryTests.swift:9:9: error: cannot find 'XCTAssertEqual' in scope` is reported
* lib target build is OK

```json
  "swift.buildArguments": [
    "-Xswiftc",
    "-sdk",
    "-Xswiftc",
    "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk",
    "-Xswiftc",
    "-target",
    "-Xswiftc",
    "arm64-apple-ios15.0-simulator"
```

**To Reproduce**

**Expected behavior**

**Environment**
 - OS:  macosx
 - Swift version (output of `swift --version`)
 - Visual Studio Code version: 
 - vscode-swift version: v0.6.0

**Additional context**

THE OTHER problem, when I put the mouse cursor above `import Alamofire`, `soucekitd`, `swiftc?` tell me that it's incompatible. maybe because it's trying to find the module which building for mac? 
BTW the build path is always `.build/x86_64-apple-macosx` even it's for iOS

I created a pretty simple spm with Alamofire dependency, and set the `swift.buildArguments`  like the above, mainly for testing iOS build.
Please lemme know if there is any missing information

**Comment by adam-fowler** [comment]
I see the issue with XCTest. Not sure how to resolve that one. It isn't really an issue with the extension though. This is an SwiftPM issue with building tests via SwiftPM.

Regarding the Alamofire problem, have you built your app, once including Alamofire? Sourcekit-LSP (The LSP server the extension uses) requires that the app has been built at least once after adding a new dependency.

**Comment by aelam** [comment]
> I see the issue with XCTest. Not sure how to resolve that one. It isn't really an issue with the extension though. This is an SwiftPM issue with building tests via SwiftPM.

oh yes. I think you are right 

`swift build --build-test` works well
but with arguments fails


> Regarding the Alamofire problem, have you built your app, once including Alamofire? Sourcekit-LSP (The LSP server the extension uses) requires that the app has been built at least once after adding a new dependency.

I've set `"swift.backgroundCompilation": true`, there should be no problem. 
it seems right now soucekitd doesn't  show it anything about it now. I forgot what I changed

And when I try to `option + mouse click` alamofire code in my code, it goes to the Alamofire file which is actually in `.build/checkout/Alamofire`. it's not really finding the definition from the built product, (anyway it's great!)

**Comment by adam-fowler** [comment]
By the way I've been running with settings
```json
{
    "swift.buildArguments": [
        "--arch",
        "arm64",
        "-Xswiftc",
        "-target",
        "-Xswiftc",
        "arm64-apple-ios15.0-simulator"
    ],
    "swift.SDK": "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk"
}
```

**Comment by aelam** [comment]
maybe nothing can be done here, you can close it 

but I'd like to paste several interesting related links here


https://github.com/apple/swift-package-manager/pull/5627
https://github.com/apple/swift-package-manager/issues/5619
