### ISSUE TITLE
log of `swift package resolve` shoud be in output rather than the terminal?

### ISSUE THREAD

**Issue by aelam** [swift-server/vscode-swift#363]
**Is your feature request related to a problem? Please describe.**

Not sure if it's the standard way to put the log of `swift package resolve` and other similar logs in the output section of VSCode. right now it's in the terminal.
It seems other extesions print it in the output section and it's easy to choose task from the dropdown list for example, LSP,  LLDB, SwiftFormat

Feel free to close it if you think currently it's the best way 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adam-fowler** [comment]
It is standard for all VS code tasks to output to a terminal. 
Background processes like LSP don't have a related task so use a output pane.
