### ISSUE TITLE
Load `.xcode-version` for vscode-swift and support swift.env in settings.json

### ISSUE THREAD

**Issue by aelam** [swift-server/vscode-swift#364]
**Is your feature request related to a problem? Please describe.**

 I have installed multiple Xcodes, the pattern is like Xcode-13.4, Xcode-14.0, etc and I have installed `xcenv`, in my project I have a `.xcode-version` file,  `xcenv` helps me load the correct commands, SDK for me.  If I can run xcodebuild, xcrun in terminal, it's actually running with the version that is set in `.xcode-version` file

I am wondering if it's possible to support this. 
And also there is another related problem: I have to set all absolute paths for `vscode-swift` such as `swift.SDK`, `swift.buildArguments`.
 
supporting `env` setting and `xcenv` loading, could make the `settings` easier?

**Describe the solution you'd like**

* load .xcode-version 
* path settings can be shell command such as ```-Xswiftc `xcrun --sdk iphonesimulator --show-sdk-path` ```
* add env settings like https://code.visualstudio.com/docs/python/environments

**Describe alternatives you've considered**
Clearly and concisely describe any alternative solutions or features you've considered.

**Additional context**

**Comment by adam-fowler** [comment]
We don't intend to support third party tools like `xcenv` where we cannot control how they are supported.
I'm sure we could add something that could help though. As I understand it all `xcenv` does in the end is set the `DEVELOPER_DIR` environment variable. We could possibly provide a command which displays a list of available of Xcode's and then sets `DEVELOPER_DIR` environment variable in the correct place in the settings.

**Comment by aelam** [comment]
xcenv is quite commonly used by ios development
and the.xcode-version file can be also used by fastlane, very mainstreamed 
in addition, pyenv, rbenv are the same solution which created shims for all the necessary commands and env 

definitely deserve to consider

loading DEVELOPER_PATH is also a great solution tho

**Comment by adam-fowler** [comment]
See #369

**Comment by aelam** [comment]
thank you!

**Comment by adam-fowler** [comment]
Closing in favour of #369
