### ISSUE TITLE
Error: Couldn't start client SourceKit Language Server

### ISSUE THREAD

**Issue by NSExceptional** [swift-server/vscode-swift#367]
**Describe the bug**

This error appears when I install the extension or open a workspace.

**To Reproduce**
1. Install the extension
2. Observe the error message

**Environment**
 - OS: macOS Catalina
 - Swift version: Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28) Target: x86_64-apple-darwin19.5.0
 - Visual Studio Code version: `1.64.2`
 - vscode-swift version: `v0.4.3`

Edit: Also I'm on Xcode 12.4, the last version supported by Catalina

**Comment by adam-fowler** [comment]
Is it possible for you to update to the latest version of vscode-swift?

Also swift 5.3 is not really supported. Some features of the extension require Swift 5.4 or later. But I thought starting the LSP server should be ok.

**Comment by adam-fowler** [comment]
If I remember right you need VS Code 1.65.0 or later to get the latest version of the swift extension.

**Comment by adam-fowler** [comment]
Did you test with the latest version of VS Code and the Swift extension?

**Comment by NSExceptional** [comment]
Hey Adam, sorry for the delay, been occupied lately.

I thought I was on the latest version of everything at the time (except Xcode and Catalina of course) but I'll double check that now and try again.

**Comment by NSExceptional** [comment]
Upon further investigation, I guess Xcode 12 just doesn't come with `sourcekit-lsp`? The extension should probably warn you if it doesn't exist instead of failing the way it does today, heh

Is Xcode 12/Catalina supposed to be supported? If it is, maybe the README could use a "requirements" section under **Installation**. It wasn't immediately clear to me that I had to do any extra setup<sup>1</sup> either because all that section says is that you need Swift installed

> <sup>1.</sup> [_The extension provides language features such as code completion and jump to definition via the Apple project SourceKit-LSP. For these to work fully it is required that the project has been built at least once._](https://github.com/swift-server/vscode-swift#language-features)

If you or anyone knows the hard requirements I can put up a PR

**Comment by NSExceptional** [comment]
Okay hang on, according to the SourceKit-LSP repo, Xcode 11.4+ should come with it… I can run it with `xcrun sourcekit-lsp`, and this causes VS Code to give me a slightly different error:

```
[Error - 6:20:11 PM] SourceKit Language Server client: couldn't create connection to server.
Launching server using command sourcekit-lsp failed. Error: spawn sourcekit-lsp ENOENT
```

I installed the Xcode 12.4 command line tools package, and `sourcekit-lsp` is still not present in `/usr/bin`. On my work computer with Big Sur and Xcode 13, it _is_ there.

Does this extension support running the language server through `xcrun`?

**Comment by NSExceptional** [comment]
As an easy work around, I was able to take the binary from Big Sur and drop it into `/usr/local/bin` on Catalina and point the extension to it. Curious if there's a method that doesn't involve happening to have a copy of this binary on hand

**Comment by adam-fowler** [comment]
Hi @NSExceptional running sourcekit-lsp through `xcrun` won't be supported as the exe we pass to VSCode must be the actual LSP server executable. I imagine VSCode is trying to connect to `xcrun` as if it is the LSP server.

You shouldn't need to copy the executable to `/usr/local/bin`. Just setting the LSP server path to be the output of `xcrun -f sourcekit-lsp` should work.

**Comment by adam-fowler** [comment]
Closing as the above comment should sort out the issue

**Comment by tinder-tannerbennett** [comment]
I forgot to respond, but yes that did work, thank you!

Is there a reason this setting isn't auto-populated with the output of that command @adam-fowler?

**Comment by NSExceptional** [comment]
I forgot to respond, but yes that did work, thank you!

Is there a reason this setting isn't auto-populated with the output of that command @adam-fowler?

**Comment by adam-fowler** [comment]
I was assuming that sourcekit-lsp would be in the same folder as swift. It is the case in every other install of swift I have seen so far.

**Comment by NSExceptional** [comment]
Hasn't been for me, for some reason, on two separate computers. Might be nice to have logic to fall back to the output of the command you gave me, or at least give the user an option to use that output if it's not found in the "standard" location on first run
