### ISSUE TITLE
Package.swift changing could trigger `swift package resolve`?

### ISSUE THREAD

**Issue by aelam** [swift-server/vscode-swift#374]
**Describe the bug**

I watched the behavior of Xcode, when I modify `Package.swift`, `resolve` will be triggered, and the dependencies UI will be updated then
when I debug #370, I was waiting for the updating but finally I've found it's never updated `workspace-state.json`
Maybe we can have the same behavior?

PS: checkout-state.json is also interesting, it may be used for updating the status of UI (like fetching/checking out)

**To Reproduce**

**Expected behavior**

**Environment**
 - OS: [e.g. Ubuntu 20.04]
 - Swift version (output of `swift --version`)
 - Visual Studio Code version:
 - vscode-swift version:

**Additional context**

**Comment by adam-fowler** [comment]
If you edit package.swift it should run a resolve. Are you sure your changes haven't broken this

**Comment by aelam** [comment]
@adam-fowler 

I watched the behavior of Xcode 

if `Package.swift` or `Package.resolved` is modified Xcode will resolve dependency graph automatically, (As far as I know, It's not actually calling `resolve` but `show-dependency`)

The weird point is after `show-dependency` is done it will update `Package.resolved` (I monitored the file system changing of OS)

so it will make a dead loop like `Package.resolved` modified  --> `show-dependency` --> `Package.resolved` modified  --> [dead-loop]

probably we need to cache the content of `Package.resolved` in `SwiftPackage` to check if it's the proper timing to trigger `resolve dependency graph` and then check the checksum of it and then don't trigger again

The other simple way is that we don't trigger `resolve dependency graph` after `Package.resolved` is changed 


How do you think

**Comment by adam-fowler** [comment]
Are you saying `swift package resolve` is not updating `workspace-state.json`? What Xcode does is not really relevant here.

**Comment by aelam** [comment]
`swift package resolve` does update `workspace-state.json`
What I want to say is `show-dependency` normally should be an easier/better way  BUT the behavior of it is weird

After I think it over, I think you chose a wise way which is greater


Thanks for your great work!
