### ISSUE TITLE
terminal popups make developing docker packages almost impossible

### ISSUE THREAD

**Issue by kelvin13** [swift-server/vscode-swift#375]
**Describe the bug**

on pretty much every edit to a project with a `.build` directory managed by docker, the terminal popup explodes with 

```
Executing task in folder: ~/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-07-20-a/usr/bin/swift package resolve 

error: invalid access to .build/workspace-state.json
```

due to the docker container owning the `.build` directory. this popup is very annoying and shows up every few seconds. 

**To Reproduce**

steps to reproduce the behavior:

1. change the permissions of `.build` so that the process running VSCode cannot modify it 
2. edit a source file

**Expected behavior**

the extension should run `swift package resolve` more conservatively, or not run it if it detects that it does not have permissions to write to the `.build` directory.

**Environment**
 - OS: Ubuntu 20.04
 - Swift version 

```
Swift version 5.8-dev (LLVM 173344a30c43521, Swift d1220fd4f768151)
Target: x86_64-unknown-linux-gnu
```

 - Visual Studio Code version: 1.69.2
 - vscode-swift version: 0.6.0

**Comment by 0xTim** [comment]
I disagree with this - this is user error. It's the same behaviour if you're running a build and the VSCode process doesn't have access to the `.build` directory. Trying to be conservative and not show an error would produce a poor user experience. E.g. change Package.swift file to add a new dependency, resolve can't write to `.build` so doesn't do anything, now the package list is out of date and doesn't reflect the actual dependencies used by the package. 

The solution is to run the package using a Remote Dev Container so VSCode has access to the container. This gives you best of both worlds - running inside a Docker container so you can control the environment, Swift version etc and still get the full experience provided by the extension

**Comment by kelvin13** [comment]
it took an afternoon, and i really had to fiddle with the toolchain paths in the extension settings but i got the remote containers working so these popups aren’t an issue for me anymore; closing...

**Comment by adam-fowler** [comment]
@kelvin13 have you seen this https://github.com/swift-server/vscode-swift/blob/main/docs/remote-dev.md

**Comment by adam-fowler** [comment]
Ha given you submitted a PR for it, I guess you have

**Comment by kelvin13** [comment]
yeah that guide was really helpful! the only thing i couldn’t figure out was how to [enable port forwarding for port 80 and 443](https://forums.swift.org/t/why-isn-t-http-s-port-forwarding-working/59296)…
