### ISSUE TITLE
Improve README for release

### ISSUE THREAD

**Issue by 0xTim** [swift-server/vscode-swift#38]
We should expand the README to include screenshots, gifs, configuration information and anything needed for using the plugin. This will be used by VSCode and the extension page when we publish it

**Comment by svanimpe** [comment]
I planned on doing this when we finalise the features for a first release. Current todos are:

- Update the section on tasks. The CoreLLDB made some changes to how tasks work, and running executables is now handled with the debugger. The example on how to add command line arguments should also be updated to use the debugger.
- Mention our dependency on CoreLLDB and explain how to set up the LLDB Library to use.
- Mention that debugging doesn't work on Windows.
- Mention our inclusion of SourceKit-LSP and include its configuration settings.
- Mention our (limited) support for multi-root workspaces.
