### ISSUE TITLE
Build doesn't copy resources

### ISSUE THREAD

**Issue by SpectralDragon** [swift-server/vscode-swift#380]
**Describe the bug**
I working on project with few targets and each target contains specific resources. But when I compile SPM package from VS Code, then resources copied only from executable target. When I build it from Xcode, all resources copied correctly.

**To Reproduce**
1. Go to https://github.com/LiteCode/AdaEngine/tree/develop
2. Download project and open Package.swift with VSCode 
3. Build project in Debug mode and you will receive fatal error in MetalRenderBackend.swift::126 `Bundle.current.url(forResource: descriptor.shaderName, withExtension: "metallib")!`
4. If you will check bundle AdaEngine_AdaEngine.bundle, than you can see, that bundle contains only Vulkan folder, instead of Contents/Resources folder

**Expected behavior**
All resources copied correctly.

**Environment**
 - OS: macOS 12.4
 - Swift version: `swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
Target: x86_64-apple-macosx12.0`
 - Visual Studio Code version: 1.69.2
 - vscode-swift version: v0.6.0

**Additional context**
Readme file with instructions is not correct right now, Vulkan isn't needed.

**Comment by adam-fowler** [comment]
This is a Swift Package Manager issue. You should file a bug with https://github.com/apple/swift-package-manager. I assume you get the same results if you run `swift build` on the command line?

**Comment by SpectralDragon** [comment]
>  I assume you get the same results if you run `swift build` on the command line?

I'll check it

**Comment by SpectralDragon** [comment]
Yeah, you was right, the problem is swift package running on xcode and on SPM will shipping two different products. In first scenario where swift package builds on Xcode the bundles contains typical macos/ios NSBundle with `Contents` folders. In second scenario swift compiler builds a product with simple Bundle. And also, SPM wasn't process a metal libs =/

Thanks!
