### ISSUE TITLE
Test Explorer: Shortcut to open the source file

### ISSUE THREAD

**Issue by Zingam** [swift-server/vscode-swift#388]
Test Mate for C++ has the ability to open the source file of the test and even to display the location of the test.

I was looking a few weeks ago if this can be implemented for Swift, then I thought that it was coming but I'm not seeing it in 0.7.0. So I gave up looking into it.

If I recall correctly that should be possible. Is this planned and is somebody working on it already?

**Comment by adam-fowler** [comment]
see #192
