### ISSUE TITLE
Add Swift Snippets GUI support in VSCode

### ISSUE THREAD

**Issue by Kyle-Ye** [swift-server/vscode-swift#391]
**Describe the solution you'd like**

Add some GUI support(Maybe a green triangle button indicating we could run this file) to run Swift Snippest file like what we saw in other languages like Java and Python.

eg.

<img width="161" alt="image" src="https://user-images.githubusercontent.com/43724855/184809137-19c74753-3e1b-48f6-a40c-b265cba70169.png">

<img width="275" alt="image" src="https://user-images.githubusercontent.com/43724855/184809377-815a3a73-9471-4137-b2e3-4eaa60f6c2a8.png">

> See the Swift Snippest discussion: here https://forums.swift.org/t/swift-snippets/51947

EDIT: Adding proposal https://github.com/apple/swift-evolution/blob/main/proposals/0356-swift-snippets.md

**Comment by adam-fowler** [comment]
Hi @Kyle-Ye 

I saw the snippet support pitch. I can't remember offhand but does it provide support for building and running snippets via SwiftPM?

**Comment by Kyle-Ye** [comment]
Yes, we can run the snippets by 
```shell
export SWIFTPM_ENABLE_SNIPPETS=1 
swift package learn
```

You can try it by this PR https://github.com/apple/swift-markdown/pull/70

**Comment by adam-fowler** [comment]
I assume that will run all snippets, is there a command for running an individual snippet

**Comment by Kyle-Ye** [comment]
> I assume that will run all snippets, is there a command for running an individual snippet

This will not run all snippets, it will just show CLI output. And only if the user gives the input (like 1↵2↵) will it run the specific snippet. As for direct command support, maybe it currently does not support it. (I did not go through the implementation detail and maybe @bitjammer knows something about it)
But we can pitch this to SPM to let it support this or use some tricky way to replace the user's input as a temporary workaround.

**Comment by Kyle-Ye** [comment]
> use some tricky way to replace the user's input as a temporary workaround.

For example, when user clicks "run" for snippet 0 of group 0, we could run
```
echo "0\n0\nr" > /tmp/snipptest.input
export SWIFTPM_ENABLE_SNIPPETS=1
swift package learn < /tmp/snipptest.input
```

**Comment by adam-fowler** [comment]
If you can build the extension you could test out #397. This adds two new commands `runSnippet` and `debugSnippet` which are available if the current edited file is a Swift snippet.

**Comment by Kyle-Ye** [comment]
I just clone the repo with the commits of #397 and #403. And build the extension. (To avoit confusion, I also tried first uninstall the extension and build it to a vsix product and install from the vsix product)

But I did not see the `runSnippet` and the `debugSnippet` commands nor the "Swift" sub-menu of editor right click menu. (First I suspect it was the swift-package-version issue, so I just upgrade the package manifest to swift 5.7. But it did not work either.)

Maybe it is because I'm not very family with the advanced configuration of VS Code. Could you give some UI hints or text hints on how to test the above feature? Thanks

**Comment by adam-fowler** [comment]
All the changes are on `main`. If you aren't seeing the Swift submenu in the right click menu then you've somehow not installed the extension. 

The snippet commands are only available when you are editing a Snippet. Custom snippet folders are not supported. Bring up the command menu Cmd+Shift+p. Type swift in the filter bar and it should list all the commands available to you.

**Comment by adam-fowler** [comment]
You should build the extension with `npm run dev-package`. This creates a `swift-lang-development.vsix` which you can manually load into VSCode. 

The other alternative is after running `npm install`, open the vscode-swift project in VS Code and press F5 to run the extension.
