### ISSUE TITLE
Test Discovery Error (Swift 5.8)

### ISSUE THREAD

**Issue by compnerd** [swift-server/vscode-swift#394]
**Describe the bug**
It seems that test discovery is broken on main with the latest version of the plugin.  Building and running tests simply states:
```
Test Discovery Error
 warning: '--list-tests' option is deprecated; use 'swift test list' instead
Error: unknown option '--skip-build'
Usage: list <options>
  See 'list --help' for more information.
```

**To Reproduce**
- Install a recent build of Swift from main (see swift.org/download)
- Try build tests for SourceKit-LSP

**Expected behavior**
Tests to be identified and be able to be executed.

**Environment**
 - OS: Windows 10
 - Swift version: Swift version 5.8-dev (LLVM b69b0f8449614a5, Swift 6ef09e95444e4c4)
 - Visual Studio Code version: 1.70.2
 - vscode-swift version: 0.7.0

**Additional context**
Not sure how long you can download the exact version of the toolchain, but it is here: https://ci-external.swift.org/job/swift-PR-build-toolchain-windows/154/artifact/build/artifacts/installer.exe

**Comment by adam-fowler** [comment]
Has `--skip-build` been removed from SwiftPM? Is this in 5.7, or on the main branch?

**Comment by adam-fowler** [comment]
It appears you cannot skip the build when listing tests. See https://github.com/apple/swift-package-manager/issues/5739

**Comment by adam-fowler** [comment]
@compnerd this PR should fix the issue https://github.com/apple/swift-package-manager/pull/5770. Once it is merged can you test?

**Comment by compnerd** [comment]
Hmm, there are a few more changes to LSP that I would prefer not to lose, but hopefully should be able to get those up in a day or so.  Once they are up, we should be able to do a one-off build with the requisite patches and I should be able to test that.

**Comment by adam-fowler** [comment]
This is fixed with latest Swift trunk development build

**Comment by compnerd** [comment]
The test listing does work ... kinda.  It doesn't show up after a build directly, but if I did a "run all tests" it showed up, though didn't run the tests.  It doesn't seem to be as reliable about running the tests as before though.  Not sure what is going on just yet.

**Comment by adam-fowler** [comment]
If you have no tests listed when you do a "run all tests" it will not run any tests (as you have none listed). But at the same time this completes a build which would then populate the test list. 

I verified on linux that the test list is updated after a build has completed. I haven't had time to set up a new Windows VM to verify on Windows. The other one expired.
