### ISSUE TITLE
extension crashes when LSP does not have access to operator definitions file

### ISSUE THREAD

**Issue by kelvin13** [swift-server/vscode-swift#399]
**Describe the bug**

custom operators crash the extension if it has not also indexed the file containing the operator definitions.
this is often the case, because the extension cannot consistently locate sibling files if in a nested Packages/ editable package.

example: 

```swift 
enum MaskedVersion
{
    func ?= (pattern:MaskedVersion?, version:Self)
    {
        pattern ?= .init(version)
    }

    init?<S>(_ string:S) where S:StringProtocol
    {
    }
}
```

**To Reproduce**

open the attached project in vscode

**Expected behavior**

the extension should not crash

**Environment**

 - swift: DEVELOPMENT-SNAPSHOT-2022-08-18-a
 - Visual Studio Code version: 1.70.2
 - vscode-swift version: 0.7.0

there is a `.devcontainer` in the attached project

[sourcekit-lsp-crash.zip](https://github.com/swift-server/vscode-swift/files/9419230/sourcekit-lsp-crash.zip)

**Additional context**

**Comment by adam-fowler** [comment]
Your code crashed sourcekit-lsp. This is a sourcekit-lsp issue.
The sourcekit-lsp output pane includes the folllowing.
```
sourcekit-lsp: /home/build-user/swift/include/swift/AST/DiagnosticEngine.h:993: swift::InFlightDiagnostic swift::DiagnosticEngine::diagnose(swift::SourceLoc, const swift::Diagnostic &): Assertion `!ActiveDiagnostic && "Already have an active diagnostic"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	While evaluating request TypeCheckSourceFileRequest(source_file "/home/adamfowler/Downloads/sourcekit-lsp-crash/Sources/workspace/MaskedVersion.swift")
1.	While evaluating request TypeCheckFunctionBodyRequest(workspace.(file).MaskedVersion.?=@/home/adamfowler/Downloads/sourcekit-lsp-crash/Sources/workspace/MaskedVersion.swift:3:10)
2.	While type-checking statement at [/home/adamfowler/Downloads/sourcekit-lsp-crash/Sources/workspace/MaskedVersion.swift:4:5 - line:6:5] RangeText="{
        pattern ?= .init(version)
    "
3.	While type-checking expression at [/home/adamfowler/Downloads/sourcekit-lsp-crash/Sources/workspace/MaskedVersion.swift:5:9 - line:5:33] RangeText="pattern ?= .init(version"
4.	While type-checking-target starting at /home/adamfowler/Downloads/sourcekit-lsp-crash/Sources/workspace/MaskedVersion.swift:5:9
[Error - 07:40:37] The SourceKit Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by kelvin13** [comment]
can we transfer this issue to https://github.com/apple/sourcekit-lsp ?

**Comment by compnerd** [comment]
@kelvin13 I don't think that is possible, they are in different organizations.

**Comment by kelvin13** [comment]
closing, i manually re-filed the issue in apple/sourcekit-lsp
