### ISSUE TITLE
`swift package resolve` is run unnecessarily after update to `Package.resolved`

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#4]
At the moment there is a file watcher on `Package.resolved` which calls `swift package resolve` whenever `Package.resolved` is changed. This doesn't make sense as `swift package resolve` generates this file. I can see the package dependency view is updated whenever this task finishes, so is currently directly linked to the task being run.

I would have thought `swift package resolve` would be called whenever `Package.swift` is edited.
The package dependency view update should be decoupled from the resolve task and updated whenever `Package.resolved` file changes.

This means you get the UI updating correctly, without running unnecessary resolves.

Thoughts @svanimpe @0xTim

**Comment by adam-fowler** [comment]
#5

**Comment by 0xTim** [comment]
So the reason for adding this was to ensure that if you pulled down a package that another user had updated or you'd updated on another machine etc, then it would sync your dependencies. It should be called when the manifest itself is edited as well, but I can see an issue if a user triggers an update and we then rerun a resolve as a result of that so maybe we should try and be better and catching that use case

**Comment by 0xTim** [comment]
And I'm specifically thinking of a `git pull` here rather than a user running a `swift package update` outside of the extension/IDE

**Comment by adam-fowler** [comment]
So you want vscode to call `swift package resolve` after a `git pull`. What does Xcode do?

**Comment by 0xTim** [comment]
The same thing effectively. If you pull down a new commit with a changed resolved file it will run a package resolve so the dependencies shown in Xcode match the resolved file
