### ISSUE TITLE
Add Code Snippets for Swift

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#40]
Code snippets are templates that make it easier to enter repeating code patterns, such as loops or conditional-statements.

https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by adam-fowler** [comment]
Would need a list of what we wanted. Maybe check what other languages are doing

**Comment by svanimpe** [comment]
These are included in the built-in Swift extension: https://github.com/microsoft/vscode/tree/main/extensions/swift/snippets
