### ISSUE TITLE
Silent / Configurable Package Resolution

### ISSUE THREAD

**Issue by bdrelling** [swift-server/vscode-swift#405]
**Is your feature request related to a problem? Please describe.**
Upon opening up a Swift workspace in VS Code, the extensions starts to resolve when the project opens, just like Xcode. This automatic package resolution is great at times, but not always what I want as a VS Code user. 

For example, I might just be opening up a Vapor project to tweak `css` in VS Code. By not allowing this to be configurable (or at least silent), it can take seconds of fighting with the resolution pane to get it to go away so I can just edit my `css`. I would say that this is extremely common in the case of iOS/macOS/tvOS/watchOS development when I want to leave Xcode to use something lightweight like VS Code, like working with `fastlane` or editing a markdown file, etc.

If I do have an Xcode project open and I open VS Code alongside to edit some other file within the same directory, sometimes resolution also fails or runs into a conflict, something along the lines of `the swift process is already running` -- I'll update this issue when I notice the error again. When this happens, I have to completely close my workspace and re-open it.

It also (very infrequently) resolves randomly in the middle of my using the terminal. I don't understand this behavior, but when it does so, it hijacks the pane (taking precedence over the terminal I'm _actively_ typing in) and hijacks keyboard focus as well. This can happen multiple times throughout project development.

**Describe the solution you'd like**
Preferably both solutions:

1. **Configurable package resolution.** Let me determine how and when I want packages to resolve. Basic options of: `automatic` or `off`.
2. **Silent package resolution.** Do it in the background, preferably by default.

**Describe alternatives you've considered**
I just end up disabling and enabling the extension throughout my day, which is incredibly tedious. I often just leave it off because it's not worth the bloat 90% of the time I'm using VS Code.

**Additional context**
I understand that without package resolution, type completion won't work for dependencies, but allowing configuration will let me use VS Code as both a lightweight text/file editor within Swift repositories _and_ as an IDE for Swift projects. In the moments when I just need to crack open a file in a project, it's far too cumbersome.

**Comment by adam-fowler** [comment]
Hi,

The main issue you seem to have is fighting with the resolve task output terminal. I don't understand why you are having this issue as resolve tasks are run with the flag `vscode.TaskRevealKind.Silent`. This means they may open a new terminal or append to an existing one (which already ran a resolve) but this terminal will not get focus and will not be revealed to the user unless the user selects it. Is there a possibility you have some VSCode setting enabled that is producing this effect? You can find all the global settings you have changed here `~/Library/Application\ Support/Code/User/settings.json`.

A resolve is run when the project is opened and whenever `Package.swift` or `Package.resolved` is updated. The random resolves you are seeing are possibly due to another process touching `Package.resolved`, perhaps a copy of Xcode. I have an improvement not in a release yet which only runs a resolve if the `Package.resolved` has actually changed. This should reduce the number of unnecessary resolves.

I am not overly keen to add an option because resolves shouldn't get in the way of you using VSCode anyway. Resolving a fully resolved project is a cheap process. The process should happen in the background and should not be taking focus away from whatever window you are working in (we need to work out why this is happening for you). And with the change I mention in the previous paragraph, unnecessary resolves should not run.

Can you give me details about your environment. VSCode version, Swift extension version, OS, the output of `swift --version` and your settings file. I'll see if I can work out what is going on.

**Comment by bdrelling** [comment]
Hey Adam, thank you for the reply.

Just to be clear, you're saying the default behavior is that I shouldn't be seeing the terminal window opening for package resolution? If that's the case, I'm a-ok with not adding configurability -- the only reason I proposed that is because I figured this was the default behavior some folks preferred.

Sometimes I have Xcode open at the same time, that's not uncommon at all like I mentioned for Apple platform app projects, like opening VS Code to the side to mess with `fastlane` or a `README.md` or so on because it's a better editor for those tasks than Xcode.

As for environment information, here's everything I can think to provide based on your list.

**Environment Information**

**Operating System**: macOS 12.4.0
**Architecture**: arm64
**Xcode**: 13.4.1 (13F100)
**Swift Version**: Swift 5.6.1 (5.6.0.323.66)
```
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0
```
**VS Code**: 1.71.0
```
Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:25.516Z (5 days ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.5.0
Sandboxed: No
```
**Swift Extension Version**: 0.8.0

And here is my `settings.json` output:
```json
{
    "sync.gist": "******",
    "sync.lastUpload": "2017-02-08T19:37:20.665Z",
    "sync.autoDownload": true,
    "sync.autoUpload": true,
    "sync.lastDownload": "",
    "sync.version": 262,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.workspaceSync": false,
    "sync.anonymousGist": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "git.enableSmartCommit": true,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "git.autofetch": true,
    "terminal.integrated.fontFamily": "\"Meslo LG M DZ for Powerline\"",
    "git.confirmSync": false,
    "gitProjectManager.baseProjectsFolders": [
        "~/projects"
    ],
    "swiftlint.enable": true,
    "editor.minimap.showSlider": "always",
    "extensions.ignoreRecommendations": true,
    "editor.formatOnSave": true,
    "sync.quietSync": true,
    "sync.forceUpload": true,
    "vsicons.dontShowNewVersionMessage": true,
    "dotnet-test-explorer.autoExpandTree": true,
    "swiftlint.path": "/opt/homebrew/bin/swiftlint",
    "gitlens.gitCommands.skipConfirmations": [
        "fetch:command",
        "stash-push:command",
        "switch:command",
        "branch-create:command"
    ],
    "workbench.editorAssociations": {},
    "spellright.notificationClass": "hint",
    "spellright.statusBarIndicator": false,
    "spellright.suggestionsInHints": false,
    "spellright.ignoreFiles": [
        "**/.gitattributes",
        "**/.gitignore",
        "**/.spellignore",
        "**/.rubocop.yml",
        "**/.swiftformat",
        "**/.swiftlint.yml",
        "**/Dangerfile-*",
        "**/Gemfile",
        "**/Gemfile.lock",
        "**/Mintfile",
        "**/Podfile",
        "**/Podfile.lock",
        "**/Zincfile",
    ],
    "redhat.telemetry.enabled": true,
    "yaml.format.singleQuote": true,
    "security.workspace.trust.untrustedFiles": "open",
    "terminal.external.osxExec": "iTerm.app",
    "terminal.integrated.defaultProfile.osx": "zsh",
    "javascript.format.semicolons": "remove",
    "typescript.format.semicolons": "remove",
    "typescript.preferences.quoteStyle": "single",
    "[javascript]": {
        "editor.tabSize": 2,
        "editor.defaultFormatter": "dbaeumer.vscode-eslint"
    },
    "[json]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "[ruby]": {
        "editor.tabSize": 2
    },
    "[shell]": {
        "editor.tabSize": 2
    },
    "[typescript]": {
        "editor.tabSize": 2,
        "editor.defaultFormatter": "dbaeumer.vscode-eslint"
    },
    "shellformat.effectLanguages": [
        "shellscript",
        "dotenv",
        "hosts",
        "jvmoptions",
        "ignore",
        "spring-boot-properties",
        "azcli",
        "bats"
    ],
    "typescript.updateImportsOnFileMove.enabled": "always",
    "ruby.rubocop.useBundler": true,
    "ruby.useBundler": true,
    "lldb.library": "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/LLDB",
    "cSpell.userWords": [],
    "cSpell.ignoreWords": [],
    "eslint.format.enable": true,
    "workbench.colorTheme": "Visual Studio Dark",
    "git.ignoreMissingGitWarning": true,
    "swift.autoGenerateLaunchConfigurations": false,
    "editor.inlayHints.enabled": "off",
}
```

**Comment by adam-fowler** [comment]
Only thing I can see there that might cause issues is the fact you are using iTerm as your terminal. Could you disable that temporarily to see if that resolves the issue.

**Comment by adam-fowler** [comment]
I was sure I posted a response here. Anyway I'll post it again. 

The resolve task is run with options `presentationOptions: { reveal: vscode.TaskRevealKind.Silent }`. The documentation for this is 
```
/**
 * Only brings the terminal to front if a problem is detected executing the task
 * (e.g. the task couldn't be started because).
 */
Silent = 2,
```
Is there a chance the terminal is only brought to the front when there is an error?
