### ISSUE TITLE
'Swift' context submenu erroneously shown in every editor, regardless of file's language

### ISSUE THREAD

**Issue by frypf** [swift-server/vscode-swift#411]
**Describe the bug**
The `Swift` submenu containing the single item `Run Swift Script`, seems to have been added to the context menu in _every_ file in any language - even in workspaces that don't contain any swift files at all.

**To Reproduce**
1. Open a workspace
2. Right click in any open editor
 
**Expected behavior**
At the very least this should only appear within actual swift files. Preferably though, please provide an option to disable this superfluous context submenu outright.

**Environment**
 - OS: macOS Monterey 12.5.1
 - Swift version: 5.6.1
 - Visual Studio Code version: 1.71.0
 - vscode-swift version: 0.8.0

**Additional context**
Please don't clutter up the context menu, especially when we already have easy access to those same commands through the command palette.

**Comment by adam-fowler** [comment]
Yeah saw that just after the release. It'll be fixed in 0.8.1 which should be released either today or tomorrow
Fixed here #409

**Comment by frypf** [comment]
Awesome, thanks 👍
