### ISSUE TITLE
issue when trying to run swift script.

### ISSUE THREAD

**Issue by Nytem** [swift-server/vscode-swift#416]
so I followed the getting started page for the windows installation (https://swift.org/getting-started/) but every time I try to run a swift script I get this popup.

![image](https://user-images.githubusercontent.com/81455405/189900297-24b4839f-138d-4a60-8759-7a2184de7ee4.png)

any ideas what could be going on?

**Comment by stevapple** [comment]
This is a known restriction of the legacy Swift driver. With the release of Swift 5.7, Swift has officially adopted the new driver on Windows, so this error should not appear any more with Swift 5.7+.

Give the new Swift 5.7 a shot and see if things become different?

**Comment by Nytem** [comment]
wait nope it's showing as 5.6.3??? mb

**Comment by Nytem** [comment]
ok it ran but now I got this
![image](https://user-images.githubusercontent.com/81455405/189906731-e60eb61d-2e4b-4436-9cc5-45b67f99d973.png)

**Comment by adam-fowler** [comment]
@compnerd any ideas, what is happening here

**Comment by compnerd** [comment]
That indicates that the environment is not correct (i.e. `SDKROOT` is unset).  Most likely the shell/terminal emulator was not restarted after the update.

**Comment by Nytem** [comment]
let me try restarting everything then quickly

**Comment by Nytem** [comment]
@compnerd restarted everything and still getting the same issue

**Comment by compnerd** [comment]
Run `set SDKROOT` and ensure that the path exists and is correct.  I assume that you did do an uninstall + install for the upgrade?

**Comment by Nytem** [comment]
yeah I uninstalled swift 5.6.3 and then installed 5.7

**Comment by Nytem** [comment]
where do I enter that set SDKROOT, sorry I'm a little bit incompetent here lol, just my class for school requires swift and I own no apple devices so I'm just trying to get this working lol

**Comment by compnerd** [comment]
You should be able to run that from a cmd prompt.

**Comment by Nytem** [comment]
yeah ok a path does exist

SDKROOT=C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk

**Comment by compnerd** [comment]
I wonder if the problem is that the plugin is erasing the `SDKROOT` environment variable?  @stevapple or @adam-fowler would know that better.

**Comment by Nytem** [comment]
wonder if the standard library is even there perhaps? would you know what the name of the folder I should be looking for is?

**Comment by stevapple** [comment]
@Nytem Did you see the error when manually running `swift <script.swift>` from a developer command prompt?

The plugin doesn't modify the environment without configuration (except for testing). I see this as something wrong with SDK/toolchain layout.

**Comment by Nytem** [comment]
these all look correct?
![image](https://user-images.githubusercontent.com/81455405/189938143-de0c4bee-692f-40de-9da9-297151bfd1b8.png)
![image](https://user-images.githubusercontent.com/81455405/189938200-bc7e00b6-4449-4aa3-b1ce-130a2807f873.png)
![image](https://user-images.githubusercontent.com/81455405/189938323-655437ad-536e-498f-b16a-6aae6b21bbd9.png)

**Comment by Nytem** [comment]
@stevapple like this?
![image](https://user-images.githubusercontent.com/81455405/189940170-30618bcf-fa0e-4d8d-9b92-e1f51df22365.png)

**Comment by Nytem** [comment]
sorry for the blackouts, folders named somewhat personal info lol

**Comment by Nytem** [comment]
oh oops, will do

**Comment by compnerd** [comment]
Hmm, running with `-v` might be useful to see what the driver is doing.  In general, the interpreter is not supported on Windows, compiling and executing is.

**Comment by Nytem** [comment]
![image](https://user-images.githubusercontent.com/81455405/189943041-9bba33c6-a975-4e57-8f6e-37ee7ddb4236.png)

**Comment by Nytem** [comment]
so when following the getting started page, it said I needed python, if I type in python --version it doesn't detect anything... could that be the issue?

**Comment by stevapple** [comment]
@Nytem I reproduced the problem locally and this is a driver bug instead of the plugin’s. Could you please open a new issue in apple/swift-driver, so we can move on there? This issue can be closed then.

**Comment by Nytem** [comment]
https://github.com/apple/swift-driver/issues/1182
