### ISSUE TITLE
How to disable variable type hint?

### ISSUE THREAD

**Issue by garymaxallen** [swift-server/vscode-swift#422]
The extension automatically displays type hint of variables, I don't want this. I already know it. It makes me crazy.
<img width="616" alt="image" src="https://user-images.githubusercontent.com/10022333/192489840-3de02b74-3802-4476-9d49-32a8f6aaa78e.png">

**Comment by garymaxallen** [comment]
sorry, the problem is related to vscode itself.
it's this stupid setting. god
"editor.inlayHints.enabled": "off"

**Comment by adam-fowler** [comment]
Search for inlay hints in settings. There is an option to hide, show, hide or show when alt+ctrl is pressed.

**Comment by sodle** [comment]
Additionally, some of the inlay hints are incorrect.

![image](https://github.com/swift-server/vscode-swift/assets/4439158/6f8a6a06-93cc-4670-8e4a-9bc5664053e1)

In this example, the suggested change would be a syntax error, as closure parameters cannot accept type hints.

**Comment by adam-fowler** [comment]
@sodle These aren't suggested changes to your code they are hints to tell you what an inferred type is.
And secondly closure parameters do accept types. You could rewrite your code above as
```swift
inputString.enumerateLines(invoking: { (line: String, stop: inout Bool) in
...
```

**Comment by tinder-tannerbennett** [comment]
@adam-fowler Can we modify our use of hints to disable the ability to insert them, then?

https://github.com/microsoft/vscode/blob/e3f0f4a875e5a24cdfd3d0c457835670e39569ee/src/vscode-dts/vscode.d.ts#L5117-L5127

Even better, the hint can probably modify the surrounding code to _make_ it valid when it is triggered, using this same property.
