### ISSUE TITLE
sourcekit-lsp not working on *.mm files in Webkit source in VSCode 

### ISSUE THREAD

**Issue by blacktop** [swift-server/vscode-swift#426]
I see in the README this should work on ObjC code and I "assume" ObjC++ ? However, goto definition etc is not working for me. I am using the Swift extension mentioned here https://github.com/apple/sourcekit-lsp/tree/main/Editors

Is it that it's not finding clangd? I also have the VSCode cpp plugin installed so not sure if they are "fighting" though I believe the Cpp plugin ignores all ObjC files *(the reason I need sourcekit-lsp 😉)

Thanks!

**Comment by blacktop** [comment]
I don't see clangd mentioned in the projects src anywhere, is this extension only meant to support Swift?

Is there a way to leverage sourcekit-lsp's OjbC powers?

**Comment by adam-fowler** [comment]
Is this for objective c/cpp code in a SwiftPM package? It should work. At least we pass the file types to the language client so these files are passed onto sourcekit-lsp. I've seen c code work. 

There is no mention of clangd in the vscode-swift extension because sourcekit-lsp manages the running of the clangd executable.

**Comment by blacktop** [comment]
I was trying to get it to work with the Webkit src https://github.com/WebKit/WebKit

I assume it wasn't working because there is no package.swift in the root?  What is the minimal contents I would need to add to that file to get the lsp to pickup all the code?

**Comment by adam-fowler** [comment]
That'll be your issue. The extension only works with SwiftPM projects, or single swift files. I know people have created dummy Package.swift files for their xcworkspace files. You could try to setup a target for each folder in the Source folder. Each target would have to be given a custom path name as SwiftPM assumes source files appear under a folder called Sources not Source. There is more info about the package manager here https://www.swift.org/package-manager/

**Comment by blacktop** [comment]
thank you
