### ISSUE TITLE
Setting for passing extra arguments to swift test

### ISSUE THREAD

**Issue by Peter-Schorn** [swift-server/vscode-swift#431]
There doesn't appear to be any way to run tests in parallel in the Test Explorer View. Adding a setting that allows you to pass extra arguments to `swift test` invocations, such as `--parallel`, would solve this.

**Comment by adam-fowler** [comment]
The VSCode extension requires the output of `swift test` to update the TestExplorer. The output from `swift test --parallel` is different from when run without `--parallel` so I would have to support parsing this output as well as the standard output. On top of that it is not very helpful. It tells you when tests start, but never tells you when they are successful, only when they fail. 

If this was to be added I would add an option to enable parallel running of tests, not the more general extra arguments for `swift test`. The output of swift test and the Test Explorer are too tightly coupled to allow adding random extra arguments into the equation.

**Comment by Peter-Schorn** [comment]
I understand. Thanks for taking the time to respond.
