### ISSUE TITLE
Outline view shows local variables as type members

### ISSUE THREAD

**Issue by svanimpe** [swift-server/vscode-swift#434]
In the screenshot below, `frequency`, `format`, `channels`, and `result` are local variables in the computed property `audioDeviceSettings`.

Similarly, `count`, `decoders`, and `index` are local variables in the `chunkDecoders` computed property.

<img width="499" alt="Screenshot 2022-10-15 at 17 51 57" src="https://user-images.githubusercontent.com/1496250/195995876-53cbbb12-6b89-43ed-9469-46a3bbe64efe.png">

This is using version 0.8.2 with Swift 5.7 on macOS

**Comment by adam-fowler** [comment]
Can you include the code that generates this. I won’t be able to look at this for the next week as I’m on holiday. It is most likely some confusion between the vscode language client and sourcekit-lsp. It is probably worthwhile adding a bug to the source kit-lisp repo.

**Comment by svanimpe** [comment]
Here's a minimal test case:

```swift
struct OutlineIssue {
    var x: Int {
        let y = 0
        return y
    }
}
```

![image](https://user-images.githubusercontent.com/1496250/196137745-7153c7d8-a166-4390-bc82-8abec2099886.png)

It also occurs on Linux.

**Comment by adam-fowler** [comment]
Fixed on main branch of SourceKit-LSP, fix will be available with Swift 6.
