### ISSUE TITLE
<unknown>:0: error: could not build C module 'SwiftShims'

### ISSUE THREAD

**Issue by ondexedDB** [swift-server/vscode-swift#436]
**Describe the bug**
Im using it for first time, and its giving me error. I installied swift and everything, and im on windows.
How do I fix this please?
**To Reproduce**
Run swift Script

<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "AssertionReporting.h"
         ^
C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\shims/AssertionReporting.h:16:10: note: in file included from C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\shims/AssertionReporting.h:16:
#include "SwiftStdint.h"
         ^
C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\shims/SwiftStdint.h:28:10: error: 'stdint.h' file not found
#include <stdint.h>
         ^
<unknown>:0: error: could not build C module 'SwiftShims'

**Comment by adam-fowler** [comment]
Sounds like you haven't installed swift correctly. Did you install the correct Windows SDK before installing Swift?

Here are the swift install instructions https://www.swift.org/getting-started/#installing-swift

**Comment by adam-fowler** [comment]
Wait a sec I see you are trying to run a Swift script. I don't think they are working on Windows at the moment. Have you tried compiling a SwiftPM package instead?

**Comment by adam-fowler** [comment]
Closing as I had no response
