### ISSUE TITLE
Relax tests discovery to include tests not bound to a symbol / not following the "class.method" pattern

### ISSUE THREAD

**Issue by natinusala** [swift-server/vscode-swift#449]
**Is your feature request related to a problem? Please describe.**

Unless I fall into some sort of unsupported case, AFAICT tests can have any naming convention, and are not constrained to the regular "class.method" pattern.

For example on Linux, tests discovery is done "manually" by giving the list of all tests classes to `XCTMain`. Each class has a `allTests ` property listing all the test cases (methods). The end result is that you can name your tests anything (as long as there are no commas since they are reserved for `swift test --filter` list separator).

Tests can also be dynamically generated. The BDD library [Quick](https://github.com/Quick/Quick) makes uses of this, and makes your test names a full english sentence. I don't know how it behaves on macOS / Xcode.

I use Quick in my project and the test discovery panel of vscode shows 0 tests, presumably because 1) they do not show up as symbols in LSP and 2) they don't match the regular "class.method" pattern.

However when I run `swift test --list-tests` I have the list of all the tests : 

```
[...]
Quick.QuickSpec/a view tree with overridden propagating discarding attributes; when the view tree is created; then the implementation tree is created
Quick.QuickSpec/a view tree with overridden propagating discarding attributes; when the default color changes; then the implementation is untouched
Quick.QuickSpec/a view tree with overridden propagating discarding attributes; when the default color changes; then attributes are not set on the implementation side
Quick.QuickSpec/a view tree with overridden propagating discarding attributes; when the overridden color changes; then the implementation is updated
Quick.QuickSpec/a view tree with overridden propagating discarding attributes; when nothing changes; then the implementation is untouched
Quick.QuickSpec/a view tree with overridden propagating discarding attributes; when nothing changes; then attributes are not set on the implementation side
Quick.QuickSpec/a view with appending attributes; when the same attribute is applied multiple times; then all attributes are applied
Quick.QuickSpec/ScarletCore tests; when finished; tears down
```

And when I run `swift test --filter "Quick.QuickSpec/ScarletCore tests; when finished; tears down"` it properly runs that one test.

**Describe the solution you'd like**
Discover the tests using `swift test --list-tests` but don't remove them from the list if they don't show up in the LSP symbols and/or don't follow the "class.method" pattern.

**Describe alternatives you've considered**
I run my tests manually using `swift test --filter xxxx` for now

**Additional context**
Here is a sample project with funky test names for testing: https://github.com/natinusala/xctest-comma

**Comment by adam-fowler** [comment]
When I run this on macOS it works fine. It uses the xctest test discovery which doesn't use the `XCTMain` so the test names are the function names.

The linux `XCTMain` is no longer needed since test discovery was enabled in swift 5.4, but obviously some libraries are still making use of it. #451 should resolve this

**Comment by natinusala** [comment]
How does refreshing work? It doesn't seem to pickup new test cases when I update the test files, they only show up if I run all tests specifically through the vscode test panel, and even then they appear as grey, not green / passing

**Comment by adam-fowler** [comment]
So refreshing works through a combination of post build triggers and LSP document updates.

After every build is completed a `swift test --list-tests` is run to catch test changes. 

Alongside this whenever the editor runs an LSP document symbols request we catch the results and use that to catch new test methods. This is done by parsing for new methods prefixed by "test" that have no arguments. This obviously won't work for custom named methods. I haven't looked into how this interacts with custom named methods. This might be problematic. It might add duplicates of method tests. I'll have to review. Also the custom named methods most likely won't have location info. Another thing to check.

**Comment by natinusala** [comment]
I confirm that my tests don't have location info since I don't see a Run button in the gutter next to the test cases in the editor. But that's to be expected and I honestly don't see a solution to that seeing how tests are "dynamically" generated.

**Comment by adam-fowler** [comment]
#451 is merged. I should be able to get a release out with this before Xmas
