### ISSUE TITLE
Fix running tests on Windows

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#473]
Currently when running tests on Window. If you run them instead of debugging them they fail to load with an error message similar to 
```
<unknown>:0: error: PCH was compiled with module cache path 'C:\Users\User\Developer\libs\swift-collections\.build\x86_64-unknown-windows-msvc\debug\ModuleCache\2TGCAFOH5KUFD', but the path is currently 'c:\Users\User\Developer\libs\swift-collections\.build\x86_64-unknown-windows-msvc\debug\ModuleCache\2TGCAFOH5KUFD'
<unknown>:0: error: missing required module 'SwiftShims'
```
Debugging them works though. This may be due to tests being run via `swift test` instead of running the xctest exe directly

**Comment by compnerd** [comment]
@adam-fowler could you please add a bit more context here?  I'd be curious to learn what the issue is and what could've been done to prevent it.

**Comment by adam-fowler** [comment]
I believe it is something I broke, adding more info above

**Comment by adam-fowler** [comment]
Ok I can fix this by ensuring `swift test` doesn't build the tests by adding the `--skip-build` command line parameter. @compnerd any idea why `swift test` on its own would produce these errors. If I type it into the terminal it works fine.

**Comment by adam-fowler** [comment]
I couldn't work out what was the difference between the two paths in the error message. I've now worked it out, one begins with `c:\\` the other begins with `C:\\`.

**Comment by compnerd** [comment]
Interesting; I wonder why the case is different between the two.

**Comment by adam-fowler** [comment]
Replacing this issue with #478 and closing this
