### ISSUE TITLE
Support Swift Playground packages `.swiftpm`

### ISSUE THREAD

**Issue by wmorgue** [swift-server/vscode-swift#481]
Unable to work with programs (packages) created in [Swift Playground](https://www.apple.com/swift/playgrounds/).
I shared my app to macOS and after opening it I get an error.

1. Just create a empty App (SwiftUI) in Swift Playground (not Xcode): `SomeApp.swiftpm`
2. Share with macOS
3. Open `SomeApp.swiftpm` via `vs code`: 
```bash
$ code SomeApp.swiftpm
```
4. See error in vs code:

```text
error: 'someapp.swiftpm': Invalid manifest

SomeApp.swiftpm/Package.swift:8:8: error: no such module 'AppleProductTypes'
import AppleProductTypes
```

**Expected behavior**
I expected it to just work 🤷🏼

**Environment**
 - OS: Intel macOS 13.1 build 22C65
 - Swift version:
 
 ```bash
 swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: x86_64-apple-macosx13.0
 ```
 - Visual Studio Code version:
 
 ```bash
 1.74.3
97dec172d3256f8ca4bfb2143f3f76b503ca0534
x64
 ```
 - vscode-swift version: `1.0.0`

**Additional context**

I understand that the problem is `import AppleProductTypes`, but I don't know how hard it is to fix.
Content of `SomeApp.swiftpm/Package.swift`:

```swift
// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Some App",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Some App",
            targets: ["App"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "App",
            path: "App"
        )
    ]
)
```

**Comment by adam-fowler** [comment]
As I understand it AppleProductTypes is internal to the Xcode version of SwiftPM and is unavailable to the cli version which VSCode uses. At the moment there isn't really a way around this.

**Comment by adam-fowler** [comment]
Going to close this as not possible
