### ISSUE TITLE
The extension sometimes doesn't load when opening a Swift project

### ISSUE THREAD

**Issue by natinusala** [swift-server/vscode-swift#498]
**Describe the bug**
Sometimes when I open a Swift project, the extension doesn't load at all. Disabling and enabling it back does nothing, neither does reloading the window. Using the "Reinstall extension" command then reloading works though.

**To Reproduce**
Sadly I have no consistent way of reproducing it, it's seemingly random - however I would be happy to provide any debug information in case it happens again.

**Expected behavior**
When I open a Swift project in vscode I expect Swift integration to start immediately without me reinstalling the extension.

**Environment**
 - OS: I've had it happen on regular Ubuntu 20 and WSL Ubuntu 22
 - Swift version (output of `swift --version`) 5.9-dev (LLVM 726983520b3cae8, Swift 89fec217fb790c7)
 - Visual Studio Code version: 1.75.1
 - vscode-swift version: 1.1.0

**Comment by adam-fowler** [comment]
Can you replicate this with swift 5.7?

**Comment by natinusala** [comment]
I switched to Swift 5.7, I'll let you know if it happens again

**Comment by natinusala** [comment]
It happened to me again on Swift 5.7.3 on WSL. It seems to happen when I have more than one vscode window opened, on two different projects.

**Comment by adam-fowler** [comment]
When it doesn't start can you go the extensions view, select the swift extension and then select `runtime status`. Generally when it has failed to load it is because an error was thrown while initialising. The `runtime status` window should report this error.

**Comment by adam-fowler** [comment]
Closing issue as there hasn't been a response in over 3 months

**Comment by natinusala** [comment]
I'm sorry I meant to answer but I forgot :see_no_evil:

I was able to narrow down the problem, it only happens when I have multiple vscode windows open on multiple Swift projects (one window per project). 

On the first window to open it works but on the subsequent ones it says `Cannot register 'sourcekit-lsp.serverPath'. This property is already registered.`

**Comment by adam-fowler** [comment]
Do you have more than one swift extension installed?

**Comment by natinusala** [comment]
Doesn't look like it, no.

**Comment by adam-fowler** [comment]
Somehow VS Code is registering the configuration setting `sourcekit-lsp.serverPath` multiple times. The most obvious way for this to happen is that two extensions both have this configuration setting. Given multiple swift extensions were based off an example that was hosted in the sourcekit-lsp repo, I could see multiple extensions using the same name. I kept the same naming as the example code for the sourcekit-lsp config settings. With hindsight that was a bad idea, I should have renamed them.
