### ISSUE TITLE
[LSP Crashed] if function call arguments are not passed in at once

### ISSUE THREAD

**Issue by skyleaworlder** [swift-server/vscode-swift#499]
**Describe the bug**
I try to call a function like `Task.sleep`. If I don't figure out its argument name `nanoseconds` as quickly as possible, LSP will crash after it tries 6 times.

**To Reproduce**
1. Go to Editor
2. Use the following snippet but please DO NOT just pass in any arguments:

```swift
Task.sleep()
```

3. See error

**Expected behavior**
LSP not crashed.

**Environment**
 - OS: Windows 11, but connect to Ubuntu 22.04 using SSH. (Swift extension is installed on Windows 11.)
 - Swift version: 5.7-RELEASE
 - Visual Studio Code version: 1.75.1
 - vscode-swift version: v1.1.0

**Additional context**
None.

**Comment by JumpMasterJJ** [comment]
+1

**Comment by adam-fowler** [comment]
Are you using swift v5.7.3? I think this was fixed for Linux at least in 5.7.3. Otherwise at least a very similar issue was fixed on the 5.8 branch

**Comment by adam-fowler** [comment]
This is fixed in the 5.8 branch of sourcekit-lsp and latest 5.7 on linux, so I'm going to close this. Anyway it isn't a bug in vscode-swift. See https://github.com/apple/sourcekit-lsp/issues/635
