### ISSUE TITLE
Error: couldn't create connection to LSP server

### ISSUE THREAD

**Issue by MartinLau7** [swift-server/vscode-swift#500]
**Describe the bug**
When I open the SPM project through VScode, a message indicating that the LSP cannot be connected is displayed.
Log: 
[Error - 下午8:50:46] SourceKit Language Server client: couldn't create connection to server.
Launching server using command /usr/bin/sourcekit-lsp failed. Error: spawn /usr/bin/sourcekit-lsp ENOENT
<img width="474" alt="image" src="https://user-images.githubusercontent.com/5416852/222961698-b6605db0-342a-4f1a-a2b7-31016c690e9c.png">

**Expected behavior**

**Environment**
 - OS:  Ubuntu 20.04
 

 - Swift version: swift-5.7.3-RELEASE

 - Visual Studio Code version: 1.76.0
 - vscode-swift version: v1.1.0

**Additional context**

**Comment by adam-fowler** [comment]
This appears to be related to how you installed Swift. Can you give us some info about how you installed swift and the folder structure of your swift installation. Eg where is your sourcekit-lsp executable in relation to your swift exe.

**Comment by MartinLau7** [comment]
> This appears to be related to how you installed Swift. Can you give us some info about how you installed swift and the folder structure of your swift installation. Eg where is your sourcekit-lsp executable in relation to your swift exe.

sourcekit-lsp is from swift 5.7.3 release, this only seems to occur when Remote SSH is done on M1, everything is fine on Intel

**Comment by MartinLau7** [comment]
Everything worked fine after I reinstalled VSCode-Universal (old version: Apple Silicon)
