### ISSUE TITLE
Strange error message for package resolve on Windows

### ISSUE THREAD

**Issue by stefanspringer1** [swift-server/vscode-swift#502]
**SEE UPDATE BELOW: build error currebtly also appears inside the command line, so no VS Code problem**

**Describe the bug**

**To Reproduce**
1. Open a Swift package in VS Code, e.g. https://github.com/stefanspringer1/SwiftXMLParser
2. See error

**Expected behavior**
No errors.

**Environment**
 - OS: Windows 11
 - Swift version 5.7.3 (swift-5.7.3-RELEASE)
 - Visual Studio Code version: 1.76.0
 - vscode-swift version: 1.1.0

**Additional context**
No paths set inside the extension settings, swift package build is fine in the command line

Errors (Output):

```
 *  Executing task: C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swift.exe package resolve 

error: 'swiftxmlparser': Invalid manifest
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "dispatch.h"
         ^
C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\include\dispatch/dispatch.h:66:10: note: in file included from C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\include\dispatch/dispatch.h:66:
#include <dispatch/time.h>
         ^
C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\include\dispatch/time.h:67:9: error: missing '#include <stdint.h>'; 'uint64_t' must be declared before it is used
typedef uint64_t dispatch_time_t;
        ^
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\stdint.h:25:28: note: declaration here is not visible
typedef unsigned long long uint64_t;
                           ^
<unknown>:0: error: could not build C module 'CDispatch'

 *  The terminal process "C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swift.exe 'package', 'resolve'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by stefanspringer1** [comment]
build error currently also appears inside the command line, so no VS Code problem

**Comment by stefanspringer1** [comment]
build error currently also appears inside the command line, so no VS Code problem

**Comment by compnerd** [comment]
@stefanspringer1 I think that this is a missing repair after a VS update.  This should be alleviated hopefully in the 5.9 time frame with inflight improvements.

**Comment by stefanspringer1** [comment]
Yes, I did a repair via the installer. Could have thought of it… catched me by surprise. I already saw your patch. Thanks! Swift is constantly loosing some of its “rough edges” on Windows 😊
