### ISSUE TITLE
`Restart LSP Server` doesn't work on Windows

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#508]
**Describe the bug**
Running the command `Restart LSP Server` kills the current LSP server but doesn't start a new one.

It appears the `stop` command times out even though the executable has been killed and then an error is reported to log, but no new server is started.

**Comment by tristanlabelle** [comment]
@adam-fowler seems like this was fixed by #521 ? Do you close the bug now or when publishing a new version of the extension?

**Comment by adam-fowler** [comment]
Yeah I guess you can close this
