### ISSUE TITLE
Code snippet in documentation showing line numbers

### ISSUE THREAD

**Issue by soumyamahunt** [swift-server/vscode-swift#518]
**Describe the bug**
The code snippet in docc documentation previews showing line numbers.

<img width="807" alt="Screenshot 2023-04-09 at 10 03 19 PM" src="https://user-images.githubusercontent.com/51203900/230823693-26013f52-654c-4c1a-8bbd-37601fffb909.png">

**To Reproduce**
1. Create a swift package.
2. Add code snippets in any documentation.
3. Hover over the documented symbol to preview documentation.
4. See the bug.

**Expected behavior**
Code snippets should not show line numbers as in Xcode.

<img width="717" alt="Screenshot 2023-04-10 at 9 36 47 AM" src="https://user-images.githubusercontent.com/51203900/230823802-21bd607c-a5ab-42d3-a0f9-e83880fbf5d1.png">

**Environment**
 - OS: macOS 13.3.1
 - Swift version:

> swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0

 - Visual Studio Code version: 1.77.1
 - vscode-swift version: 1.2.0

**Comment by adam-fowler** [comment]
This is coming from SourceKit-LSP. You should add an issue there https://github.com/apple/sourcekit-lsp/issues.

I'm not sure it's a bug issue. VSCode doing something different from Xcode is not a bug.
