### ISSUE TITLE
stale sourcekit-lsp problems in problem list

### ISSUE THREAD

**Issue by stevenbrix** [swift-server/vscode-swift#519]
**Describe the bug**

When working with code (especially porting Mac code to Windows) i find that the language server can get in a state where `sourcekit` problems are still reported n the Problem List well after I've already fixed them.

**To Reproduce**

I don't have a smoking gun repro steps, it generally happens after i've been working in a project for a while and all of a sudden i notice that errors aren't going away. 

**Expected behavior**
I would expect errors that I have fixed to go away, especially on a rebuild

**Environment**
 - OS: Windows 11
 - Swift version (output of `swift --version`): 5.9-dev
 - Visual Studio Code version: 1.77.1
 - vscode-swift version: 1.2.0

**Additional context**
I took a dump of the process when it was in this state if that would be useful?

Restarting the language server works, but it would be useful to have a "clear problems" button like there exists in macOS.

**Comment by adam-fowler** [comment]
This is an issue with SourceKit-LSP. It might be worthwhile adding an issue to that repository. If you can provide a solid repo case that'll help a lot as well.

**Comment by stevenbrix** [comment]
i don't have a simple repro yet, it generally happens in a large project, and after i've been working for a while i'll notice things not updating

**Comment by tristanlabelle** [comment]
@stevenbrix , I think this was fixed by my [implementing pull diagnostics](https://github.com/apple/sourcekit-lsp/pull/746). Do you reckon we can close this?

**Comment by adam-fowler** [comment]
@stevenbrix Are you able to verify this with the latest Windows 5.9 build of swift?

**Comment by adam-fowler** [comment]
Closing as no response, also it has been flagged as fixed in SourceKit-LSP

**Comment by tristanlabelle** [comment]
There are still cases where I have to close a file and reopen it for SourceKit-LSP to clear up some stale diagnostics, but the situation is much better than before. I'll file another bug if I get a repro.
