### ISSUE TITLE
[Bug] Running `swift package archive` causes race condition of package resolution

### ISSUE THREAD

**Issue by darylteo** [swift-server/vscode-swift#522]
**Describe the bug**

Related Bugs

https://github.com/swift-server/vscode-swift/issues/373

This is a tough one to describe...

I'm working with `swift-aws-runtime-lambda`, and part of this exercise uses a LambdaPackager plugin to compile Swift files in a docker amazonlinux container so that it can run on AWS hardware.

The difference in the OS environment is where the issue lies I suspect - the docker container re-resolves it's own dependencies for amazonlinux but writes to the same .build folder, which touches package.resolved. This then causes this VSCode Extension to auto resolve the new packages, and then rewrite the repos in checkouts... which then leads to the archive operation failing. 

I know autoResolve this is the "expected behaviour" so I thought I'd flag this with the team to see if anything can be done to improve this.

I've added a minimal repro to demonstrate. The issue gets worse with larger repos as this increases the chance of race collisions.

Here's a demo (some parts sped up for brevity)

https://imgur.com/ODYHnwS

**To Reproduce**

 - Clone https://github.com/darylteo/bug-vscode-swift-lambda
 - Enable auto resolve
 - `swift build` works
 - `swift package archive` does not 
 - disable auto resolve
 - `swift package archive` now works

**Expected behavior**

Ideally, running vscode should not interfere with `swift package archive`

**Environment**
 - OS: [e.g. Ubuntu 20.04]  Mac M1 Max Pro OS 12.6
 - Swift version (output of `swift --version`)  1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
 - Visual Studio Code version: 1.77.3
 - vscode-swift version: 1.2.1

**Additional context**

**Comment by adam-fowler** [comment]
Hi, do you have different dependencies based on platform?
A resolve should only occur if the hash of Package.resolved is different from before. I'll verify this is still the case

**Comment by adam-fowler** [comment]
The only way I could see this happening is if your swift packages are not up to date. SourceKit-LSP has a bug where it keeps overwriting the Package.resolved https://github.com/apple/sourcekit-lsp/issues/707.

I imagine what is happening is when the archive command is run there is a package update, then SourceKit-LSP reverts them and the changing back and forwards is causing resolves to run which change the contents of the downloaded packages.

Can you try running the `archive` command with the setting `SourceKit-LSP: Disable` set to on and see if it works.

**Comment by 0xTim** [comment]
You could also pass `--build-path ./.build/linux` to your plugin build command to stop it overwriting the host build directory

**Comment by darylteo** [comment]
> Hi, do you have different dependencies based on platform?
> A resolve should only occur if the hash of Package.resolved is different from before. I'll verify this is still the case

@adam-fowler that's what I suspect. I'm coding on a OS X machine, but in order to deploy to AWS Lambda, the Swift Lambda Plugin compiles it in a AmazonLinux Docker Container. Let me check if that resolves 🙏

**Comment by adam-fowler** [comment]
Can you also try with SourceKit-LSP disabled.

**Comment by darylteo** [comment]
No joy with SourceKit-LSP disabled and `build-path` set. 

![Screen Shot 2023-04-14 at 10 21 43 pm](https://user-images.githubusercontent.com/1226920/232042041-df820596-2c73-4fa8-8a11-208e4f0feecd.jpg)

The only other observation I can give is that the auto resolve seems to kick in after loading in `swift-crypto`

Here's the full trace

https://gist.github.com/darylteo/8f9ffda1a3acd3eaf237ee3d76318bcc

**Comment by adam-fowler** [comment]
I know what it is. It is kinda my fault, the problem package is Soto. If you are building SotoCore on Linux it includes `swift-crypto`. If you are building it on macOS it doesn't. `swift-crypto` has minimum platform requirements so I don't include it on macOS. I use CommonCrypto on macOS instead. So your `Package.resolved` will be different on both platforms. It is probably best you use a separate build folder for the archive if you can.

**Comment by darylteo** [comment]
Oh! That's a lucky random combination of factors. :D 

> you use a separate build folder for the archive if you can.

--scratch-path / --build-path didn't do it for me... I guess you're saying to copy the folder or is there some other swiftpm thing I could do? :D i'm not too experienced with the swift tooling 😅

to be fair, it'll be less of an issue once I move this up to CI/CD, but I expect there may be others in the future who run into this.

**Comment by adam-fowler** [comment]
I have added support for disabling the auto-resolve while running swift command plugins via the `Swift: Run Command Plugin` command. You need to edit the command plugin task and set the `disableTaskQueue` flag. See #524

**Comment by adam-fowler** [comment]
With release 1.3 this should be resolved
