### ISSUE TITLE
vscode-swift extension does not recognize bridging header

### ISSUE THREAD

**Issue by garymaxallen** [swift-server/vscode-swift#527]
I know vscode-swift is not supposed to do iOS development, but I am just one step away.

I use vscode and vscode-swift extension to do iOS development according to this guide, https://medium.com/swlh/ios-development-on-vscode-27be37293fe1.

All goes very well, until I have to use a swift bridging header file.

These are my code project structure

sourcekit-lsp setting:

![image](https://user-images.githubusercontent.com/10022333/233644708-d7e35535-4fd2-4423-ac80-b086c79b937c.png)

bridging header file:

![image](https://user-images.githubusercontent.com/10022333/233644879-1cf9b9cf-ed61-4c31-9099-e2b6bcbe57cf.png)

the imported C header file:

![image](https://user-images.githubusercontent.com/10022333/233644998-b0290adf-f1cd-4cf8-b070-ef7ea86adacf.png)

swift extension does not recognize the extractnews() function from the C header file:

![image](https://user-images.githubusercontent.com/10022333/233645130-13e6eef7-95be-4b76-8fa7-137cb2ea8cae.png)

But you can see every other thing is recognized, like UIKit, WebKit

![image](https://user-images.githubusercontent.com/10022333/233645318-26cec021-f4e9-4807-9767-0fb6885a32aa.png)

**Comment by adam-fowler** [comment]
I don't think Swift Package Mansger recognises bridging headers is the issue here. Without SwiftPM I don't get Sourcekit-LSP support and I can't then provide this in the extension.

**Comment by ljhm** [comment]
We can figure out what Xcode does when it creates and uses Bridging Header files, if there is a way to output the compiling and linking command in Xcode. We can build Makefiles based on that then. Objective-C Bridging Header is great, it works on macOS and iOS. Both C and C++ features are available there.

**Comment by adam-fowler** [comment]
Is it bridging headers you want or is it to include Objective-C? Because if it is the latter then you could use the following https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#creating-c-language-targets

**Comment by adam-fowler** [comment]
Closing as this hasn't had a response for 2 months
