### ISSUE TITLE
-Xlinker -L, and rpath for dynamic library

### ISSUE THREAD

**Issue by ljhm** [swift-server/vscode-swift#529]
**Describe the bug**
 *  Executing task: swift build --product hello 

Building for debugging...
ld: warning: Could not find or use auto-linked library 'foo'
Undefined symbols for architecture x86_64:
  "_intcpy", referenced from:
      _$s5helloAAV4mainyyFZ in hello.swift.o
  "_strncpy2", referenced from:
      _$s5helloAAV4mainyyFZ in hello.swift.o
ld: symbol(s) not found for architecture x86_64
[0/1] Linking hello

 *  The terminal process "swift 'build', '--product', 'hello'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

**To Reproduce**

Hi, I have a module under Sources which is a dynamic library 
(.dylib or .so) in C language.

How can I set the -Xlinker -L, and rpath or (DY)LD_LIBRARY_PATH to
debug in both swift and C code in vscode like Xcode?

Thanks
```
$ tree --charset C hello/
hello/
|-- Package.swift
|-- README.md
`-- Sources
    |-- cfoo_dir
    |   |-- Makefile
    |   |-- foo
    |   |-- foo.c
    |   |-- foo.d
    |   |-- foo.h
    |   |-- foo.o
    |   |-- libfoo.dylib
    |   `-- module.modulemap
    `-- hello
        |-- hello.swift
        `-- hello2.swift

$ 
```
$ otool -D hello/Sources/cfoo_dir/libfoo.dylib 
hello/Sources/cfoo_dir/libfoo.dylib:
@rpath/libfoo.dylib
$ 

$ DYLD_LIBRARY_PATH=Sources/cfoo_dir/ swift run -Xlinker -LSources/cfoo_dir/
Building for debugging...
Build complete! (0.22s)
hello
hello2
foo
$ 

**Expected behavior**
Debugging works in both swift, and C code in dynamic library like Xcode.

**Environment**
 - OS: macOS 12.6.5 (21G531)
 - Swift version (swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: x86_64-apple-macosx12.0)
 - Visual Studio Code version: Version: 1.77.3 (Universal)
 - vscode-swift version: v1.2.1

**Additional context**

**Comment by adam-fowler** [comment]
You might be able to use a combination of the settings `Build Arguments` and `Runtime Path` to get this working. I haven't really looked into getting dynamic libraries working, so don't know if you would need anymore.

**Comment by ljhm** [comment]
Thanks, 

I got something like this that works.

```
// tasks.json:

{
    "version": "2.0.0",
    "tasks": [
      {
        "label": "build",
        "type": "shell",
        "options": {
          "cwd": "${workspaceFolder}",
        },
        // "command": "/usr/bin/make",
        "command": "swift build -Xswiftc -DDEBUG -Xswiftc -LSources/cfoo_dir/ -Xlinker -rpath -Xlinker Sources/cfoo_dir/",
      }
    ]
  }

```

**Comment by adam-fowler** [comment]
You could also add all of those build arguments to the build settings for that workspace. But what you posted works fine.

**Comment by ljhm** [comment]
> You could also add all of those build arguments to the build settings for that workspace. But what you posted works fine.

Hi, Adam,

Do you mean that I can put the flags in package.swift?

I just test on both tasks.json and package.swift, and encounter a problem.

If i turn off `-Xswiftc` flag in tasks.json, and put `-Xswiftc` flag in `swiftSettings section ` in package.swift, there is an error: unknown argument: '-Xswiftc'.

But flags in `linkerSettings` section is fine in package.swift.

Thanks!

```
// tasks.json:

  "command": "/usr/bin/swift",
  "args": [
    "build",
    "-c", "debug", // , "debug", //"release",
    "-Xswiftc", "-g", // "-g" , "-O"
    // "-Xlinker", "-L", "-Xlinker", "Sources/cfoo_dir/",
    // "-Xlinker", "-rpath", "-Xlinker", "Sources/cfoo_dir/",
  ]
```

---

```
// package.swift:

  .executableTarget(
    name: "hello",
    dependencies: ["cfoo_dir", "foo", "hello3_dir"],

    // Swift version 5.7.2, macOS 12.6.5 (21G531)
    // error: unknown argument: '-Xswiftc', 
    // swiftSettings: [
    //   .unsafeFlags(["-Xswiftc", "-g"]), // -g -O
    // ],

    linkerSettings: [
      .unsafeFlags(["-Xlinker", "-rpath", "-Xlinker", "Sources/cfoo_dir"]),
      .unsafeFlags(["-Xlinker", "-L", "-Xlinker", "Sources/cfoo_dir"]),
    ]
  )
```

**Comment by adam-fowler** [comment]
No I don't mean edit the Package.swift. I mean in VSCode press Cmd+, to bring up the settings and edit the swift extension settings from there. You can edit settings globally (what they call user) and for your current workspace.
<img width="275" alt="Screenshot 2023-05-01 at 10 14 42" src="https://user-images.githubusercontent.com/9382567/235433654-bb6b7ce0-374d-4a49-aa93-eade8bb1e439.png">

**Comment by ljhm** [comment]
Thanks adam,

I put the settings in workspace .vscode for it may change from project to project.
