### ISSUE TITLE
VS Code reports errors with tasks

### ISSUE THREAD

**Issue by svanimpe** [swift-server/vscode-swift#53]
Whenever I go to **Terminal > Run Tasks...** VS Code shows errors in the Tasks output channel:

```
Error: the task identifier '{"type":"swift","command":"run Run","description":"Run Target Run","group":"build","problemMatcher":[],"label":"swift: Run Target Run","detail":"swift run Run"}' is missing the required property 'args'. The task identifier will be ignored.
Error: the task configuration '{"type":"swift","command":"run Run","description":"Run Target Run","group":"build","problemMatcher":[],"label":"swift: Run Target Run","detail":"swift run Run"}' is using an unknown type. The task configuration will be ignored.
```

The weird thing is we don't even provide tasks like this anymore.

This is just a Vapor project generated with the CLI. It doesn't have a **tasks.json** file. I've also checked the output of our TaskProvider and that is fine. The output only displays when I open the tasks panel. No errors are shown when our provider is ran initially, to provide a resolve task.

Can anyone reproduce this?

**Comment by adam-fowler** [comment]
I have seen tasks hang around. Not sure why though, no errors though. Early on in development did your tasks have an `args` field

**Comment by svanimpe** [comment]
No they didn't. The tasks I'm seeing are from before you started working on integrating CodeLLDB. I finally managed to fix this issue by deleting `~/Library/Application Support/Code` (just keeping my settings.json file).
