### ISSUE TITLE
custom swift build commands for test explorer

### ISSUE THREAD

**Issue by stevenbrix** [swift-server/vscode-swift#536]
**Is your feature request related to a problem? Please describe.**
We are trying to test shared libraries (between Mac and Windows) on Windows in VSCode. We have a VSCode workspace open with our app code, as well as the folders where our shared code lives. There is currently no way to prevent the re-build of a shared library to update packages in the IDE.

**Describe the solution you'd like**
I would like to be able to specify `--skip-update` to the build command for tests so that my packages stay pinned. I tried putting a build command in `.vscode/tasks.json` and hoped it would be picked up but it wasn't

**Describe alternatives you've considered**
If we could simply build the tests from the main build of our app like xcode does that would be great, but i'm not sure if that's possible.

**Additional context**

**Comment by adam-fowler** [comment]
You can use the build arguments in the settings to add the `--no-update` build argument.

**Comment by stevenbrix** [comment]
@adam-fowler thanks for the response, let me check!

**Comment by stevenbrix** [comment]
hey @adam-fowler, this looks like it meets our needs, thanks!
