### ISSUE TITLE
Jump from reported errors / test failures to the corresponding line in source

### ISSUE THREAD

**Issue by dabrahams** [swift-server/vscode-swift#544]
When tests fail for me in VSCode, I can't click the message to edit the offending line of source code, and there's no obvious keyboard shortcut for that.  Personally, I'd like it to jump to the first problem automatically and to have a keystroke for stepping through the rest of the issues.

**Comment by adam-fowler** [comment]
Option+F8 - next test failure
Option+Shift+F8 - prev test failure

If you want to find command key bindings. The command panel (Cmd+Shift+p) is very useful
