### ISSUE TITLE
One key builld-and-test

### ISSUE THREAD

**Issue by dabrahams** [swift-server/vscode-swift#545]
Nothing seems to be set up to build and test the project all in one go.  That's the basic unit of my edit / test / debug cycle.  It should be a prominent button with a keybinding.

**Comment by dabrahams** [comment]
Ah, I see the button now! 
<img width="473" alt="image" src="https://github.com/swift-server/vscode-swift/assets/44065/c76d8a1d-c3ed-462d-a990-4281563a4094">
But I can't find a way to bind a key to it.

**Comment by adam-fowler** [comment]
The command is called `Test: Run All Tests`. VSCode's default keybinding for it is `Cmd+;` followed by `Cmd+a`. You can change it by bringing up the command list, find the command and selecting the cog on the right hand side.

**Comment by dabrahams** [comment]
Thanks so much for your patience, and sorry for the I-don't-know-how-to-use-vscode feature requests!
