### ISSUE TITLE
Build can overlap with automatic resolve packages resulting in corrupted dependencies checkouts

### ISSUE THREAD

**Issue by tristanlabelle** [swift-server/vscode-swift#547]
**Describe the bug**
When opening a fresh project and quickly building, it is easy to get in a state where the SPM checkouts of git dependencies get corrupted, so the project will not build.

**To Reproduce**
1. Open a freshly cloned Swift project with external dependencies in VS Code, for example, https://github.com/pointfreeco/swift-composable-architecture.git
2. While the Swift extension triggers an automatic resolve packages in the background, immediately run `ctrl+shift-B` to build
3. With high probability, notice errors such as:

```
   fatal: not a git repository (or any of the parent directories): .git

error: input file 'C:\Code\swift-composable-architecture\.build\checkouts\swift-argument-parser\Plugins\GenerateManual\GenerateManualPluginError.swift' was modified during the build

error: 'swift-benchmark': Failed to clone repository https://github.com/google/swift-benchmark:
    Cloning into 'C:\Code\swift-composable-architecture\.build\checkouts\swift-benchmark'...
    error: could not write config file C:/Code/swift-composable-architecture/.build/checkouts/swift-benchmark/.git/config: No such file or directory
    fatal: could not set 'core.logallrefupdates' to 'true'
```

**Expected behavior**
The build should not be allowed to start until resolve packages completes.

**Environment**
 - OS: Windows 11
 - Swift version: Trunk build
 ```
compnerd.org Swift version 5.9-dev (LLVM 2750202702814a2, Swift cd78e8b8aa452a9)
Target: x86_64-unknown-windows-msvc
 ```
 - Visual Studio Code version: 1.78.2
 - vscode-swift version: Version: 1.2.1

Previously reported as https://github.com/apple/sourcekit-lsp/issues/740

**Comment by adam-fowler** [comment]
Are you in a position to test the main branch of vscode-swift? If so could you try and repro your issue. I have disabled build tasks by not listing them when a resolve, update or other process is running on the package

**Comment by tristanlabelle** [comment]
We've had a few red Windows builds but I'll try this as soon as I get a chance next week.

**Comment by tristanlabelle** [comment]
That doesn't seem to work for me? @adam-fowler 

![image](https://github.com/swift-server/vscode-swift/assets/2314287/60d48f6e-f8a0-474a-baab-39aa5798a407)

**Comment by adam-fowler** [comment]
Did you build the extension yourself? I haven't released this yet

**Comment by tristanlabelle** [comment]
Ooops my bad. I just installed an updated toolchain and forgot that the release vehicle is different for `vscode-swift`.

**Comment by adam-fowler** [comment]
Version 1.4 was just released with a fix for this
