### ISSUE TITLE
Remove reference to `RPath`

### ISSUE THREAD

**Issue by compnerd** [swift-server/vscode-swift#555]
**Describe the bug**
`Swift: Runtime Path` describes itself with "Only effective when they can't be discovered by RPath."  However, `RPath` (which should be `rpath`) is not a portable term.  Windows has no such construct and the DLL search path is complex.  It looks at the current executable directory (`$ORIGIN` or `@ORIGIN` in ELF/MachO parlance) and the DllSearch path which is generally used with sandboxing.

**To Reproduce**
1. Go to 'Settings'
2. Scroll down to 'Swift: Runtime Path'

**Expected behavior**
Use terminology which applies equally well to all platforms or platform specific terminology.

**Environment**
 - OS: Windows
 - Swift version: compnerd.org Swift version 5.9-dev (LLVM 4d1942b06350403, Swift 49e928406444aa1)
 - Visual Studio Code version: 1.79.2
 - vscode-swift version: 1.3.0

**Comment by adam-fowler** [comment]
What are your suggestions here then? Dynamic Library search path?

**Comment by compnerd** [comment]
Yeah, or even library search paths as a term.  An alternative way to write it would be "search for libraries in these locations".
