### ISSUE TITLE
Remove reference to `$PATH`

### ISSUE THREAD

**Issue by compnerd** [swift-server/vscode-swift#556]
**Describe the bug**
`Swift: Path` describes the default to "search in `$PATH`".  This does not make sense on Windows, where in cmd it would be `%Path%`, or `$env:Path` or `${env:Path}` with PowerShell.  We should use generic terms to describe this rather than platform specific terminology.

**To Reproduce**
1. Go to 'Settings'
2. Scroll down to 'Swift: Path'
3. See error

**Expected behavior**
Use of generic or platform specific descriptions

**Environment**
 - OS: Windows
 - Swift version: compnerd.org Swift version 5.9-dev (LLVM 4d1942b06350403, Swift 49e928406444aa1)
 - Visual Studio Code version: 1.79.2
 - vscode-swift version: v1.3.0

**Additional context**

**Comment by adam-fowler** [comment]
What about "The path of the folder containing the Swift executables. The default is to look in the PATH environment variable.

**Comment by compnerd** [comment]
@adam-fowler I personally prefer directory over folder due to my Linux background but that’s exactly what I had in mind.  The statement as quoted is now using platform agnostic terms.

**Comment by MalxWare47** [comment]
idiot it wouldn't matter what platform youre on you would still need to look at PATH
