### ISSUE TITLE
SourceKit Language Server emits errors, autocomplete doesn't work

### ISSUE THREAD

**Issue by p-lenart** [swift-server/vscode-swift#561]
**Describe the bug**
After fetching all dependencies, autocompletion doesn't work. Here are logs from the Output:

**SourceKit Lanaguage Server:**
```
D:\SwiftDemo\Package.swift:4:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
D:\SwiftDemo\Package.swift:4:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
```

**Swift**
```
12:31:47: SourceKit-LSP setup
12:31:47: compnerd.org Swift version 5.9-dev (LLVM 4a3b38183d7bb09, Swift 44a40979e52be8e)
12:31:48: SwiftDemo: add: d:\SwiftDemo
12:31:48: SwiftDemo: Resolving Dependencies ... done.
12:31:50: SwiftDemo: focus: d:\SwiftDemo
12:31:51: SwiftDemo: Test Discovery Failed: error: The operation could not be completed. The file doesn’t exist.
```

**To Reproduce**
1. mkdir SwiftDemo
2. cd SwiftDemo
3. swift package init --name SwiftDemo
4. Open project in VSCode
5. Add some code to test autocompletion
4. Autocomplete functionality doesn't work

**Expected behavior**
Autocomplete support works as expected

**Environment**
 - OS: Windows 11
 - Swift version Swift version 5.9-dev (LLVM 4a3b38183d7bb09, Swift 44a40979e52be8e) (downloaded from [here](https://download.swift.org/development/windows10/swift-DEVELOPMENT-SNAPSHOT-2023-06-05-a/swift-DEVELOPMENT-SNAPSHOT-2023-06-05-a-windows10.exe) )
 - Visual Studio Code version: 1.79.2 695af097c7bd098fbf017ce3ac85e09bbc5dda06 x64
 - vscode-swift version: v1.3.0

**Additional context**
n/a

**Comment by adam-fowler** [comment]
Autocompletion via Sourcekit-lsp only works after you have built the project

**Comment by p-lenart** [comment]
> Autocompletion via Sourcekit-lsp only works after you have built the project

Does it matter if I run it from a "Run Build Task" or manually from the console? 

I still have problems with autocomplete not working for a larger, private project, but I'm not sure how I can provide more information to track down an issue.

**Comment by adam-fowler** [comment]
You can run build either inside VSCode or via the command line. The index is built when you compile using either of these methods. 

I've found sometimes sourcekit-lsp still fails (never been able to narrow down the reasons for this). Running the restart LSP server command after this normally fixes the issue.

**Comment by adam-fowler** [comment]
Closing as related SourceKit-LSP has been resolved
