### ISSUE TITLE
No Intellisense or Autocomplete

### ISSUE THREAD

**Issue by Juke-Duke** [swift-server/vscode-swift#566]
**Describe the bug**
No intellisense/errors showing in vscode, everything builds and runs correctly otherwise. When using other packages, I cant see any of its types or methods.

**To Reproduce**
I have xcode 15 beta 2 and the extension downloaded.

**Expected behavior**
Intellisense or error feedback from vscode.

**Environment**
 - OS: MacOS Ventura 13.4.1
 - Swift version (output of `swift --version`)
 ```
swift-driver version: 1.82.2 Apple Swift version 5.9 (swiftlang-5.9.0.114.10 clang-1500.0.29.1)
Target: arm64-apple-macosx13.0
```
 - Visual Studio Code version: 1.79.2
 - vscode-swift version: 1.3.0

**Additional context**
<img width="719" alt="image" src="https://github.com/swift-server/vscode-swift/assets/73366375/a62691c0-97df-4e53-aff4-b4ea5d560a91">
No error in ide

<img width="715" alt="image" src="https://github.com/swift-server/vscode-swift/assets/73366375/90ef30ee-353b-4683-933d-1b04abc1fad2">

Should see methods like `YAMLEncoder`, `YAMLDecoder`, etc.

**Comment by adam-fowler** [comment]
I get the same issue with 5.9 on macOS. Have you tried 5.8?

**Comment by Juke-Duke** [comment]
How do I switch my toolchain to my 5.8 on vscode?

**Comment by adam-fowler** [comment]
Try using the `Select Xcode toolchain` command.

**Comment by Juke-Duke** [comment]
Ok yeah it worked. You have to download the latest version of XCode, not the toolchain. Then in vscode, `Cmd+Shift+P` and select `Swift: Select Xcode Developer Dir` and make sure its pointing to latest, not any betas.

Thank you @adam-fowler for the assistance 🙂
