### ISSUE TITLE
Automatic build on file save experimental flag issues

### ISSUE THREAD

**Issue by MahdiBM** [swift-server/vscode-swift#571]
**Describe the bug**
The "automatic build on file save" experimental flag can be improved further, at least for my personal experience:
- [ ] It automatically switches the in-vscode terminal tabs when it starts building again. IMO it shouldn't.
  * To reproduce, just open a new tab, make changes to swift files, and observe that the terminal tab switches to the one re-building the package.
- [ ] It doesn't automatically build the package on opening project.

Optionally both of these could be their own configuration options.

**Environment**
- OS: 
```
Linux 2142cc59059b 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```
- Swift version (output of `swift --version`):
```bash
Swift version 5.8.1 (swift-5.8.1-RELEASE)
Target: aarch64-unknown-linux-gnu
```
- Visual Studio Code version:
```
Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:58.115Z (1 wk ago)
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 23.0.0
```
- vscode-swift version: v1.4.0

**Comment by adam-fowler** [comment]
The terminal tan changing I've tried to fix already without much luck. I'll have another look. 

Build on startup shouldn't be too hard.

**Comment by MahdiBM** [comment]
Thanks! I might take a look at them too, just made the issue so i don't forget about problems i see in the extension :)
I was going to do another issue too, but already forgot about that ...

**Comment by adam-fowler** [comment]
> I was going to do another issue too, but already forgot about that ...

That sounds familiar

**Comment by adam-fowler** [comment]
#576 will add a build at startup
I cannot replicate your issue where the build terminal get pushed to the front

**Comment by MahdiBM** [comment]
> I cannot replicate your issue where the build terminal get pushed to the front

You can close this issue in that case. 
I'm confident I have seen such behavior, but not sure if/when I'll be able to provide enough info so you can properly debug the problem.
I'll make a new issue when I have more info, if it doesn't auto-resolve itself.

**Comment by MahdiBM** [comment]
Also, how can I install a version of the extension with the changes available?
Is there some kind of a nightly version that uses the main branch?
If not, is that possible to do without too much problems? Perhaps in GHA?

**Comment by adam-fowler** [comment]
Checkout the CONTRIBUTING.md docs. Tells you how to install node.js and then how to run the extension from within VS Code

**Comment by adam-fowler** [comment]
Build on start up is in release v1.5
