### ISSUE TITLE
custom swift test commands

### ISSUE THREAD

**Issue by stevenbrix** [swift-server/vscode-swift#573]
We have a custom build system to make up for features that SPM lacks in our project. We therefore can not build using the VSCode extension, but we'd like to make use of the test explorer

**Describe the solution you'd like**
a `swift.testArguments` where we are able to pass `--skip-build` and any other arguments we want

**Describe alternatives you've considered**
I've tried making use of `swift.buildArguments` to pass my custom arguments and while the build almost succeeds, the linker fails with errors like this:

```<unknown>:0: error: failed file status check: could not access path 'C:\dev\browser\arc\Apps\BrowserWin\.build\x86_64-unknown-windows-msvc\debug\index\store\v5\units/x86_64-unknown-windows-msvc.swiftinterface-394W2REEQTNHS': permission denied
<unknown>:0: error: failed file status check: could not access path 'C:\dev\browser\arc\Apps\BrowserWin\.build\x86_64-unknown-windows-msvc\debug\index\store\v5\units/x86_64-unknown-windows-msvc.swiftinterface-394W2REEQTNHS': permission denied
<unknown>:0: error: failed file status check: could not access path 'C:\dev\browser\arc\Apps\BrowserWin\.build\x86_64-unknown-windows-msvc\debug\index\store\v5\units/x86_64-unknown-windows-msvc.swiftinterface-394W2REEQTNHS': permission denied
<unknown>:0: error: failed file status check: could not access path 'C:\dev\browser\arc\Apps\BrowserWin\.build\x86_64-unknown-windows-msvc\debug\index\store\v5\units/x86_64-unknown-windows-msvc.swiftinterface-394W2REEQTNHS': permission denied
<unknown>:0: error: failed file status check: could not access path 'C:\dev\browser\arc\Apps\BrowserWin\.build\x86_64-unknown-windows-msvc\debug\index\store\v5\units/x86_64-unknown-windows-msvc.swiftinterface-394W2REEQTNHS': permission denied
error: fatalError


 *  The terminal process "C:\Program Files\Swift\Toolchains\0.0.0+Asserts\usr\bin\swift.exe 'build', '--build-tests', '-Xlinker', '-debug:dwarf', '-Xcc', '-IC:\dev\browser\arc\Apps\BrowserWin\.packages\Microsoft.WindowsAppSDK.1.4.230518007-experimental1\include', '-Xlinker', '-LC:\dev\browser\arc\Apps\BrowserWin\.packages\Microsoft.WindowsAppSDK.1.4.230518007-experimental1\lib\win10-x64\'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

Building for debugging...
<unknown>:0: error: failed file status check: could not access path 'C:\dev\browser\arc\Apps\BrowserWin\.build\x86_64-unknown-windows-msvc\debug\index\store\v5\units/x86_64-unknown-windows-msvc.swiftinterface-394W2REEQTNHS': permission denied
error: fatalError
```
I'm also not confident that incremental builds will work, so i'd much rather just instruct `swift test` to use my pre-built stuff

**Comment by adam-fowler** [comment]
Are you asking for build arguments for test that are different from the ones used for build? Or just to be able to skip the build. I can see why that could be useful in your case. 

Out of interest have you setup a custom VSCode task to initiate your build process?

**Comment by stevenbrix** [comment]
@adam-fowler yeah we have a custom VSCode build task for our build process. We use CMake to run things like Nuget downloads and other windows tools that SPM doesn't support/understand yet

another possible solution would be to have the Test explorer run the default build task that's defined in VSCode.

**Comment by adam-fowler** [comment]
> another possible solution would be to have the Test explorer run the default build task that's defined in VSCode. this seems more correct than just running a random build

That doesn't work when you have multiple packages in one workspace. Also it isn't a random build it is a build that coincides with the build tasks setup by the extension. If you edit that task it will run the edited task task before building tests. Unfortunately if you change that task to a different type eg shell, the extension can't find it and will use the default implementation.

**Comment by adam-fowler** [comment]
Actually looking at the code, I can probably get it to find different task types. It would be doing the search based on the task name

**Comment by adam-fowler** [comment]
See #575

**Comment by adam-fowler** [comment]
Default build command from tasks.json will be used, if it exists
