### ISSUE TITLE
Xcode shows weird left-overs after using local version of package in VSCode

### ISSUE THREAD

**Issue by MahdiBM** [swift-server/vscode-swift#574]
**Describe the bug**
Xcode shows weird left-overs after using local version of package in VSCode.
Luckily you can just remove those left-overs, but still suboptimal that they happen.

**To Reproduce**
- Open a Swift project.
- After the extension loads the package list, select to "use local version" of a package.
- Once more right-click on the package name and select "add to workspace".
  - Might need devcontainers, not sure.
- Observe an extra directory in Xcode file navigator, which is _basically_ empty.

<img width="181" alt="Screenshot 2023-07-27 at 9 38 38 PM" src="https://github.com/swift-server/vscode-swift/assets/54685446/fa12f767-b280-4f57-9503-e312fe43e6f0">

**Expected behavior**
No extra directory.

**Environment**
Ubuntu Jammy with Swift 5.8.
Or recent Xcode 15 betas on macOS Sonoma, which use Swift 5.9 beta.
 - Visual Studio Code version: 1.4.0
 - vscode-swift version: 
```
Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:58.115Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 23.0.0
```

**Additional Context**
Not sure if the bug happens on macOS too. I've been using the extension on dev containers due to extension not working properly thanks to some of the Xcode 15 betas.

**Comment by adam-fowler** [comment]
That is SwiftPM not cleaning up after itself. Locally edited packages are stored in the `Packages` folder either as symbolic link to the actual package folder or as a copy of the package. When you call `package unedit` sometimes it doesn't manage to clear everything away. 

This is a SwiftPM so closing here.
