### ISSUE TITLE
Allow Dependency Files to be searched

### ISSUE THREAD

**Issue by 0xTim** [swift-server/vscode-swift#578]
VSCode's "Search Files by Name" menu doesn't show the files for your dependencies. I'm not sure if this is a configuration option, SourceKit issue or not possible but this is one feature from Xcode I miss.

For example, in a project with Soto, if I invoke the menu and type `AWSClient` I don't get anything. However, if the file has been open recently, by say clicking through to a dependency, then it _does_ appear. It would be great if we could search files in the dependency tree as well!

**Comment by 0xTim** [comment]
Note the same happens for symbols in the workspace which arguably would be even more helpful

**Comment by adam-fowler** [comment]
You can use the following settings to control what you see in file search
- Search: Use Ignore Files (defaults to on, which is why you aren't seeing anything in .build folder)
- Search: Exclude (you'll want to add to this if you disable the above). I added `*.build/debug/**`, `*.build/release/**`, `*.build/*/debug/**` and `*.build/*/release/**`

**Comment by adam-fowler** [comment]
@0xTim Does the above give you what you want?

**Comment by 0xTim** [comment]
@adam-fowler yep thanks! The search ordering is a bit off but definitely workable! Any idea about symbols only showing the current file? If not I'll create another issue

**Comment by adam-fowler** [comment]
Symbols only showing the current file, will most likely require work from SourceKit-LSP. I have already added an issue there to provide support. I don't think the LSP spec provides a standard request, so it might have to be a custom request. See https://github.com/apple/sourcekit-lsp/issues/802
