### ISSUE TITLE
Support "Run Without Debugging"

### ISSUE THREAD

**Issue by tristanlabelle** [swift-server/vscode-swift#581]
**Is your feature request related to a problem? Please describe.**
When using "Run Without Debugging", the project executable is still launched under the debugger, but one that hits no breakpoints.

![image](https://github.com/swift-server/vscode-swift/assets/2314287/42a8099f-3390-4c0d-ab5c-495c816908ba)

**Describe the solution you'd like**
The Swift extension probably doesn't support Run and should implement it. See https://code.visualstudio.com/docs/editor/debugging :
> Tip: The Run action is always available, but not all debugger extensions support 'Run'. In this case, 'Run' will be the same as 'Debug'.

**Describe alternatives you've considered**
The executable can be manually started from the command line.

**Additional context**
Seen on Windows 11

**Comment by adam-fowler** [comment]
This would be a bug for vscode-lldb but going by the description of what `Run without debugging` is, it sounds like the current setup is correct. 

> Many of the launch configuration attributes are supported in 'Run' mode. VS Code maintains a debug session while the program is running, and pressing the Stop button terminates the program.

**Comment by tristanlabelle** [comment]
Hmm. It's really unexpected to me that this is running under a codelldb process:

![image](https://github.com/swift-server/vscode-swift/assets/2314287/dab2902c-5adc-4c6e-89f2-076cbbdaaae3)

We've been having a problem with codelldb lately, preventing from starting with debugging, and because of this we also cannot launch without debugging, which is unexpected.

**Comment by adam-fowler** [comment]
I'm going to close this as it is working as expected and the codelldb issue is resolved by using lldb-vscode.
