### ISSUE TITLE
Code folding/expanding issues when functions have comments in Swift 5.8 with vscode-swift

### ISSUE THREAD

**Issue by MartinLau7** [swift-server/vscode-swift#587]
### Issue 

I am currently using Swift 5.8. After installing vscode-swift, I noticed issues with expanding and collapsing code when functions have comments.

Functions without comments do not seem to have this problem. It appears to be specifically related to the presence of comments within functions. 

I'm not sure when this problem started occurring.

![2023-08-22 15_35_17](https://github.com/swift-server/vscode-swift/assets/5416852/b6493abf-da79-40dd-ba18-0386c343618a)

### Steps to Reproduce

1. Install vscode-swift in VS Code
2. Create a Swift project
3. Add functions with comments  
4. Try to collapse/expand the functions

The code will not properly collapse or expand when comments are present.

### Expected Behavior 

The code folding/expanding should work properly regardless of whether comments are present within functions.

### Environment

- VS Code version: 1.81.1
- vscode-swift version: 1.5
- Swift version: 5.8.1
- OS version: Ubuntu 20.04

Let me know if any other details would be helpful!

**Comment by adam-fowler** [comment]
This is a sourcekit-lsp issue. It looks like it is fixed in 5.9

**Comment by adam-fowler** [comment]
Actually it isn't. It looks like it gets it right initially (most likely when sourcekit-lsp isn't running). But once sourcekit-lsp starts up it provides back values. I would add a bug to the sourcekit-lsp repository

**Comment by MartinLau7** [comment]
Yes, once I disabled sourcekit-lsp, it seems to be working normally. It would be great if you could submit an issue to the sourcekit-lsp repository.

**Comment by adam-fowler** [comment]
Martin sorry I didn't get around to adding the SourceKit-LSP issue. I doubt that fix will make it into Swift 5.9 though. I'm going to close this now.
