### ISSUE TITLE
`swift package resolve` seems to run indefinitely under certain conditions

### ISSUE THREAD

**Issue by NSExceptional** [swift-server/vscode-swift#592]
**Describe the bug**

<img width="508" alt="Screenshot 2023-08-24 at 10 23 42 AM" src="https://github.com/swift-server/vscode-swift/assets/8371943/30390b0b-870b-4040-9ff2-423047eba470">

As you can see here, the task remains running in the status area indefinitely.

**To Reproduce**

I'm not sure how to reproduce this, as there is no top-level Package.swift file. This is, however, a large monorepo that may contain many Package.swift files deep within.

**Environment**
 - OS: macOS 13.3
 - Swift version: `1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0`
 - Visual Studio Code version: `1.81.1` (latest)
 - vscode-swift version: `v1.5.0`

**Comment by adam-fowler** [comment]
Yeah I have seen this. Especially with workspaces with multiple Package.swift. It is the task completion code not triggering. It is related to a bug in VSCode where triggering two versions of a task in the same workspace with a similar setup but different working directories are considered the same task.

**Comment by adam-fowler** [comment]
If this is at startup I have just fixed an issue that would cause this issue.

**Comment by adam-fowler** [comment]
Version 1.5.1 has just been released with a fix for this
