### ISSUE TITLE
Cannot install SourceKit-lsp on Mac

### ISSUE THREAD

**Issue by AgataCzap** [swift-server/vscode-swift#600]
Hi,

I've installed Swift and shell extensions on my VSCode and I'm trying to connect both following the recommendation of building sourcekit-lsp:

I get the following errors in my terminal:

Last login: Fri Sep  1 13:44:00 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) ip_address:~ ac$ xcrun --toolchain swift sourcekit-lsp
xcrun --toolchain swift --find sourcekit-lsp
Content-Length: 94

{"jsonrpc":"2.0","id":null,"error":{"message":"expected ':' in message header","code":-32700}}LanguageServerProtocolJSONRPC/JSONRPCConnection.swift:251: Fatal error: fatal error encountered decoding message MessageDecodingError(code: LanguageServerProtocol.ErrorCode(rawValue: -32700), message: "expected \':\' in message header", id: nil, messageKind: LanguageServerProtocol.MessageDecodingError.MessageKind.unknown)
Illegal instruction: 4
(base) ip_address:~ ac$ xcrun --toolchain swift --find sourcekit-lsp
/Library/Developer/CommandLineTools/usr/bin/sourcekit-lsp
(base) ip_address:~ ac$ .build/<platform>/<configuration>/sourcekit-lsp
-bash: platform: No such file or directory
(base) ip_address:~ ac$ 

In VSCode:
"cipd init /Users/username/.cache/cros-ide/cipd -force" failed: spawn cipd ENOENT"
"missing dependent shell tool, please configure correct "swift.path.shell"

I am using Mac Ventura 13.3.1.
Yes I still have the last Intel Mac with 16GB RAM.

I can normally edit and run Swift in Xcode.
I am just using VSCode as a faster way of writing Swift, as sometimes Xcode can freeze my computer, but it's problematic that it can't find my shell tools.

Thank you.

IP address and username are hidden to protect my laptop.

**Comment by adam-fowler** [comment]
You shouldn't need to build SourceKit-LSP. It comes with the swift toolchain. If you have an Xcode install already then everything should just work.

**Comment by adam-fowler** [comment]
Can you run `swift` from the command line?

**Comment by AgataCzap** [comment]
Hi Adam,

Yes, I can run and execute swift in the command line:

Last login: Mon Sep  4 11:24:37 on console


(base) ip_address:~ ac$ xcrun swift
Welcome to Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100).
Type :help for assistance.
  1> import Foundation
  2> print("Hello World!")
Hello World!
  3>

**Comment by adam-fowler** [comment]
Can you run swift without `xcrun`?

**Comment by AgataCzap** [comment]
Yes, it also works with just swift.
(base) ac:~ ac$ swift
Welcome to Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100).
Type :help for assistance.
  1> print("Hello")
Hello
  2>

**Comment by adam-fowler** [comment]
ok then all you need to do is run VSCode and compile your project and then LSP functionality should be available. You don't need to run sourcekit-lsp separately.

**Comment by AgataCzap** [comment]
Thank you, I will give this method a go.
