### ISSUE TITLE
Better jump to definition for implementations of a protocol

### ISSUE THREAD

**Issue by MahdiBM** [swift-server/vscode-swift#601]
Consider this code:
```swift
protocol TestProtocol {
    func doThing()
}

struct TestImpl: TestProtocol { 
    func doThing() { }
}

func anyTestProtocol(value: any TestProtocol) {
    value.doThing()
}
```

In VSCode in `value.doThing()`, when you right click on `doThing()` to jump to definition, it'll just automatically jump to the protocol.

Xcode though is more smart about it and lets you choose between the protocol or one of the implementations:   

<kbd> <img width="741" alt="Screenshot 2023-09-01 at 6 04 36 PM" src="https://github.com/swift-server/vscode-swift/assets/54685446/3a7905fb-96ba-4c85-a3fd-a420f87cfdef"> </kbd>

**EDIT:**
I realize there were some left overs in the code, I removed those.

**Comment by adam-fowler** [comment]
This is a SourceKit-LSP thing. It should return multiple options if they exist.

**Comment by MahdiBM** [comment]
It always does on Xcode, an it never does on VSCode. Maybe Xcode is doing something extra?

**Comment by adam-fowler** [comment]
Are you running Xcode with SourceKit-LSP? Because by default it uses sourcekitd

**Comment by MahdiBM** [comment]
Excuse my lack of knowledge then :) I'll open an Issue in SourceKit-LSP.
