### ISSUE TITLE
Unable to look up references to highlighted symbols

### ISSUE THREAD

**Issue by dkolas** [swift-server/vscode-swift#602]
Thanks for all of your work on this!  

Environment: VSCode 1.8.1 (Windows)
Runtime: WSL2 - ubuntu
Swift (linux) version 5.7.3

When connected to the runtime in WSL2, I can build, run, test, etc, but finding references always shows `No results.`

Other things that would seem to require the debug symbols / language server are working, for example can click through to definitions, type inference working, etc.

Please let me know if there are any config changes I can make or extra info to provide.

**Comment by adam-fowler** [comment]
As with a lot of the LSP functionality, a fully built project is required before many features work. But I see you jump to definition etc working so I can assume you have that already.

There are no configuration changes that are required to get look up references to work. I have this working on my mac and inside a devcontainer running ubuntu. I will test on other platforms later. I'm away from home just now and only have my laptop. In the meantime you could do the following
- Open project
- Build project
- Go to settings and set `swift.sourcekit-lsp.trace.server` to `verbose`
- Run command `Developer: Reload Window`
- Right click on symbol and select `Go to references`
- Go to output view and select `SourceKit-LSP` from the drop down
- Cut and paste contents of that view into a comment here

**Comment by dkolas** [comment]
Thanks Adam!

Below is the output of doing the above suggestions.  It looks like the LSP isn't returning anything, so maybe I ought to try a different LSP version?

```
[Trace - 8:25:39 AM] Sending request 'textDocument/references - (19)'.
Params: {
    "textDocument": {
        "uri": "file:///<redacted-full-path-of-filename>.swift"
    },
    "position": {
        "line": 344,
        "character": 42
    },
    "context": {
        "includeDeclaration": true
    }
}


[Trace - 8:25:39 AM] Received response 'textDocument/references - (19)' in 17ms.
Result: []
```

**Comment by compnerd** [comment]
The redacted path is material to the issue.  Since you’re using WSL2, it could be causing problems.

**Comment by dkolas** [comment]
> The redacted path is material to the issue. Since you’re using WSL2, it could be causing problems.

Sure!  If it helps:

- The path is a WSL-side path (begins `/home/dkolas/projects...`)
- The path is valid / correct
- The same path is used for requests to `/inlayHint`, which are successful

**Comment by compnerd** [comment]
Hmm, and do those paths match what is in `debug.yaml`?  I know that on Windows there were some issues with path canonicalisation that prevented references from being found.  Those have since been resolved, and I wonder if this is due to that.  I assume that you are using a proper Linux toolchain and do not have a Windows toolchain installed?

**Comment by dkolas** [comment]
> Hmm, and do those paths match what is in `debug.yaml`? I know that on Windows there were some issues with path canonicalisation that prevented references from being found. Those have since been resolved, and I wonder if this is due to that. I assume that you are using a proper Linux toolchain and do not have a Windows toolchain installed?

Apologies, I'm not sure what you mean by `debug.yaml`, if you can give me a pointer I'd be happy to check.

Yes, this is derived from a linux 5.7.3 toolchain:
```
$  swift --version
Swift version 5.7.3 (swift-5.7.3-RELEASE)
Target: x86_64-unknown-linux-gnu
``` 
(above snippet from VS code terminal)

and I have the "WSL: Ubuntu" as the connected remote in the bottom corner.  

It looks like I do have an older toolchain installed on the windows side, but it's only on 5.5, so the project would not even build if that's what's being used. 

Tomorrow I'll try with a newer linux toolchain just to see what happens.

**Comment by dkolas** [comment]
Using the most recent stable linux toolchain from swift.org (5.8.1) didn't change anything.

**Comment by dkolas** [comment]
Also, FWIW - I see the same behavior on a different machine with the setup:

Environment: VSCode 1.81.1 (Windows)
Runtime: WSL2 - ubuntu
Swift (linux) version 5.8.1

which doesn't have a windows swift toolchain at all.

**Comment by adam-fowler** [comment]
Can you provide a simple project that replicates this issue.

**Comment by dkolas** [comment]
Adam,

I've attached a very simple project (the generated template plus a few lines) in which I can replicate.

Just to make sure I'm not just holding it wrong:

From within MyTestLibrary.swift, I can highlight the func name `addOne`, right-click, Find all references, which gives "No results."   Similarly highlighting MyTestClass, right-click,  Find all references, yields "No results.".  Go to references also produces "No references found". 

From within the vscode terminal:
```
$ swift --version
Swift version 5.8.1 (swift-5.8.1-RELEASE)
Target: x86_64-unknown-linux-gnu
```
[test.tar.gz](https://github.com/swift-server/vscode-swift/files/12608710/test.tar.gz)

**Comment by adam-fowler** [comment]
Hi

I tested your small project on my macOS desktop and a Linux laptop. I opened the project, built it and then from the right click menu selected find all references.

On both platforms it worked as expected and references were listed. 

I meant to test this on a Windows VM but ran out of time. I am away on holiday tomorrow and won't be back for two weeks, so unless someone else can pick this up you'll have to wait until after I get back. Sorry

**Comment by dkolas** [comment]
@adam-fowler 

Thanks for checking.  I figured it out this morning.  Based on what you said, it seemed like it should be working, because there theoretically shouldn't be any difference between the WSL and linux toolchains.

It turns out that the highlighting part is the issue.  I have a habit of double-clicking to highlight a symbol before taking any action on it.  If I just click on the symbol, and the cursor is in the middle of the symbol, everything works correctly.  However if you double-click the symbol and then right click, the cursor position that is sent to the language server is at the END of the symbol, and it returns nothing.  I can verify this in the output window of the language server:

```
[Trace - 8:08:42 AM] Sending request 'textDocument/references - (26)'.
Params: {
    "textDocument": {
        "uri": "file:///home/dkolas/swift-test/Sources/MyTestLibrary/MyTestLibrary.swift"
    },
    "position": {
        "line": 5,
        "character": 11
    },
    "context": {
        "includeDeclaration": true
    }
}

(works)

[Trace - 8:09:27 AM] Sending request 'textDocument/references - (31)'.
Params: {
    "textDocument": {
        "uri": "file:///home/dkolas/dev/projects/swift-test/Sources/MyTestLibrary/MyTestLibrary.swift"
    },
    "position": {
        "line": 5,
        "character": 15
    },
    "context": {
        "includeDeclaration": true
    }
}

(returns nothing)
```

I don't know if it's possible in VS Code to see the beginning of the selected text and use that as the position for the lookup instead of the end, which seems like it would make it work for my behavior pattern.  Either way I have a way now to make it work.

I'll leave it to you to decide whether this should be closed or a tweak made.  Thanks for your help and enjoy your holiday!

**Comment by adam-fowler** [comment]
I'll have a chat with the sourcekit-lsp team and see what we can do.

**Comment by adam-fowler** [comment]
https://github.com/apple/sourcekit-lsp/pull/975

**Comment by adam-fowler** [comment]
The fix for this has been merged now, I don't know when it will make it into a swift development release though

**Comment by dkolas** [comment]
Ok to close, then?  There's clearly a user workaround until it makes it in.  Thanks for tracking this down upstream.

**Comment by dkolas** [comment]
Sounds good!  Thanks again 😄
