### ISSUE TITLE
Error on Arch Linux: Path to shell executable "/usr/lib/usr/bin/swift" does not exist.

### ISSUE THREAD

**Issue by bitnom** [swift-server/vscode-swift#605]
Error: `Path to shell executable "/usr/lib/usr/bin/swift" does not exist.` which also prevents my vscode terminal from working.

I saw https://github.com/swift-server/vscode-swift/issues/218

My binaries are at `/usr/lib/swift/bin` which I added to `$PATH` and started `code` via :
```bash
env PATH=/usr/lib/swift/bin:$PATH code ./
```

but I continue to get the error `The terminal process failed to launch: Path to shell executable "/usr/lib/usr/bin/swift" does not exist.` as well as SourceKit error `Launching server using command /usr/lib/usr/bin/sourcekit-lsp failed. Error: spawn /usr/lib/usr/bin/sourcekit-lsp ENOENT`

If I manually set Swift: Path extension setting to `/usr/lib/swift/bin` I get the same error.

When swift was installed, it linked `/usr/lib/swift/bin/swift` to `/bin/swift`. I deleted the link while trying to resolve this issue.

```bash
λ ls -hal /usr/lib/swift/bin
Permissions Size User Date Modified Name
drwxr-xr-x     - root 28 Jul 08:37   .
drwxr-xr-x     - root 28 Jul 08:37   ..
drwxr-xr-x     - root 28 Jul 08:37   sdk-module-lists
lrwxrwxrwx     8 root 28 Jul 08:36   clang -> clang-13
lrwxrwxrwx     5 root 28 Jul 08:36   clang++ -> clang
.rwxr-xr-x  121M root 28 Jul 08:36   clang-13
lrwxrwxrwx     5 root 28 Jul 08:36   clang-cache -> clang
lrwxrwxrwx     5 root 28 Jul 08:36   clang-cl -> clang
lrwxrwxrwx     5 root 28 Jul 08:36   clang-cpp -> clang
.rwxr-xr-x   49M root 28 Jul 08:36   clangd
.rwxr-xr-x   50M root 28 Jul 08:36   docc
lrwxrwxrwx     3 root 28 Jul 08:36   ld.lld -> lld
lrwxrwxrwx     3 root 28 Jul 08:36   ld64.lld -> lld
.rwxr-xr-x   74M root 28 Jul 08:36   lld
lrwxrwxrwx     3 root 28 Jul 08:36   lld-link -> lld
.rwxr-xr-x  255k root 28 Jul 08:36   lldb
.rwxr-xr-x   88k root 28 Jul 08:36   lldb-argdumper
.rwxr-xr-x   99M root 28 Jul 08:36   lldb-server
.rwxr-xr-x   14M root 28 Jul 08:36   llvm-ar
.rwxr-xr-x  5.2M root 28 Jul 08:36   llvm-cov
.rwxr-xr-x  5.8M root 28 Jul 08:36   llvm-profdata
.rwxr-xr-x  8.6M root 28 Jul 08:36   plutil
.rwxr-xr-x  8.1k root 28 Jul 08:36   repl_swift
.rwxr-xr-x  127M root 28 Jul 08:36   sourcekit-lsp
lrwxrwxrwx    14 root 28 Jul 08:36   swift -> swift-frontend
.rwxr-xr-x   12k root 28 Jul 08:36   swift-api-checker.py
lrwxrwxrwx    14 root 28 Jul 08:36   swift-api-digester -> swift-frontend
lrwxrwxrwx    14 root 28 Jul 08:36   swift-api-extract -> swift-frontend
lrwxrwxrwx    14 root 28 Jul 08:36   swift-autolink-extract -> swift-frontend
lrwxrwxrwx    13 root 28 Jul 08:36   swift-build -> swift-package
.rwxr-xr-x   36M root 28 Jul 08:36   swift-build-sdk-interfaces
.rwxr-xr-x  1.4M root 28 Jul 08:36   swift-build-tool
.rwxr-xr-x  1.6M root 28 Jul 08:36   swift-demangle
.rwxr-xr-x   36M root 28 Jul 08:36   swift-driver
lrwxrwxrwx    13 root 28 Jul 08:36   swift-experimental-destination -> swift-package
.rwxr-xr-x  147M root 28 Jul 08:36   swift-frontend
.rwxr-xr-x   11M root 28 Jul 08:36   swift-help
.rwxr-xr-x   93M root 28 Jul 08:36   swift-package
lrwxrwxrwx    13 root 28 Jul 08:36   swift-package-collection -> swift-package
lrwxrwxrwx    13 root 28 Jul 08:36   swift-package-registry -> swift-package
lrwxrwxrwx    13 root 28 Jul 08:36   swift-run -> swift-package
lrwxrwxrwx    14 root 28 Jul 08:36   swift-symbolgraph-extract -> swift-frontend
lrwxrwxrwx    13 root 28 Jul 08:36   swift-test -> swift-package
lrwxrwxrwx    14 root 28 Jul 08:36   swiftc -> swift-frontend
lrwxrwxrwx     3 root 28 Jul 08:36   wasm-ld -> lld
```

**Environment**
 - OS: Garuda Linux (Arch)
 - Swift version: 5.8.1
 - Visual Studio Code version: 1.8.1.1
 - vscode-swift version: v1.5.1

**Additional context**
The package: http://aur.archlinux.org/packages/swift-bin

executing `sudo ln -s /usr/lib/swift/bin /usr/lib/usr/bin` temporarily fixed the issue, though this is obviously not great.

**Comment by adam-fowler** [comment]
It looks like your Swift install does not follow the standard pattern for a Linux install. Executables should be in a folder `usr/bin` relative to the root of your install. 

How did you install Swift?

**Comment by stevapple** [comment]
`/usr/lib/swift/bin` is okay, but installing Swift binary into `/bin` is **strongly** discouraged. `/bin` is a place for system essentials. The package should use `/usr/bin` instead.

**Comment by jdberry** [comment]
I'm having a very similar problem with vscode-swift. My installation is on a raspberry-pi 64 bit bullseye. Swift 5.8 installed from the distribution at https://swift-arm.com. 

I get the following errors in VSCode, to which I'm a novice:

```
[Error - 11:43:21] SourceKit Language Server client: couldn't create connection to server.
Launching server using command /usr/libexec/usr/bin/sourcekit-lsp failed. Error: spawn /usr/libexec/usr/bin/sourcekit-lsp ENOENT
```

```
Failed to load watchdog/Package.swift: {"errno":-2,"code":"ENOENT","syscall":"spawn /usr/libexec/usr/bin/swift","path":"/usr/libexec/usr/bin/swift","spawnargs":["package","describe","--type","json"],"cmd":"/usr/libexec/usr/bin/swift package describe --type json"}
```

```
$ env | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
$ ls -l /usr/bin | grep swift
lrwxrwxrwx 1 root root          36 Sep  9 11:20 sourcekit-lsp -> /usr/libexec/swift/bin/sourcekit-lsp
lrwxrwxrwx 1 root root          37 Sep  9 11:18 swift -> /usr/libexec/swift/bin/swift-frontend
lrwxrwxrwx 1 root root          37 Sep  9 11:19 swiftc -> /usr/libexec/swift/bin/swift-frontend
$ ls /usr/libexec/swift
bin  include  lib  local  share
```

Is this an issue with how the swift-arm distribution is layed out? @futurejones

**Comment by adam-fowler** [comment]
The extension assumes that all swift toolchains are structured as the Apple released ones ie all binaries are inside a `usr/bin` folder. This was a recent change previously it was more flexible but subject to some vagueness about where to find executables. I can review this change. 

Perhaps @futurejones can comment on why he chose to not include the `usr` folder in his installs.

**Comment by stevapple** [comment]
> Perhaps @futurejones can comment on why he chose to not include the `usr` folder in his installs.

@adam-fowler Swift-ARM is absolutely on the correct path. It simply takes `/usr/libexec/swift` as the prefix of toolchain installation, and all the tools are available in `/usr/libexec/swift/usr/bin`. This is correct because we only want to expose a very small subset (`swift`, `swiftc` and `sourcekit-lsp`) to `PATH` permanently.

> I get the following errors in VSCode, to which I'm a novice:
> 
> ```
> [Error - 11:43:21] SourceKit Language Server client: couldn't create connection to server.
> Launching server using command /usr/libexec/usr/bin/sourcekit-lsp failed. Error: spawn /usr/libexec/usr/bin/sourcekit-lsp ENOENT
> ```

@jdberry I believe your problem is rather simple and has nothing to do with either the toolchain. The path to SourceKit-LSP is `/usr/libexec/swift/usr/bin/sourcekit-lsp` but you’re trying to launch `/usr/libexec/usr/bin/sourcekit-lsp`, and that’s all for it.

**Comment by stevapple** [comment]
🤔After trying to understand the situation correctly… It seems the fix is as simple as not hard-coding (and relying on) the parent directory of `bin` to be `usr`? I can’t think about any usecase where we’re relying on it to get things work.

**Comment by futurejones** [comment]
> The extension assumes that all swift toolchains are structured as the Apple released ones ie all binaries are inside a usr/bin folder. This was a recent change previously it was more flexible but subject to some vagueness about where to find executables.

@adam-fowler can you post links to the commits where this change has occurred. 

Moving the installation directory from `/usr/` to `/usr/libexec/swift/` was done to eliminate conflicts caused by swift shipping with its own version of clang, llvm, libicu and others. Adding an extra `/usr` was not added as there was no indication that is was needed in testing prior to the package releases.

The installation directory can be changed to `/usr/libexec/swift/usr/` if this will fix the issue but I would like to know why this is now needed as there was no issues previously with this installation path.

**Comment by adam-fowler** [comment]
ok, I'll have to work around it. I made an assumption that all swift installs were structured as Apple structured theirs.
