### ISSUE TITLE
High CPU usage and autocompletion breaking on Windows

### ISSUE THREAD

**Issue by tomwyr** [swift-server/vscode-swift#612]
**Describe the bug**
Opening a new file and just changing language mode to Swift causes multiple cores of the CPU to kick in and never stop, even when the source file is still empty. Also, the autocompletion doesn't seem to work and, as soon as there's an error introduced to the code, the analyzer hangs at displaying that particular error unless I restart vscode or the LSP.

**Expected behavior**
Autocompletion doesn't break and CPU usage is low when LSP has nothing to be busy with.

**Environment**
 - OS: Windows 11
 - Swift version: compnerd.org Swift version 5.9 (swift-5.9-RELEASE) Target: x86_64-unknown-windows-msvc
 - Visual Studio Code version: 1.82.2
 - vscode-swift version: 1.5.2

**Additional context**
The red lines on the screenshots mark the moment where language mode is changed to Swift and (I assume) the vscode extension gets activated.

![1](https://github.com/swift-server/vscode-swift/assets/9600796/3fc5cbe4-7194-4667-bf2b-3fe823c570f7)
![2](https://github.com/swift-server/vscode-swift/assets/9600796/da7cd69f-814b-4e11-8626-c6d86e045b76)
![3](https://github.com/swift-server/vscode-swift/assets/9600796/6c9cc2e9-fde0-4c3c-9482-3cdde34c59c3)

**Comment by adam-fowler** [comment]
@compnerd have you see anything like this?

**Comment by Shockah** [comment]
Having the same issue, straight after setting up Swift and VSCode.

**Comment by natinusala** [comment]
I have the same issue on Windows 10 here. 

I also have a weird problem where the SourceKit LSP process locks up C files (including headers) in my project and I can't edit them anymore unless I fully exit vscode (which kills sourcekit). I don't know if it's related.

**Comment by adam-fowler** [comment]
> I also have a weird problem where the SourceKit LSP process locks up C files (including headers) in my project and I can't edit them anymore unless I fully exit vscode (which kills sourcekit). I don't know if it's related.

This will be unrelated. Probably an issue you should post to sourcekit-lsp repo.

@tomwyr Similarly this performance issue should be bugged on sourcekit-lsp repo

**Comment by icnahom** [comment]
The issue does not occur in Swift 5.8.1.

**Comment by adam-fowler** [comment]
> The issue does not occur in Swift 5.8.1.

Can anyone else verify this please?

**Comment by tomwyr** [comment]
Can confirm the CPU usage is back to normal in Swift 5.8.1. Also I tested the latest version 5.9.1 on a different laptop and the problem persists there as well.

**Comment by adam-fowler** [comment]
This almost certainly is a SourceKit-LSP issue, so I have reported it there https://github.com/apple/sourcekit-lsp/issues/982

**Comment by adam-fowler** [comment]
Closing as related SourceKit-LSP issue has been closed
