### ISSUE TITLE
Broken "Swift: Clean Build"?

### ISSUE THREAD

**Issue by MahdiBM** [swift-server/vscode-swift#616]
**Describe the bug**
The "Swift: Clean Build" (COMMAND+SHIFT+P -> "Swift: Clean Build") action only does a `swift package clean` without following that with a `swift build`:
```
Executing task: /Applications/Xcode 15.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift package clean
```
It either should do both, or be renamed to something like "Swift: Clean Package" in my preception.

**Environment**
* Swift 5.9 RELEASE
* macOS 14
* on macOS or on a dev container

**Comment by adam-fowler** [comment]
Are you expecting it to clean and then build.
How about `Clean build folder`

**Comment by MahdiBM** [comment]
Since we are in VSCode I would just name it Clean .build in that case

**Comment by adam-fowler** [comment]
`Clean Build Folder` is what Xcode uses, so I'll keep to that
