### ISSUE TITLE
Work out what executable to run to debug tests on Windows

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#63]
When creating a launch configuration to debug tests we need the actual executable that is run when the tests are running (we don't want to attach to the swift executable).

- On macOS we run `xctest mytests.xctest`.
- On linux we run `my tests.xctest`.

I assumed that Windows would be the same as Linux, but @svanimpe has pointed out this is not the case.

@compnerd can you help us? What is the executable we should attach to on Windows?

**Comment by svanimpe** [comment]
If I try to run the **.xctest** file, Windows just ask me what application it should open this file in. If I rename it to give it an **.exe** extension, I do get a more useful error message, saying it cannot find **XCTest.dll**.

Running the tests with `swift test --enable-test-discovery` works fine.

**Comment by compnerd** [comment]
@adam-fowler the binary is the .xctest bundle.  You can query that from SPM to get the actual path.  You will need to inject XCTest into the path as it is not in the path (you could be cross compiling, so can't have it there by default).

**Comment by adam-fowler** [comment]
@compnerd Where is the XCTest.dll? I'm kinda doing this blind (with help from @svanimpe) as I don't have a Windows PC anymore.

Hmm how am I going to get the `.xctest` binary to find the XCTest dll via `launch.json`. I guess we could add the path to the environment of the test Task. 

@svanimpe once the rest of the build and test PR is in do you think you set this up? Might give us a quicker turnaround

**Comment by compnerd** [comment]
It's unknown!  Thats the beauty of all this :-D  You need to figure that out yourself.

You can use `DEVELOPER_DIR`, the target, and the contents of `Info.plist` to figure that out.  The `Info.plist` for the platform contains the version information for XCTest.  The `DEVELOPER_DIR` environment variable tells you where the developer tools are located, and the target tells you the platform.

`DEVELOPER_DIR`: `S:\Library\Developer`
target: `x86_64-unknown-windows-msvc`

This tells you that you should look at `S:\Library\Developer\Platforms\Windows.platform` .  You will find a `Info.plist`.  If you look at that, the `DefaultProperties ` will give you the `XCTEST_VERSION` (e.g. `development`).  This tells you that you should look at `S:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development\usr\bin`

**Comment by adam-fowler** [comment]
@compnerd Jeez this sounds fun. Thanks for all the info. 
@svanimpe I think this one is on you, I can't do this blind

**Comment by svanimpe** [comment]
I can get it working with the following launch config:

```typescript
return [{
    type: "lldb",
    request: "launch",
    name: `Test ${ctx.swiftPackage.name}`,
    program: `./.build/debug/${ctx.swiftPackage.name}PackageTests.xctest`,
    cwd: `\${workspaceFolder:${ctx.folder.name}}`,
    env: {
        "PATH": "C:\\Library\\Developer\\Platforms\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\bin;${env:PATH}"
    },
    preLaunchTask: `swift: Build All`
}];
```
If I understand @compnerd  correctly, this extra path is actually `${DEVELOPER_DIR}\Platforms\${target}.platform\Developer\Library\XCTest-${version}\usr\bin`

Is that correct? If so, how do I find the correct `${target}` platform?

**Comment by adam-fowler** [comment]
I'd prefer adding the PATH environment when we create the task, not to the launch config. But its a starting point for sure

**Comment by compnerd** [comment]
@svanimpe - right; the platform is a static mapping:

*-*-windows-* -> Windows
*-*-linux-android* -> Android
*-*-linux-* -> Linux
*-*-macosx* -> MacOSX
*-*-ios* -> iPhoneOS
*-*-tvos* -> tvOS
*-*-watchos* -> watchOS
...

You need to know what platform the user is targeting, and the best way to know that is to ask the user.

**Comment by svanimpe** [comment]
@compnerd Can we assume that on Windows:

- **DEVELOPER_DIR** is set
- The Windows platform is available
- It contains an **Info.plist**
- That **Info.plist** contains the **XCTEST_VERSION** key?

In other words, if one of these is not true, can we consider that an error?

**Comment by compnerd** [comment]
> @compnerd Can we assume that on Windows:
> 
> * **DEVELOPER_DIR** is set
Yes, this is definitely a valid assumption

> * The Windows platform is available
This is not a valid assumption (at least in the medium/long term).  I suppose that for the imminent releases that will hold, but this is not a valid assumption.  There is no reason that I need the Windows SDK, I could always be cross-compiling to a different platform, and could just avoid installing the SDK for Windows because it will never be used.

> * It contains an **Info.plist**

Yes, this is a valid assumption.

> * That **Info.plist** contains the **XCTEST_VERSION** key?

This is fine to assume for now.  Perhaps some day this may be lifted, but I don't see that going away anytime soon sadly.  If you can think of a way to disconnect the versioning and not require this, I'd be interested in hearing about that.

> In other words, if one of these is not true, can we consider that an error?

Outside of the Windows platform not being available, the others should definitely be considered a hard error.  That is an invalid installation and ideally would surface an error to the user indicating that the installation is invalid/corrupt.
