### ISSUE TITLE
sourcekit-lsp server does not start if opening a C++ file.

### ISSUE THREAD

**Issue by GeorgeLyon** [swift-server/vscode-swift#630]
**Describe the bug**
I'm working on a mixed CMake based C++ and Swift project, and to make this work I need to use this extension instead of the Clangd extension. But this extension only activates when opening a Swift file so when I open a workspace I don't get LSP functionality until I open a Swift file. This extension should also be initialized when opening a C++ file.

**To Reproduce**
1. Open a CMake based project (which uses compile-commands.json to power LSP)
2. Open a C++ file
3. Try to use LSP features (hover, go-to-def), but nothing will work (and no "SourceKit" entry in VSCode's "Output" viewer)
5. Open a Swift file
6. Go back to the original C++ file
7. Try to use LSP features (hover, go-to-def)
8. LSP functionality works fine

**Expected behavior**
Opening a C++ file should initialize the extension and sourcekit-lsp

**Environment**
 - OS: Ubuntu 22.04 in a devcontainer

**Additional context**

**Comment by adam-fowler** [comment]
If you have a `compile-commands.json` in the base of the project it should activate.

**Comment by GeorgeLyon** [comment]
Ah, I found this bug while testing this recent source kit change: https://github.com/apple/sourcekit-lsp/pull/915 so my particular test had compile_commands.json in a subfolder. That is probably the issue. Still, it would be great if the extension supported the new project configurations.

**Comment by adam-fowler** [comment]
You could try enabling `searchSubfoldersForPackages`. Only problem being the extension will think the root folder for that CMake project is the subfolder. Not totally sure how that'll affect it though. 

The extension supports multiple packages per workspace and assumes a Package.swift, compile-commands.json indicates the root of a package.

**Comment by GeorgeLyon** [comment]
This makes sense to me, I'm not currently set up to test top-of-tree but it makes sense to me that this will fix the issue (IIRC from the sourcekit-lsp code, a "workspace" is just a list of paths, such as the paths to files that have compile commands, with no real "root directory" concept). I'll reopen if I run into it again.
