### ISSUE TITLE
Error or Empty LSP Response on hover.

### ISSUE THREAD

**Issue by RussBaz** [swift-server/vscode-swift#632]
**Describe the bug**
I recently started getting empty or error responses when I hover or do other thing with my code. But not with every function or variable. Just most.

Here is what I get when I hover over a variable declaration:
```
let protected: <<error type>>
```

But I am having no issues when opening the same project from Xcode.

Please advise on how to properly debug this issue.

**To Reproduce**
I am struggling to reproduce with other projects, as it works fine when I create a new empty project.

**Expected behavior**
Type information correctly displayed.

**Environment**
 - OS: [e.g. Ubuntu 20.04]: MacOS 14.0 (Original issue was found in an Intel mac. Since then I tested it on M1 mac with 14.1 and got the same issue)
 - Swift version (output of `swift --version`)
```
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: x86_64-apple-macosx14.0
```
 - Visual Studio Code version: 1.83.1
 - vscode-swift version: v1.7.0

**Additional context**
Here is the Swift Forums thread where I originally reported the issue, with extra details such as a detailed log trace: https://forums.swift.org/t/vs-code-extension-is-failing-how-to-debug-a-cause/68059/

**Comment by adam-fowler** [comment]
Ah I hadn't noticed you added this to the vscode-swift extension repo. It should really go in the apple/sourcekit-lsp repo as it is an issue with the lsp server.

**Comment by RussBaz** [comment]
As it turns out, running `swift package reset`, and then resolving and building again solved the issue. Therefore, I can no longer replicate the issue. I will be closing it now.

I suspect this issue might have been caused by leftovers of previous incremental builds due to me upgrading not long ago from 5.8 to 5.9. Further details can be found in the previously attached forum thread.
