### ISSUE TITLE
Running tests from the UI fails with a ENOENT error in Windows if VSCode doesn't run as administrator

### ISSUE THREAD

**Issue by daniele-niero** [swift-server/vscode-swift#637]
When VScode runs in user mode, instead of "as administrator", running a test from the UI, like from the `Testing` panel, results in an error like this:
```
Error: {"errno":-4058,"code":"ENOENT","syscall":"spawn c:\\Users\\danie\\Desktop\\SwiftNodes\\.build\\debug\\SwiftNodesPackageTests.xctest","path":"c:\\Users\\danie\\Desktop\\SwiftNodes\\.build\\debug\\SwiftNodesPackageTests.xctest","spawnargs":["MathTests.MathVectorTests/testCrossProduct"],"cmd":"c:\\Users\\danie\\Desktop\\SwiftNodes\\.build\\debug\\SwiftNodesPackageTests.xctest MathTests.MathVectorTests/testCrossProduct"}
```
clearly this path is wrong `c:\\Users\\danie\\Desktop\\SwiftNodes\\.build\\debug\\SwiftNodesPackageTests.xctest`, `.build\debug` is actullt a yaml file, there should be another folder between them. For me it should be `x86_64-unknown-windows-msvc`

![image](https://github.com/swift-server/vscode-swift/assets/967740/73d15fd3-bba3-4dc0-b00d-02efca6df03c)  
![image](https://github.com/swift-server/vscode-swift/assets/967740/d8a0262c-9bd8-4f16-bb9d-e34fa922255a)

Everything works fine if VSCode is running as administrator.

**Environment**
 - OS: Windows 11 and 10
 - Swift version 5.9.1
 - Visual Studio Code version: 1.84.2 (user setup)
 - vscode-swift version: 1.7.0

**Comment by stevapple** [comment]
I doubted if you had enabled Developer Mode, which is required for SwiftPM to symlink the latest build directory to `.build/release` or `.build/debug`, which is then used by IDEs and tools like VS Code. Running as Administrator, of course, has the highest privilege so there’s no problem.
 
It’s okay for the plugin to move away from relying on the shortcut. Just to mention that your setup is not standard and Administrator is not the most suitable solution.

**Comment by daniele-niero** [comment]
Ah, that was it. 

So, activating developer mode, fixes the issue. However I wonder if it must be this way. When I activated it, a warning message said it is not recommended it for security reasons and, in fact, this is the first time I had to do it. No even at work it is on.

**Comment by compnerd** [comment]
Yeah, this is as @stevapple pointed out an issue with the "Developer Mode".  I do generally dislike this requirement and would like to fix it, but haven't had time to do so.  https://github.com/thebrowsercompany/swift-build/issues/56 has some ideas of how to reduce the reliance on that.

**Comment by daniele-niero** [comment]
Ah, but then I don't need to activate the developer mode, I just need to find a way to grant SeCreateSymbolicLinkPrivilege to myself?

**Comment by compnerd** [comment]
Yes, that is possible to do via the Group Policy Editor.
