### ISSUE TITLE
When testing runs, don’t show Test Results View straight away

### ISSUE THREAD

**Issue by ahoppen** [swift-server/vscode-swift#651]
When running tests, I think it would be nice if VS Code didn’t show the test results pane straight away. I would prefer to have some indicator in the status bar that says “Testing” (similar to “Building”) and only open the Test Results view if test execution fails. If test execution succeeds, VS Code could maybe show a transient notification (or whatever the things in the bottom right corner that eg. tell you to restart LSP when charging the server path are called).

I just think that would be less noisy and lets me focus on the code more.

**Comment by adam-fowler** [comment]
The extension doesn't have any control over this, but there are settings that have some control. There is a `Testing: Open Testing` setting, although it  doesn't seem to affect the display of the Test Results view. This might be worthwhile bugging in https://github.com/microsoft/vscode

**Comment by adam-fowler** [comment]
Found what this was. It was my fault in the end. It is fixed in #659. The setting should work after that is merged
