### ISSUE TITLE
Debug frames of async functions starts with “await resume partial function for”, which is a lot of clutter

### ISSUE THREAD

**Issue by ahoppen** [swift-server/vscode-swift#655]
See attached screenshot. IMO the “await resume partial function for” adds clutter with little value. Maybe the extension could post-process the stack frames to remove or shorten that prefix.

<img width="2672" alt="Screenshot 2023-12-05 at 16 33 54" src="https://github.com/swift-server/vscode-swift/assets/4062178/fe7a28b5-8752-4a6e-87c7-8807ee22497c">

**Comment by adam-fowler** [comment]
The debugger used is either another extension [CodeLLDB](https://github.com/vadimcn/codelldb) or for Windows the debug adapter packaged that comes with the swift install is also available. You should bug this on either on CodeLLDB, or LLVM if you want it fixed

**Comment by ahoppen** [comment]
Filed https://github.com/vadimcn/codelldb/issues/1039
