### ISSUE TITLE
Go to definition doesn't work on Windows for packages and external types

### ISSUE THREAD

**Issue by oskargargas** [swift-server/vscode-swift#662]
**Describe the bug**
`Go to definition` doesn't work on Windows for packages and external types. It works for types and variables declared directly in project.

**To Reproduce**
1. Open The Browser Company `windows-samples` [(my fork with fix for workspace config)](https://github.com/oskargargas/windows-samples/tree/main)
2. Build and run. If something doesn't work take a look here: https://github.com/thebrowsercompany/windows-samples/issues/5#issuecomment-1871221162
3. Open `PreviewApp.swift`
4. Go to definition:
    1. In line 1. `import Foundation`
    2. In line 2. `import UWP`
    3. In line 24. `Button()`
5. See error
    1. In line 1. `import Foundation` - `Failed to load swiftinterface `
    2. In line 2. `import UWP` - `Failed to load swiftinterface `
    3. In line 24. `Button()` - No definition found

`Failed to load swiftinterface` - assuming this one: https://github.com/swift-server/vscode-swift/blob/2f29b2b916735a04d0b2a7d105d5946e89f5563e/src/ui/ReadOnlyDocumentProvider.ts#L29

**Expected behavior**
Symbol definition is presented. UWP and other packages are found and presented in Package Dependencies window. `Button` is present in `WinUI -> Microsoft.UI.Xaml.Controls.swift:446` or directly in `WinRT\Sources\WinUI\Microsoft.UI.Xaml.Controls.swift`

**Environment**
 - OS: Windows 10 Pro 22H2
 - Swift version (output of `swift --version`)
     - https://github.com/thebrowsercompany/swift-build/releases/tag/20231224.2
     - ```
       compnerd.org Swift version 5.11-dev (LLVM 13124099c3f0229, Swift f08f86c71617bac)
       Target: x86_64-unknown-windows-msvc
       ```
 - Visual Studio Code version: newest, 1.85.1
 - vscode-swift version: newest, 1.7.1

**Additional context**
Add any other context about the problem here.

Line 1, 2 trace:
```
[Trace - 5:25:40 PM] Sending request 'textDocument/definition - (41)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
    },
    "position": {
        "line": 4,
        "character": 10
    }
}

[org.swift.sourcekit-lsp:request-41] default 2023-12-28 16:25:40.974
Received request: textDocument/definition
{
  "position" : {
    "character" : 10,
    "line" : 4
  },
  "textDocument" : {
    "uri" : "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
  }
}
---
[org.swift.sourcekit-lsp:request-41] default 2023-12-28 16:25:40.981
Succeeded (took 6.999969482421875ms)
textDocument/definition
Optional<LocationsOrLocationLinksResponse>
[
  {
    "range" : {
      "end" : {
        "character" : 0,
        "line" : 0
      },
      "start" : {
        "character" : 0,
        "line" : 0
      }
    },
    "uri" : "file:///C:/Users/oskar/AppData/Local/Temp/GeneratedInterfaces/WinUI.swiftinterface"
  }
]
---
[Trace - 5:25:40 PM] Received response 'textDocument/definition - (41)' in 9ms.
Result: [
    {
        "uri": "file:///C:/Users/oskar/AppData/Local/Temp/GeneratedInterfaces/WinUI.swiftinterface",
        "range": {
            "end": {
                "character": 0,
                "line": 0
            },
            "start": {
                "character": 0,
                "line": 0
            }
        }
    }
]

[Trace - 5:25:41 PM] Sending request 'textDocument/diagnostic - (42)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
    }
}

[org.swift.sourcekit-lsp:request-42] default 2023-12-28 16:25:41.195
Received request: textDocument/diagnostic
{
  "textDocument" : {
    "uri" : "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
  }
}
---
[org.swift.sourcekit-lsp:request-42] default 2023-12-28 16:25:41.201
Succeeded (took 6.000518798828125ms)
textDocument/diagnostic
DocumentDiagnosticReport
{
  "items" : [

  ],
  "kind" : "full"
}
---
[Trace - 5:25:41 PM] Received response 'textDocument/diagnostic - (42)' in 7ms.
Result: {
    "kind": "full",
    "items": []
}
```

Line 24 trace:
```
[Trace - 5:53:24 PM] Sending request 'textDocument/definition - (80)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
    },
    "position": {
        "line": 23,
        "character": 34
    }
}

[org.swift.sourcekit-lsp:request-80] default 2023-12-28 16:53:24.159
Received request: textDocument/definition
{
  "position" : {
    "character" : 34,
    "line" : 23
  },
  "textDocument" : {
    "uri" : "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
  }
}
---
[org.swift.sourcekit-lsp:request-80] error 2023-12-28 16:53:24.166
Fallback definition request ResponseError(code: LanguageServerProtocol.ErrorCode(rawValue: -32001), message: "unsupported method")
---
[org.swift.sourcekit-lsp:request-80] default 2023-12-28 16:53:24.167
Succeeded (took 8.001327514648438ms)
textDocument/definition
Optional<LocationsOrLocationLinksResponse>
null
---
[Trace - 5:53:24 PM] Received response 'textDocument/definition - (80)' in 9ms.
No result returned.

[Trace - 5:56:01 PM] Sending request 'textDocument/diagnostic - (81)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
    }
}

[org.swift.sourcekit-lsp:request-81] default 2023-12-28 16:56:01.943
Received request: textDocument/diagnostic
{
  "textDocument" : {
    "uri" : "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
  }
}
---
[org.swift.sourcekit-lsp:request-81] default 2023-12-28 16:56:01.947
Succeeded (took 3.9997100830078125ms)
textDocument/diagnostic
DocumentDiagnosticReport
{
  "items" : [

  ],
  "kind" : "full"
}
---
[Trace - 5:56:01 PM] Received response 'textDocument/diagnostic - (81)' in 7ms.
Result: {
    "kind": "full",
    "items": []
}
```

**Comment by adam-fowler** [comment]
Looking at the LSP output it is most likely related to the percent encoded `:`. 

Out of interest could you post a successful jump to definition within your package to see if it percent encodes the `:`.

**Comment by oskargargas** [comment]
Here is a successful jump. It also contains this `c%3A` in some places.

```
[Trace - 9:21:39 PM] Sending request 'textDocument/definition - (160)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
    },
    "position": {
        "line": 30,
        "character": 11
    }
}


[org.swift.sourcekit-lsp:request-60] default 2023-12-28 20:21:39.600
Received request: textDocument/definition
{
  "position" : {
    "character" : 11,
    "line" : 30
  },
  "textDocument" : {
    "uri" : "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
  }
}
---
[org.swift.sourcekit-lsp:request-60] default 2023-12-28 20:21:39.607
Succeeded (took 6.999969482421875ms)
textDocument/definition
Optional<LocationsOrLocationLinksResponse>
[
  {
    "range" : {
      "end" : {
        "character" : 12,
        "line" : 23
      },
      "start" : {
        "character" : 12,
        "line" : 23
      }
    },
    "uri" : "file:///C:/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
  }
]
---
[Trace - 9:21:39 PM] Received response 'textDocument/definition - (160)' in 8ms.
Result: [
    {
        "range": {
            "end": {
                "character": 12,
                "line": 23
            },
            "start": {
                "line": 23,
                "character": 12
            }
        },
        "uri": "file:///C:/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
    }
]


[Trace - 9:21:39 PM] Sending request 'textDocument/codeAction - (161)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
    },
    "range": {
        "start": {
            "line": 23,
            "character": 12
        },
        "end": {
            "line": 23,
            "character": 12
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 23,
                        "character": 12
                    },
                    "end": {
                        "line": 23,
                        "character": 22
                    }
                },
                "message": "\"animatable\": Unknown word.",
                "severity": 3,
                "source": "cSpell"
            }
        ],
        "triggerKind": 2
    }
}


[org.swift.sourcekit-lsp:request-61] default 2023-12-28 20:21:39.874
Received request: textDocument/codeAction
{
  "context" : {
    "diagnostics" : [
      {
        "message" : "\"animatable\": Unknown word.",
        "range" : {
          "end" : {
            "character" : 22,
            "line" : 23
          },
          "start" : {
            "character" : 12,
            "line" : 23
          }
        },
        "severity" : 3,
        "source" : "cSpell"
      }
    ],
    "triggerKind" : 2
  },
  "range" : {
    "end" : {
      "character" : 12,
      "line" : 23
    },
    "start" : {
      "character" : 12,
      "line" : 23
    }
  },
  "textDocument" : {
    "uri" : "file:///c%3A/Users/oskar/Developer/windows-samples/WinUI3AnimationsPreview/Sources/WinUI3AnimationsPreview/PreviewApp.swift"
  }
}
---
[org.swift.sourcekit-lsp:request-61] default 2023-12-28 20:21:39.879
Succeeded (took 5.001068115234375ms)
textDocument/codeAction
Optional<CodeActionRequestResponse>
[

]
---
[Trace - 9:21:39 PM] Received response 'textDocument/codeAction - (161)' in 10ms.
Result: []
```

**Comment by oskargargas** [comment]
Making more tests now. I see that jumps to class methods, variables declared in scope work. But jump to class field does not. And everything is correctly visible in `Outline` window...

**Comment by oskargargas** [comment]
Here you go:
```
PS C:\Users\oskar\AppData\Local\Temp\GeneratedInterfaces> ls
    Directory: C:\Users\oskar\AppData\Local\Temp\GeneratedInterfaces

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        28.12.2023     17:37        1045873 Foundation.swiftinterface
-a----        28.12.2023     19:03        3072157 Swift.Misc.swiftinterface
-a----        28.12.2023     17:16        3072157 Swift.String.swiftinterface
-a----        28.12.2023     14:58          95363 WindowsFoundation.swiftinterface
-a----        28.12.2023     17:25        1320318 WinUI.swiftinterface
```

Content looks legit:
[GeneratedInterfaces.zip](https://github.com/swift-server/vscode-swift/files/13792348/GeneratedInterfaces.zip)
```swift
/// [Open Microsoft documentation](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.button)
open class Button : WinUI.ButtonBase {

    override open func _getABI<T>() -> UnsafeMutablePointer<T>?

    override open var thisPtr: WindowsFoundation.IInspectable { get }

    public static func from(abi: UnsafeMutablePointer<__x_ABI_CMicrosoft_CUI_CXaml_CControls_CIButton>?) -> WinUI.Button?

    override public init(fromAbi: WindowsFoundation.IInspectable)

    override public init<Composable>(composing: Composable.Type, _ createCallback: (WindowsFoundation.UnsealedWinRTClassWrapper<Composable>?, inout WindowsFoundation.IInspectable?) -> Composable.Default.SwiftABI) where Composable : WindowsFoundation.ComposableImpl

    override open func queryInterface(_ iid: WindowsFoundation.IID) -> WindowsFoundation.IUnknownRef?

    override public init()

    /// [Open Microsoft documentation](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.button.flyoutproperty)
    public static var flyoutProperty: WinUI.DependencyProperty! { get }

    /// [Open Microsoft documentation](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.button.flyout)
    public var flyout: WinUI.FlyoutBase!
}
```

I also deleted them, restarted everything and checked if they generate correctly - they do.

**Comment by adam-fowler** [comment]
Hi Oskar, 
I think I know what the issue is now. I broke the URI I received from SourceKit-LSP when trying to make it a readonly document URI. I have a PR #664 which should fix this. 

I'm not going to be near a machine I can test Windows code on for a few weeks, so if you could test it that'd be awesome. Details on how to build the extension and test can be found here https://github.com/swift-server/vscode-swift/blob/main/CONTRIBUTING.md.

cc: @tristanlabelle

**Comment by oskargargas** [comment]
Thanks @adam-fowler! Looks like it's working now. Closing
