### ISSUE TITLE
Launch configurations hang after building

### ISSUE THREAD

**Issue by nitricware** [swift-server/vscode-swift#663]
**Describe the bug**
After building the project, the built file is not run.

**To Reproduce**
1. Go to Run > Start Debugging (F5)

**Expected behavior**
After the "Build complete! (X.Xs)" message I expect the output of my program to appear and the activity indicator in the Run and Debug menu to disappear.

**Environment**
 - OS: Windows 11 22000.2652
 - Swift version: Swift version 5.9.2 (swift-5.9.2-RELEASE)
 - Visual Studio Code version: 1.7.1
 - vscode-swift version: 1.85.1

**Additional context**
When I run `swift run` in the terminal (the built-in one and the stand alone terminal) the command builds and runs the code just fine.

Could this be a problem with CodeLLDB? The path to the lldb library is empty in the settings of the extension.

**Comment by adam-fowler** [comment]
This could be an CodeLLDB issue. You could check the CodeLLDB output pane.
Another alternative is to use the LLDB adapter that comes with the Windows version of swift. Go to the settings and select `Swift › Debugger: Use Debug Adapter From Toolchain`.

**Comment by nitricware** [comment]
Now the problem is similar, but different: After "Build complete!", the activity indicator disappears but the program is still not run. LLDB and lldb-vscode outputs are empty.

Here's the complete output from the terminal:

```
Executing task: C:\Users\MyUser\scoop\apps\swift\5.9.2\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr/bin/swift.exe build --product test2 -Xlinker -debug:dwarf 

Building for debugging...
Build complete! (0.53s)
 *  Terminal will be reused by tasks, press any key to close it.
```

**Comment by adam-fowler** [comment]
Can you post your `launch.json` file here

**Comment by nitricware** [comment]
> Can you post your `launch.json` file here

yes, of course:

```json
{
    "configurations": [
        {
            "type": "swift-lldb",
            "request": "launch",
            "args": [],
            "cwd": "${workspaceFolder:test2}",
            "name": "Debug test2",
            "program": "${workspaceFolder:test2}\\.build\\debug\\test2.exe",
            "preLaunchTask": "swift: Build Debug test2"
        },
        {
            "type": "swift-lldb",
            "request": "launch",
            "args": [],
            "cwd": "${workspaceFolder:test2}",
            "name": "Release test2",
            "program": "${workspaceFolder:test2}\\.build\\release\\test2.exe",
            "preLaunchTask": "swift: Build Release test2"
        }
    ]
}
```

Interestingly, when I run the program it does not create a `tasks.json` which i think it did earlier...

**Comment by adam-fowler** [comment]
What happens if you try to run `.build\debug\test.exe` from the command line? 

The extension does not generate a `tasks.json` file. So I wouldn't worry about that. The build tasks are generated internally.

**Comment by nitricware** [comment]
if i run `.build\debug\test2.exe` from the build-in terminal, it displays the output of the program (which is just "Hello, World!" right now.

**Comment by adam-fowler** [comment]
Can you run swift lldb from the command line and debug your app. Sometimes when there is a discrepancy between python versions it fails.

**Comment by nitricware** [comment]
How would I do this?

**Comment by adam-fowler** [comment]
That's good news. Should have been the first question I asked. The Windows swift install is quite fussy about which Python version is available for LLDB.

I do have a task to pre-empt this and warn the user I just haven't got around to it.

**Comment by nitricware** [comment]
Thanks again for your patience and the great work on the extension!
