### ISSUE TITLE
Swift Windows ARM + VSCode Issue: SourceKit Language Server client: couldn't create connection to server

### ISSUE THREAD

**Issue by litewrap** [swift-server/vscode-swift#681]
**Describe the bug**

**To Reproduce**
- With Windows 11 ARM (I am using Parallels Desktop on M1 Mac)
- Install Swift Windows arm64 build
- Go to any Swift PM project
- Open VS Code
- Message appear: "SourceKit Language Server client: couldn't create connection to server"

**Expected behavior**

**Environment**

Swift Windows arm64------------------
https://github.com/thebrowsercompany/swift-build/releases/tag/20240213.1

VSCode-----------------------
Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:58.324Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT arm64 10.0.22000

**Additional context**

**Comment by adam-fowler** [comment]
@compnerd what is the status of Swift on Windows ARM?

**Comment by compnerd** [comment]
The toolchain should be stable, there is issue that we just fixed with concurrency. I think that the LSP is currently known to be not working :(. We don't have official builds yet, but that is something that I am hoping we can get soon.

**Comment by adam-fowler** [comment]
Ok this is an issue with SourceKit-LSP. I'm going to close this here.
