### ISSUE TITLE
Use `workspace/tests` and `document/tests` requests to list tests inside a project

### ISSUE THREAD

**Issue by ahoppen** [swift-server/vscode-swift#693]
https://github.com/apple/sourcekit-lsp/issues/611 introduced the `workspace/tests` and `document/tests` methods to lists all tests within a workspace or document. The VS Code extension should be using them to list the available tests.

**Comment by adam-fowler** [comment]
Awesome I missed that went in.

**Comment by adam-fowler** [comment]
Does this request need a built project?

**Comment by ahoppen** [comment]
Yes, it does. It reads the index to find the tests

**Comment by adam-fowler** [comment]
@ahoppen Do these return `SymbolInformation` always, or can it return `DocumentSymbols`?

**Comment by ahoppen** [comment]
It currently always returns `SymbolInformation` and I don’t see any reason for us to change that in the foreseeable future.

**Comment by adam-fowler** [comment]
Ok that's cool. The client always has the option of both. 

By the way I have something up and running. I'll be posting a PR in the next day or so.

**Comment by plemarquand** [comment]
I'm in the process of looking at these and integrating them in to the Test Explorer.

**Comment by adam-fowler** [comment]
@plemarquand Please review #761 and #762 for more details about both requests. It was easier to break them out into separate issues. I going to close this in favour of the two new issues.
