### ISSUE TITLE
Show build progress in activity bar

### ISSUE THREAD

**Issue by ahoppen** [swift-server/vscode-swift#694]
Currently, when building, VS Code only shows `Building…` as an activity indicator (or whatever the thing in the bottom bar is called). It would be nice if it would show the current build progress as it’s output from `swift build` (e.g. `Building 6/9`)

**Comment by adam-fowler** [comment]
That's not easy. Builds are triggered by VSCode tasks and I have no access to stdout from a VSCode task.

**Comment by matthewbastien** [comment]
The VSCode API allows for custom execution of tasks. I can take a look to see how much extra work that would be.

**Comment by award999** [comment]
I'd love to run with this issue
