### ISSUE TITLE
Warning complaining about compiler arguments not found keep popping up

### ISSUE THREAD

**Issue by chawyehsu** [swift-server/vscode-swift#719]
**Describe the bug**

- [x] I did searching and didn't find any issue reported about this

![image](https://github.com/swift-server/vscode-swift/assets/5764917/8a3cbd6a-affb-49ac-9049-b060e9819d62)
Text: Failed to get compiler arguments for Package.swift. Ensure the source file is part of a Swift package or has compiler arguments in compile_commands.json. Functionality will be limited.

**To Reproduce**
1. Open a project and the warning will pop up

I tested with boilerplate project by `swift package init --type executable`, the warning is still there so I believe it's not something wrong with my working codebase.

**Expected behavior**

No warning

**Environment**
 - OS: Windows 10  10.0.19045
 - Swift version
     ```
     compnerd.org Swift version 6.0-dev (LLVM ce41a43bba95b2b, Swift 4336204fe47da60)
     Target: x86_64-unknown-windows-msvc
     ```
 - Visual Studio Code version: 1.87.0
 - vscode-swift version: 1.8.1

**Additional context**

I found everytime I [break the `sourcekit-lsp`](https://github.com/apple/sourcekit-lsp/issues/1115), it restarts and the warning will pop up again a time for every `.swift` file I open, which is so annoying. :-[

**Comment by chawyehsu** [comment]
Perhaps this should be reported to the `sourcekit-lsp` repo:
https://github.com/apple/sourcekit-lsp/blob/f7f2cea7c51f5e9ac4468fe9f3aacc306bb254de/Sources/SourceKitLSP/Swift/SwiftLanguageServer.swift#L366-L374

**Comment by adam-fowler** [comment]
This is a sourcekit-lsp issue. Please add a bug there
