### ISSUE TITLE
Unable to debug unit tests on VSCode Windows

### ISSUE THREAD

**Issue by softwarehangar7** [swift-server/vscode-swift#728]
I'm trying to debug a unit test on Windows, but I'm receiving the message `unable to find executable for <path for file>.xctest.exe` (see [swift forum discussion](https://forums.swift.org/t/debug-unit-tests-in-windows-with-vscode/70846/3) )

My build folder doesn't present any file with the .xctest.exe extension. Only .xctest.

Also, it is missing a part of the path. It should be `.build\x86_64-unknown-windows-msvc\debug`. It's missing the `x86_64-unknown-windows-msvc` part.

I am able to debug executables, but not unit libraries.

**To Reproduce**
Create any unit test for a swift lib.
Open VSCode, build all with `--build-tests`
Click the debug button on the Test Explorer

**Environment**
 - OS: Windows 10 Pro 21H2 19044.1387
 - Swift version: swift-5.10-RELEASE
 - Visual Studio Code version: 1.87.2
 - vscode-swift version: v1.8.1

**Comment by adam-fowler** [comment]
@compnerd is this a recent change to not include `.exe` at the end of xctest executable filenames? I was sure it was there previously.

**Comment by tristanlabelle** [comment]
I don't think it was ever there, but it really should be.

**Comment by adam-fowler** [comment]
This is odd, as I did have it working. I'm currently nowhere near my machine with the Windows VM so can't verify this. I'll probably have to rebuild it again as I haven't touched it in a few months as well. 

If I try to fix this blind can you verify this for me @tristanlabelle or @softwarehangar7

**Comment by adam-fowler** [comment]
I've had a look through the code and there is nowhere where the extension adds `.exe` to xctest executables. @softwarehangar7 Just to verify are you running/debugging tests through the TestExplorer? Also does running tests as opposed to debugging tests work ok?

**Comment by adam-fowler** [comment]
@softwarehangar7 Also finally if you enable setting `Swift: Diagnostics` in the the Advanced section of the Swift settings. When you run a TestExplorer debug session the launch config used by test explorer is output to the `Swift` output pane. If you could paste it here that'd be great.

**Comment by softwarehangar7** [comment]
Hi @adam-fowler and @tristanlabelle. I will test that.

**Comment by softwarehangar7** [comment]
> On my machine, `.build\debug` is created as a symbolic link to `.build\x86_64-unknown-windows-msvc\debug`. Is this not what you see @softwarehangar7 ? If you're missing the symlink, do you have developer mode turned on on your machine? I believe this enables symlinks.

That fixed all the issues. The path issue and also the `.xctest.exe` issue.

**Comment by softwarehangar7** [comment]
I didn't undestand why without symlink it was searching for `.xctest.exe` though

**Comment by adam-fowler** [comment]
I think this is something internal to vscode. If you try to run an
executable and it cannot find it then it tries the same name but with
“.exe” appended

**Comment by tristanlabelle** [comment]
@softwarehangar7 Nice to hear the issue is fixed. Was it specifically turning on developer mode in settings that did it?

**Comment by softwarehangar7** [comment]
@tristanlabelle Yes

**Comment by compnerd** [comment]
Perhaps we should verify that the user has the `SeCreateSymbolicLinkPrivilege` privilege before supporting test execution on Windows?

**Comment by tristanlabelle** [comment]
@compnerd I like the idea, but a few questions:
1. Does the `debug` symbolic link exist only to support testing or could it also affect just building / other uses of SPM?
2. Would testing work if using the full `x86_64-unknown-windows-msvc\debug` path?
3. Would it also fail if using `swift test` directly? 
What I'm getting at is: is lack of symbolic link a problem for SPM itself, such that it should report the error, or is it only a problem for the VS Code test integration?
