### ISSUE TITLE
I keep getting an error 'could not build Objective-C module ' name of module' sourcekitd

### ISSUE THREAD

**Issue by brucemontegani** [swift-server/vscode-swift#731]
I am using Hummingbird 2.0.0-beta.1
I keep getting an error message for the import of the 'HummingbirdTesting' module from the hummingbird package.
The error message is "could not build Objective-C module 'HummingbirdTesting'sourcekitd"

**To Reproduce**
1. clone this repo: [Todos](https://github.com/brucemontegani/Todos.git)
2. swift build
3. go to Tests/TestTodos.swift
4. See error when you hover over 'HummingbirdTesting'. It should have an error squiggly under it.

**Expected behavior**
I expected that the HummingbirdTesting module would be built and available.

**Environment**
 - OS: MacOS 14.2.1
 - swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
 - Visual Studio Code version: 1.87.2
 - vscode-swift version: 1.8.1

**Comment by adam-fowler** [comment]
Hey @brucemontegani you added a version of this bug 2 years ago #138. As I said at the time this is a sourcekit-lsp bug. 

Although if you follow all the links through all the issues you'll find it was SwiftPM bug which looks like it got fixed and merged 3 months ago. So will probably be in Swift 6. 

I'm going to close this as a duplicate.
