### ISSUE TITLE
Cross compiling on linux

### ISSUE THREAD

**Issue by santalvarez** [swift-server/vscode-swift#733]
Hi, 
Im trying to compile a swift project for the `armv7-none-none-eabi` target. The problem Im having is that I'm on linux and the extension keeps compiling for `x86_64-unknown-linux-gnu` target. I have tried setting the `-target` flag but I doesn't seem to have an effect. 

Maybe Im missing something but is there a way to prevent the extension from defaulting to the current target or is cross compiling not supported yet?

**Comment by adam-fowler** [comment]
How are you adding the `--target` argument?

**Comment by santalvarez** [comment]
Like this :
```json
    "swift.sourcekit-lsp.serverArguments": [
        "-Xswiftc", "-target", "-Xswiftc", "armv7-none-none-eabi"
    ]
```
I can compile with no problems from the command line with:
```bash
swift build --triple armv7-none-none-eabi
```
I tried using `--triple` and `--target` but can get it always defaults to the host's target.

**Comment by adam-fowler** [comment]
Go to the settings and add to the `Swift: Build Arguments`.
