### ISSUE TITLE
Rename variables and function

### ISSUE THREAD

**Issue by roydbt** [swift-server/vscode-swift#736]
**Is your feature request related to a problem? Please describe.**
Right now, nothing happens when I select a variable and click on the refactor button.

**Describe the solution you'd like**
What I would like to do is to be able to rename the variable.

**Describe alternatives you've considered**
Just manually rename it for every occurrence.

**Comment by adam-fowler** [comment]
This is something that sourcekit-lsp has to support and support has been added and will be available in Swift 6. See https://github.com/apple/sourcekit-lsp/issues/498

**Comment by adam-rocska** [comment]
Swift 6 is out, yet the feature still doesn't seem to work.

**Comment by plemarquand** [comment]
@adam-rocska This functionality is available through "Rename Symbol" when right clicking a symbol.

https://github.com/user-attachments/assets/7abe1418-b887-4157-b4d3-cf8e59e1d51b

If this isn't working for you please file a new GItHub issue with the details.
