### ISSUE TITLE
swift-lldb ignores the path when attaching to a process by program path

### ISSUE THREAD

**Issue by tristanlabelle** [swift-server/vscode-swift#745]
**Describe the bug**
`swift-lldb` `attach` debug configurations only match the executable filename despite being documented to match the full path:
https://github.com/swift-server/vscode-swift/blob/f3b76be242feda0763170aa14ff555386b607527/package.json#L991

**To Reproduce**
1. Run two programs with the same filename from two different directories
2. Create a `launch.json` configuration to attach to one of the program by full path
3. Start debugging that configuration
4. An error appears saying that the resolution is ambiguous:

![image](https://github.com/swift-server/vscode-swift/assets/2314287/017af27b-2462-4444-b8a2-9d403a39eb09)

**Expected behavior**
The debugger attaches to the process whose full path matches the one requested.

**Environment**
 - OS: Windows 11
 - Swift version (output of `swift --version`):
 ```
compnerd.org Swift version 6.0-dev (LLVM 4aa2cfd77d0beee, Swift 311c55f995371dc)
Target: x86_64-unknown-windows-msvc
```
 - Visual Studio Code version: 1.88.0
 - vscode-swift version: v1.8.1

**Comment by tristanlabelle** [comment]
I looked into this a bit and I'm not sure what component is doing the process listing and matching.

**Comment by adam-fowler** [comment]
I think this is a limitation of LLDB. The error message is coming from here https://github.com/apple/llvm-project/blob/00c794fb25f1085c060d5c46e34cbb6145837f1f/lldb/source/Target/Process.cpp#L3023

**Comment by tristanlabelle** [comment]
It looks like the name matching is only happening on the process filename, not full path: https://github.com/apple/llvm-project/blob/3cba3c783ca8712981734ee8ef7f2f56685a7a68/lldb/source/Utility/ProcessInfo.cpp#L301 .

I'll file a bug on lldb, but in the meanwhile the description of "program" is misleading.

**Comment by tristanlabelle** [comment]
Filed on LLDB as https://github.com/llvm/llvm-project/issues/88515 . Should we close this issue?

**Comment by adam-fowler** [comment]
Nothing we can do about it here
