### ISSUE TITLE
Use `textDocument/tests` LSP request to augment test list on active document save

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#762]
When a swift file is saved, make `textDocument/tests` LSP request and use the response to augment the test list generated from `workspace/tests`. 

Currently we are using a middleware to parse symbols from document symbols responses. This can be disabled for Swift 6 once the above is implemented. This is the code setting it up https://github.com/swift-server/vscode-swift/blob/dfba3243e6cb97faa45037d11478e2714d4d5e17/src/TestExplorer/TestExplorer.ts#L127-L133

**Comment by plemarquand** [comment]
Closed by #767
