### ISSUE TITLE
VSCode cannot read types generated by the OpenAPI Swift plugin (Xcode can).

### ISSUE THREAD

**Issue by dangdennis** [swift-server/vscode-swift#774]
**Describe the bug**

If you run one of the examples from [swift-openapi-generator](https://github.com/apple/swift-openapi-generator/tree/main/Examples), vscode is not able to read the types generated by the plugin. The types are visible in `./build/plugins/outputs/<library-name>`. However, the compiler builds just fine.

However, Xcode is able to understand the types used.

**To Reproduce**
1. Clone an [example](https://github.com/apple/swift-openapi-generator/tree/main/Examples/curated-client-library-example).
2. Open just the example project folder in vscode. 
3. Build the project with `swift build`.
4. Expect to see the types for `Client` and `APIProtocol` on mouse hover.

**Expected behavior**
I expect vscode to be able to recognize the generated types.

**Environment**
 - OS: macOS 14.4.1 (23E224)
 - Swift 5.10
 - Visual Studio Code version: 1.88.1 (Universal)
 - vscode-swift version: v1.9.0

**Comment by dangdennis** [comment]
Would love to help solve this as I've enjoyed the Swift on Server ecosystem and tools so far.

**Comment by adam-fowler** [comment]
> Would love to help solve this as I've enjoyed the Swift on Server ecosystem and tools so far.

Thank you for the offer. This is a known issue with SourceKit-LSP. It is tracked in https://github.com/apple/sourcekit-lsp/issues/665 and https://github.com/apple/swift-package-manager/issues/6700. 

I'm going to close this as a duplicate and also because it is not resolvable at the VSCode extension level.
