### ISSUE TITLE
Use nvm for CI builds

### ISSUE THREAD

**Issue by award999** [swift-server/vscode-swift#787]
To make sure all contributors are using the same version of node.js as the CI build, we should create a .nvmrc file that is in sync with https://github.com/microsoft/vscode/blob/main/.nvmrc and update the Dockerfile to use nvm instead of installing a set version. Update https://github.com/swift-server/vscode-swift/blob/main/CONTRIBUTING.md to indicate nvm setup

**Comment by adam-fowler** [comment]
Done
