### ISSUE TITLE
Windows Debug settings

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#80]
>> I had to look up a few things here, so just to make sure I understand this correctly:
> 
> * Is CodeView the default on Windows (when just using `swift build` for example)?

> No, the default is no debug info :). `-g -debug-info-format=codeview` enables codeview, `-g` enables DWARF.

> > * Should we always add `-debug` when creating a debug build using CodeView?

> Yes, `-debug` should be specified always when building with CodeView debug info.

> > * What would be an appropriate name for this configuration setting? "Debug using DWARF"?

> That is what I would call it.  "Debug (DWARF)" and "Debug (CodeView)" is what I use.  But the using rather than the parenthetical is better for display purposes perhaps.

> What should be the default, if we want to make sure things "just work" for new developers?

> My preference would be CodeView.  There are some bugs that we do need to sort out, but the same can be said for DWARF (and arguably more).  However, if you do use CodeView, you can deal with mixed-language projects (C/C++/Swift) and debug across system code and Swift code.  Additionally, I've found that lldb is still not particularly stable and causes trouble, and using DWARF mandates the use of lldb (at this point).

_Originally posted by @compnerd in https://github.com/swift-server/vscode-swift/pull/75#discussion_r774765271_

Hi @compnerd,

I'm a little confused previously you said for DWARF we should use parameters `-use-ld=lld -debug:dwarf`. Now you are saying we just need `-g`.

As an aside the swift extension provides integration with the CoreLLDB extension so we will be targeting LLDB for the immediate future, so I assume we want DWARF.

**Comment by compnerd** [comment]
> >> I had to look up a few things here, so just to make sure I understand this correctly:
> 
> > 
> 
> > * Is CodeView the default on Windows (when just using `swift build` for example)?
> 
> 
> 
> > No, the default is no debug info :). `-g -debug-info-format=codeview` enables codeview, `-g` enables DWARF.
> 
> 
> 
> > > * Should we always add `-debug` when creating a debug build using CodeView?
> 
> 
> 
> > Yes, `-debug` should be specified always when building with CodeView debug info.
> 
> 
> 
> > > * What would be an appropriate name for this configuration setting? "Debug using DWARF"?
> 
> 
> 
> > That is what I would call it.  "Debug (DWARF)" and "Debug (CodeView)" is what I use.  But the using rather than the parenthetical is better for display purposes perhaps.
> 
> 
> 
> > What should be the default, if we want to make sure things "just work" for new developers?
> 
> 
> 
> > My preference would be CodeView.  There are some bugs that we do need to sort out, but the same can be said for DWARF (and arguably more).  However, if you do use CodeView, you can deal with mixed-language projects (C/C++/Swift) and debug across system code and Swift code.  Additionally, I've found that lldb is still not particularly stable and causes trouble, and using DWARF mandates the use of lldb (at this point).
> 
> 
> 
> _Originally posted by @compnerd in https://github.com/swift-server/vscode-swift/pull/75#discussion_r774765271_
> 
> 
> 
> Hi @compnerd,
> 
> 
> 
> I'm a little confused previously you said for DWARF we should use parameters `-use-ld=lld -debug:dwarf`. Now you are saying we just need `-g`.
> 

You missed the important parts of it!

-Xswiftc -g -Xswiftc -use-ld=lld -Xlinker -debug:dwarf

Should give you DWARF debug info.

> 
> 
> As an aside the swift extension provides integration with the CoreLLDB extension so we will be targeting LLDB for the immediate future, so I assume we want DWARF.

I would strongly recommend against that.  About 75% of the time that will just crash (anything calling through the swift runtime into the system will cause lldb to die).  Furthermore, you will not be able to debug anything that is not pure swift with no system interaction.  You really do want CodeView for a convenient debug experience.

**Comment by adam-fowler** [comment]
@compnerd can we use CodeView with lldb?

I guess we can add an option to the extension to emit DWARF or CodeView?

**Comment by compnerd** [comment]
> @compnerd can we use CodeView with lldb?
> 

In theory or in practice? 😂. LLDB is almost unusable with PDBs with the native naïve setup.  I expect that if you configure the lldb session properly so that it uses DIA, that might fare a bit better.

> I guess we can add an option to the extension to emit DWARF or CodeView?

Having the option really would be best.

**Comment by compnerd** [comment]
Another option would be to integrate https://marketplace.visualstudio.com/items?itemName=reznikdi.windbg-debug

**Comment by Manak0786** [comment]
#141

**Comment by adam-fowler** [comment]
DWARF debug options implemented in #148

**Comment by adam-fowler** [comment]
Closing this as #148 is merged and I've opened #153 to discuss CodeView
