### ISSUE TITLE
Ensure GH CodeSpaces work

### ISSUE THREAD

**Issue by 0xTim** [swift-server/vscode-swift#81]
We should ensure that the extension works when running in GitHub CodeSpaces ~~and on vscode.dev~~. I'm pretty sure they should be fine as remote containers now work but we might need to provide some additional configuration or ensure a Dockerfile is set up correctly. Any required setup should go in the docs

**Comment by adam-fowler** [comment]
Not sure how of the extension we can run in Codespaces seeing as we cannot run external processes or get direct access to the filesystem. We might be able to get the LSP server running as there is support for running lsp servers via a web worker.

https://vscode.trafficmanager.net/api/extension-guides/web-extensions

**Comment by damuellen** [comment]
Unfortunately, the extension is a bit too eager, and wants to update the VSCode settings on every start of the codespace.

`CodeLLDB requires the correct Swift version of LLDB for debugging. Do you want to set this up in your global settings or the workspace settings?`

If you accept the following setting will be set
`"lldb.library": "/usr/lib/x86_64-linux-gnu/liblldb-6.0.so"`

This path does not work for me, LLDB cannot be started.

The correct path is. 
`"lldb.library": "/usr/lib/liblldb.so"`

**Comment by adam-fowler** [comment]
Interesting the lldb library the extension wants to use is the library that the swift version of lldb reports it is using. 

How are you setting up to run in Codespaces? I haven't looked into the Codespace stuff at all yet.

**Comment by adam-fowler** [comment]
> I use a slightly modified version of [devcontainer](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/swift/.devcontainer)

What version of the extension are you running? There was a fix in 0.1.1 related to remote containers and lldb.

**Comment by adam-fowler** [comment]
Also that devcontainer includes a different swift extension. 

Have you tried something a little simpler

```

{
    "name": "Swift 5.5",
    "image": "swift:5.5",
    "extensions": [
      // vscode-lldb is automatically loaded as swift-lang is dependent on it
      "sswg.swift-lang",
    ],
    "settings": {
      // this setting stops the swift extension trying to set the linux lldb path in your workspace
      "lldb.library": "/usr/lib/liblldb.so"
    }
}
```

**Comment by damuellen** [comment]
This is my devcontainer.json

`{
	"name": "Swift",
	"build": {
		"dockerfile": "Dockerfile",
		"args": {
			"VARIANT": "latest",
			"INSTALL_NODE": "false",
			"NODE_VERSION": "lts/*"
		}
	},
	"runArgs": [
		"--cap-add=SYS_PTRACE",
		"--security-opt",
		"seccomp=unconfined"
	],
	"settings": {
		"lldb.library": "/usr/lib/liblldb.so",
		"lldb.launch.expressions": "native",
		"lldb.evaluateForHovers": false,
		"terminal.integrated.scrollback": 50000,
		"terminal.integrated.defaultLocation": "editor",
		"sourcekit-lsp.toolchainPath": "/usr/bin/",
		"sourcekit-lsp.serverPath": "/usr/bin/sourcekit-lsp",
		"apple-swift-format.path": "/workspaces/swift-format/.build/release/swift-format",
	},
	"extensions": [
		//"pvasek.sourcekit-lsp--dev-unofficial",
                "sswg.swift-lang",
		"vadimcn.vscode-lldb",
		"hbenl.vscode-test-explorer",
		"makeitbetter.vscode-swift-test-adapter",
		"cweijan.vscode-office",
		"philhindle.errorlens",
		"wattenberger.footsteps"
	], 
}
`

**Comment by damuellen** [comment]
I found the solution, the dockerfile from MS installs LLDB. Without it the extension does the right thing.
[Dockerfile](https://github.com/microsoft/vscode-dev-containers/blob/9c56a9ac8ec618b6a1a4eaf987f8f9b7da31c86e/containers/swift/.devcontainer/Dockerfile#L17)

**Comment by adam-fowler** [comment]
> I found the solution, the dockerfile from MS installs LLDB. Without it the extension does the right thing.
> 
> [Dockerfile](https://github.com/microsoft/vscode-dev-containers/blob/9c56a9ac8ec618b6a1a4eaf987f8f9b7da31c86e/containers/swift/.devcontainer/Dockerfile#L17)

Oh yeah I remember seeing that. I think at that point I decided I'd use my simple devcontainer from above. The MS version does all sorts of stuff that doesn't seem that necessary.

**Comment by damuellen** [comment]
I made a pull request at microsoft, so that no one else stumbles across this.
https://github.com/microsoft/vscode-dev-containers/pull/1238

**Comment by adam-fowler** [comment]
Given vscode.dev and CodeSpaces are different things I think we should break this into two issues. I believe once microsoft/vscode-dev-containers#1238 is resolved we can do the same for CodeSpaces.

vscode.dev is a different thing and requires us supporting web extensions which severely limits what we can do.

**Comment by 0xTim** [comment]
Ok I agree. I'll change this to Codespaces and create a separate issue for vscode.dev

**Comment by 0xTim** [comment]
As an aside - does anyone have access to Codespaces? I didn't get on to the individual beta and none of the orgs I control has been given access to it yet

**Comment by damuellen** [comment]
In Codespace it works as it should, I have not tested another setup.
