### ISSUE TITLE
Feature request: setting to toggle displaying inline inferred type annotations

### ISSUE THREAD

**Issue by tinder-tannerbennett** [swift-server/vscode-swift#812]
**Is your feature request related to a problem? Please describe.**
Sometimes they just get in the way and I'd rather not see them, especially for local variables.

**Describe the solution you'd like**
I would like a setting for this extension to toggle the visibility of inline inferred type annotations

**Describe alternatives you've considered**
Ideally there would be separate settings to show inferred type annotations for arguments, properties, and local variables… but for now, one setting to flip them all on or off would be wonderful.

**Comment by adam-fowler** [comment]
Search for inline hints in the settings. A setting already exists in the standard VSCode settings
