### ISSUE TITLE
Provide docs for VSCode Remote Development

### ISSUE THREAD

**Issue by 0xTim** [swift-server/vscode-swift#82]
We should provide documentation for how to set up a development environment in VSCode with the extension using VSCode Remote Development. May be related to #81

Here's an old article that should still mostly apply https://medium.com/@ianpartridge/swift-development-in-docker-using-visual-studio-code-remote-b84d035e70db

**Comment by iainsmith** [comment]
The official Microsoft templates for vscode devcontainers are [here](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/swift). GitHub codespaces provides a setup flow that lets people select from the list in this repo. 

Personally I think it's reasonable to migrate the official devcontainer setup from the existing plugin to the SSWG plugin.

There is also some existing node setup this I think can be trimmed out.

**Comment by pvzig** [comment]
Not sure what the state of the world is in terms of the best lldb extension but using the one mentioned in the linked article worked for me.

Using a Dockerfile from the `swift:5.5.2` image with this `devcontainer` config:
```
{
  "name": "Test",
  "build": { "dockerfile": "Dockerfile" },
  "extensions": [
    "sswg.swift-lang",
    "vadimcn.vscode-lldb"
  ],
  "settings": {
    "lldb.adapterType": "bundled",
    "lldb.executable": "/usr/bin/lldb"
  }
}
```

**Comment by adam-fowler** [comment]
This is all you need for a dev container
```swift
{
    "name": "Swift 5.5",
    "image": "swift:5.5",
    "extensions": [
      // vscode-lldb is automatically loaded as swift-lang is dependent on it
      "sswg.swift-lang",
    ],
    "settings": {
      // this setting stops the swift extension trying to set the linux lldb path in your workspace
      "lldb.library": "/usr/lib/liblldb.so"
    }
}
```

**Comment by adam-fowler** [comment]
The Microsoft provided swift devcontainer references the other swift extension and does bad things like install its own version of lldb. We should get this fixed.
