### ISSUE TITLE
Relaunching the LSP Server doesn't clean up the output sections

### ISSUE THREAD

**Issue by nmggithub** [swift-server/vscode-swift#839]
**Describe the bug**
I am working on a complex Swift package, and I sometimes need to relaunch the LSP in order to see changes I make propagate. Doing so, however, seems to add an entry to the Output section in VSCode every time.

**To Reproduce**
1. Go to the Output tab in the bottom panel in VSCode
2. Open the dropdown of output sections
3. Observe a single entry of "Swift" and a single entry of "SourceKit Language Server"
4. Press Command-Shift-P and find the "Swift: Restart LSP Server" option and select it
5. Go back to the dropdown and observe a second entry of "SourceKit Language Server"
6. Repeat step 4 and observe a new entry each time.

**Expected behavior**
Restarting the LSP server should not add an entry each time, or, at the very least, these entries should be distinguished from each other.

**Environment**
 - OS: macOS 14.5
 - Swift version (output of `swift --version`)
 ```
 swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```
 - Visual Studio Code version: 1.89.1
 - vscode-swift version: v1.9.0

**Comment by adam-fowler** [comment]
I think this is probably a bug with VSCode, I don't control the display of this view. I'll have a look to see if there is anyway I can clear this.
Hopefully with Swift 6 you won't need to restart the server so much. There have been many improvements to SourceKit-LSP which will become available then.

**Comment by plemarquand** [comment]
@adam-fowler I had some luck here disposing the old client's output channel on a restart in #841. This removes the entry from the output list.
