### ISSUE TITLE
Sometimes get in state where swift Test Result never ends

### ISSUE THREAD

**Issue by award999** [swift-server/vscode-swift#844]
**Describe the bug**
Sometimes get in state where swift Test Result never ends

**To Reproduce**
1. From the test explorer run a suite or test, either normally and in coverage mode
2. Keep doing this over and over, can select different tests and suites
Eventually get is a state where Test Results never stops (wheel keeps spinning):

<img width="466" alt="Screenshot 2024-06-05 at 2 29 22 PM" src="https://github.com/swift-server/vscode-swift/assets/78549403/2738c14d-7bb4-42bf-baad-51c6f028d7d4">

 and all subsequent ones do the same:
<img width="466" alt="Screenshot 2024-06-05 at 2 37 10 PM" src="https://github.com/swift-server/vscode-swift/assets/78549403/1a65f16d-614d-4f20-9757-045638b4d1bf">

**Expected behavior**
Stops the test execution

**Environment**
 - OS: MacOS
 - Swift version (output of `swift --version`) 6.0 Snapshot
 - Visual Studio Code version:
 - vscode-swift version:

**Additional context**
I could not find the magic combination of clicks to reproduce this reliably but usually happened around 10-15 test runs

**Comment by plemarquand** [comment]
This should be addressed by #845 and #837

**Comment by adam-fowler** [comment]
> This should be addressed by #845 and #837

As both of these are merged this should be fixed. @award999 can you verify

**Comment by award999** [comment]
yep :)

**Comment by award999** [comment]
Verified alongside https://github.com/swift-server/vscode-swift/pull/855, things look good
