### ISSUE TITLE
When `"testing.openTesting": "openOnTestFailure" is set and a test failed, the terminal window is opened instead of the test output

### ISSUE THREAD

**Issue by ahoppen** [swift-server/vscode-swift#862]
I have the `"testing.openTesting": "openOnTestFailure"` setting set an in version 1.9.0 a test failure opened the test output view. Now it opens the `Build and Running Tests` terminal view.

**Comment by award999** [comment]
Verified with 205c628e9007f5ee26c16352ee27f3883916e4b2
