### ISSUE TITLE
[Feature] Debug as root

### ISSUE THREAD

**Issue by mickeyl** [swift-server/vscode-swift#87]
Would it be possible to support debugging as `root`? It looks like the configuration entry `"sudo": true` is not supported.

For programs that (re)configure network interfaces, all other options (capabilities, setuid, and the like) are second best.

**Comment by adam-fowler** [comment]
This is a CodeLLDB issue

**Comment by mickeyl** [comment]
If anyone stumbles over this request… for the records: The folks at CodeLLDB don't see the necessity for this feature. Thankfully the CLion developers did add that on my request now.
