### ISSUE TITLE
It would be nice to have code coverage report generated after a test run

### ISSUE THREAD

**Issue by karthikkeyan** [swift-server/vscode-swift#88]
I have used VS Code, but not as a day-to-day editor. I am not sure if this is achievable in VS(i hope it is).

In Xcode, we get the coverage after a test run. It would be really good to add some of that type.
There are two types of coverage information we get from Xcode,
1. Coverage report as a part of test run
<img width="677" alt="Screen Shot 2021-12-24 at 5 50 09 AM" src="https://user-images.githubusercontent.com/1664261/147357395-ed76b275-353b-47f9-9727-a6a87e414840.png">

2. Individual file's code coverage where we could open a file and check the execution's reach.
<img width="1072" alt="Screen Shot 2021-12-24 at 5 56 11 AM" src="https://user-images.githubusercontent.com/1664261/147357462-96711bbb-48b7-499f-9198-0568171c6520.png">

It would be nice to have these two in VS Code as well.

**Comment by svanimpe** [comment]
This may be a good starting point: https://marketplace.visualstudio.com/items?itemName=vknabel.swift-coverage
I haven't tried it yet, so I don't know how (well) it works.

**Comment by karthikkeyan** [comment]
Thanks, @svanimpe. I will try that.

**Comment by adam-fowler** [comment]
vscode are coming up with an official UI for this. We'll probably wait until that is available

https://github.com/microsoft/vscode/issues/123713

**Comment by adam-fowler** [comment]
I have added an extra test run profile in #456 which generates `.lcov` files when running all the tests. This file can then be used in one of the code coverage rendering extensions that are already available (eg https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters). This will be available in v0.10.0

Code Coverage `.lcov` generation can be found here
![image](https://user-images.githubusercontent.com/9382567/210961393-bd741d16-b1dd-4cbb-8a45-4eff0d15009c.png)
