### ISSUE TITLE
Make CodeLLDB optional

### ISSUE THREAD

**Issue by lijhj** [swift-server/vscode-swift#89]
Can you make CodeLLDB optional? CodeLLDB is 37M and the swift extension fails to install due to this on a slow connection.

I just need to read the code and the Outline view in VSCode. Xcode doesn't have Outline view.

**Comment by svanimpe** [comment]
Without CodeLLDB, you won't be able to debug or run anything. If you want to avoid it, it may be better to only install the SourceKit-LSP extension (sourcekit-lsp/Editors/vscode at main · apple/sourcekit-lsp · GitHub). That will give you all the basic functionality (code completion, jump to definition, ...).

**Comment by 0xTim** [comment]
Unfortunately there's [no way to have optional dependencies in an extension](https://github.com/microsoft/vscode/issues/6384#issuecomment-940834665) so we always need to pull it down. VSCode has Swift syntax highlighting by default so if you don't install the extension you can still open a package, browse code and view the outline. You won't however be able to click through to definition etc.

I'm going to close this as it's not something we can support.

As an aside, I've [added a PR](https://github.com/apple/sourcekit-lsp/pull/441) to SourceKit-LSP to remove the extension as we consumed it and will extend and add more features.
