### ISSUE TITLE
Changes to the manifest don't update errors

### ISSUE THREAD

**Issue by 0xTim** [swift-server/vscode-swift#96]
See https://www.alwaysrightinstitute.com/tows-vsc/

Adding a required macOS platform in Package.swift does not get rid of availability errors.

**Comment by adam-fowler** [comment]
https://bugs.swift.org/browse/SR-15679

**Comment by adam-fowler** [comment]
Fixed in https://github.com/apple/sourcekit-lsp/pull/471
