### ISSUE TITLE
Check adding new file doesn't require a restart

### ISSUE THREAD

**Issue by 0xTim** [swift-server/vscode-swift#97]
Apparently a long standing issue with the old SourceKit-LSP extension, adding a new file required VSCode to be restarted in order to pick up new types - https://twitter.com/maxdesiatov/status/1473276649206689795?s=21

We should check if this is still and issue and fix it if so

**Comment by adam-fowler** [comment]
I would assume VSCode is doing all of this for us. Looking at other LSP integrations they don't have triggers for new files so I would assume this is internal to vscode. Without compiling my own version of the server not sure what is happening here. 

I do have a hack fix though which just completely restarts the server whenever a new file is created. Not sure how solid this is though.

**Comment by adam-fowler** [comment]
Added a bug for Swift guys https://bugs.swift.org/browse/SR-15633

**Comment by adam-fowler** [comment]
https://github.com/apple/sourcekit-lsp/pull/443
in sourcekit-lsp repo fixes this. There is hope this will appear in Swift 5.6

**Comment by svanimpe** [comment]
I also noticed that SourceKit-LSP doesn't always pick up new type members. For example, I'm working on a package that has both a library and an executable that depends on it. Whenever I add new members to an existing type in the library and use them in the executable, I have to restart VS Code to get rid of compiler "errors" in the executable. The code builds and runs just fine, SourceKit just doesn't seem to see the new members.

**Comment by adam-fowler** [comment]
@svanimpe did you compile between the adding of the member and using it in the executable code. I believe you need to recompile to get the completion of new members working. 

There is something about this in the readme for sourcekit-lap

**Comment by svanimpe** [comment]
Yes, I did (using the Build All task). I haven't quite figured out what's wrong. Sometimes the errors do disappear (eventually), but I'm not sure what triggers that.

**Comment by adam-fowler** [comment]
> Yes, I did (using the Build All task). I haven't quite figured out what's wrong. Sometimes the errors do disappear (eventually), but I'm not sure what triggers that.

Best adding an issue in the sourcekit-lsp repository

**Comment by adam-fowler** [comment]
> Best adding an issue in the sourcekit-lsp repository

Ah you can't. I guess use the forums or add a bug in bugs.swift.org

**Comment by svanimpe** [comment]
Done: https://bugs.swift.org/browse/SR-15743

This is quite annoying, as I now have to restart VS Code not only after adding a new file, but also after changing the API of a module 😕

**Comment by adam-fowler** [comment]
Fixed for swift 5.6 and #130 fixes this for earlier versions of swift
